import GMZP0

/-! Print transitive axioms of every exported project theorem. -/

#print axioms GMZP0.cubic_lag_difference
#print axioms GMZP0.lag_target_coordinate
#print axioms GMZP0.double_phase_reroot
#print axioms GMZP0.fourth_difference_cubic
#print axioms GMZP0.linear_collision_eight
#print axioms GMZP0.norm_cubicPhase
#print axioms GMZP0.card_base
#print axioms GMZP0.cubicPhase_coe_real
#print axioms GMZP0.cubicDistanceSq_nonneg
#print axioms GMZP0.cubicDistance_nonneg
#print axioms GMZP0.cubicDistance_sq
#print axioms GMZP0.norm_response_le_one
#print axioms GMZP0.mean_le_root_mean_square
#print axioms GMZP0.norm_response_sub_le
#print axioms GMZP0.aligned_response_transfer
#print axioms GMZP0.norm_response_transfer
#print axioms GMZP0.exists_ge_mean
#print axioms GMZP0.finite_response_selection
#print axioms GMZP0.original_response_of_finite_capture
#print axioms GMZP0.weighted_response_le_mean
#print axioms GMZP0.captured_response_lower_bound
#print axioms GMZP0.small_scale_selection
#print axioms GMZP0.exists_response_alignment
#print axioms GMZP0.thresholdWeight_bounds
#print axioms GMZP0.thresholdWeight_support
#print axioms GMZP0.thresholdWeight_mass
#print axioms GMZP0.original_admissible_data
#print axioms GMZP0.p0_of_weightedCapture
#print axioms GMZP0.root_sum_square_add_le
#print axioms GMZP0.cubicDistance_self
#print axioms GMZP0.cubicDistance_symm
#print axioms GMZP0.cubicDistance_triangle
#print axioms GMZP0.cubicDistance_le_of_label_bound
#print axioms GMZP0.exists_nearest_frequency_lift
#print axioms GMZP0.cubicPhase_add
#print axioms GMZP0.cubicPhase_zero
#print axioms GMZP0.norm_cubicPhase_sub
#print axioms GMZP0.real_cubicPhase_chord_le
#print axioms GMZP0.cubicPhase_chord_le
#print axioms GMZP0.cubicDistance_le_circle_scale
#print axioms GMZP0.cubicDistance_le_of_scaled_circle_error
#print axioms GMZP0.integer_cast_frequency
#print axioms GMZP0.zero_branch_division_counterexample
#print axioms GMZP0.circle_root_decomposition
#print axioms GMZP0.circle_root_with_real_error
#print axioms GMZP0.circle_approx_root_decomposition
#print axioms GMZP0.circle_approx_root_fullLabel
#print axioms GMZP0.real_grid_rounding
#print axioms GMZP0.cubic_scale_grid_rounding
#print axioms GMZP0.grid_index_mem
#print axioms GMZP0.gridIndices_nonempty
#print axioms GMZP0.majorArc_grid_approximation
#print axioms GMZP0.majorArc_universal_list
#print axioms GMZP0.weighted_mass_le_energy
#print axioms GMZP0.retained_mass_from_energy
#print axioms GMZP0.assigned_weighted_energy
#print axioms GMZP0.assigned_minor_energy
#print axioms GMZP0.major_mass_of_minor_energy
#print axioms GMZP0.endpoint_eq_inputPoint
#print axioms GMZP0.card_inputBox
#print axioms GMZP0.inputEnergy_le
#print axioms GMZP0.finiteResponse_original
#print axioms GMZP0.profileMinorEnergy_of_finite_estimate
#print axioms GMZP0.finite_estimates_assigned_energy
#print axioms GMZP0.freezing_energy_budget
#print axioms GMZP0.finite_capture_from_model_energy
#print axioms GMZP0.finite_capture_from_model_operators
#print axioms GMZP0.inputPoint_injective
#print axioms GMZP0.endpointIndex_label_injective
#print axioms GMZP0.endpointIndex_base_injective
#print axioms GMZP0.endpointIndex_same_horizontal
#print axioms GMZP0.integer_parabola_collision
#print axioms GMZP0.collision_lag_displacement
#print axioms GMZP0.kernel_adjoint_identity
#print axioms GMZP0.kernel_comp_adjoint
#print axioms GMZP0.gramKernel_conjugate
#print axioms GMZP0.responseKernel_action
#print axioms GMZP0.finiteResponse_adjoint_identity
#print axioms GMZP0.responseKernel_gram
#print axioms GMZP0.responseKernel_gram_same_horizontal
#print axioms GMZP0.responseKernel_horizontal_block
#print axioms GMZP0.finiteEnergy_nonneg
#print axioms GMZP0.finitePairing_self
#print axioms GMZP0.finitePairing_norm_sq_le
#print axioms GMZP0.weighted_original_pairing
#print axioms GMZP0.weighted_original_adjoint_sq_le
#print axioms GMZP0.weighted_original_adjoint_lower
#print axioms GMZP0.alignedWeightVector_energy_le
#print axioms GMZP0.finiteAdjoint_energy_gram
#print axioms GMZP0.weighted_original_response_lower
#print axioms GMZP0.gram_same_horizontal_energy
#print axioms GMZP0.finiteAdjoint_energy_split
#print axioms GMZP0.weighted_offHorizontal_lower
#print axioms GMZP0.originalScaledWeight_bounds
#print axioms GMZP0.originalScaledWeight_mass
#print axioms GMZP0.originalScaledWeight_support
#print axioms GMZP0.originalScaledWeight_response
#print axioms GMZP0.original_window_response_lower
#print axioms GMZP0.offHorizontalEnergy_blocks
#print axioms GMZP0.offBlockNormSum_nonneg
#print axioms GMZP0.offHorizontalEnergy_le_blocks
#print axioms GMZP0.weighted_first_tt_lower
#print axioms GMZP0.original_window_first_tt
#print axioms GMZP0.horizontalPairing_adjoint_bound
#print axioms GMZP0.horizontalPairing_zero_left
#print axioms GMZP0.horizontalPairing_zero_right
#print axioms GMZP0.offBlockNormSum_restrict
#print axioms GMZP0.secondAdjointEnergy_nonneg
#print axioms GMZP0.offBlockNormSum_sq_le
#print axioms GMZP0.offBlockNormSum_second_adjoint
#print axioms GMZP0.original_window_second_adjoint
#print axioms GMZP0.endpointIndex_collision_iff
#print axioms GMZP0.nonparallel_collision_unique
#print axioms GMZP0.collision_target_unique
#print axioms GMZP0.horizontalKernel_of_collision
#print axioms GMZP0.horizontalKernel_no_collision
#print axioms GMZP0.horizontalKernel_norm
#print axioms GMZP0.horizontal_collision_count
#print axioms GMZP0.horizontalKernel_row_energy_le
#print axioms GMZP0.kernelAdjoint_energy_gram
#print axioms GMZP0.gram_diagonal_interaction
#print axioms GMZP0.gram_interaction_original_weights
#print axioms GMZP0.zero_pairing_nonzero_adjoint
#print axioms GMZP0.kernelAdjoint_energy_split
#print axioms GMZP0.finite_signed_original_weights
#print axioms GMZP0.secondDiagonalEnergy_nonneg
#print axioms GMZP0.secondAdjointEnergy_split
#print axioms GMZP0.secondDiagonalEnergy_le
#print axioms GMZP0.original_window_second_diagonal
#print axioms GMZP0.original_window_finite_signed_lower
#print axioms GMZP0.parabola_shift_abs_le
#print axioms GMZP0.safe_vertical_shift
#print axioms GMZP0.safe_parabola_target
#print axioms GMZP0.safe_lag_target
#print axioms GMZP0.exists_original_vertical_point
#print axioms GMZP0.safe_original_target_exists
#print axioms GMZP0.horizontal_interval_gap
#print axioms GMZP0.vertical_lag_zero_iff
#print axioms GMZP0.fin_initial_strip_card_le
#print axioms GMZP0.fin_final_strip_card_le
#print axioms GMZP0.fin_boundary_strips_card_le
#print axioms GMZP0.mem_safeRows_iff
#print axioms GMZP0.boundaryBaseSet_card_le
#print axioms GMZP0.boundary_original_mass_le
#print axioms GMZP0.safe_boundary_mass_partition
#print axioms GMZP0.safe_original_mass_lower
#print axioms GMZP0.horizontal_partition_cover
#print axioms GMZP0.horizontalChunk_interval
#print axioms GMZP0.mem_horizontalChunk_iff
#print axioms GMZP0.horizontalChunk_gap
#print axioms GMZP0.chunkWindow_geometry
#print axioms GMZP0.chunkWindow_mass_partition
#print axioms GMZP0.exists_mean_chunk
#print axioms GMZP0.exists_heavy_chunk
#print axioms GMZP0.windowModulus_pos
#print axioms GMZP0.safeWindowMass_pos
#print axioms GMZP0.window_boundary_budget
#print axioms GMZP0.exists_original_safe_chunk
#print axioms GMZP0.uniform_safe_window
#print axioms GMZP0.safe_chunk_target_exists
#print axioms GMZP0.original_weight_mass_le_one
#print axioms GMZP0.positive_from_signed_bound
#print axioms GMZP0.finiteStatisticThreshold_pos
#print axioms GMZP0.uniform_positive_from_signed_bound
#print axioms GMZP0.uniform_positive_safe_statistic
#print axioms GMZP0.circleCharacter_add
#print axioms GMZP0.circleCharacter_neg
#print axioms GMZP0.circleCharacter_sub
#print axioms GMZP0.circleCharacter_real
#print axioms GMZP0.cubicPhase_integer
#print axioms GMZP0.double_phase_character
#print axioms GMZP0.doublePhaseCoefficient_reroot
#print axioms GMZP0.integer_label_bounds
#print axioms GMZP0.horizontalGap_ne_zero
#print axioms GMZP0.mem_blockLabels_iff
#print axioms GMZP0.mem_lagLabels_iff
#print axioms GMZP0.lag_labels_bound
#print axioms GMZP0.lag_domain_reroot
#print axioms GMZP0.double_collision_coordinates
#print axioms GMZP0.double_collision_labels
#print axioms GMZP0.double_collision_zero_lag_iff
#print axioms GMZP0.double_kernel_original_phase
#print axioms GMZP0.double_kernel_original_weighted_phase
#print axioms GMZP0.oneBasedIndex_label
#print axioms GMZP0.shiftedBlockLabel_value
#print axioms GMZP0.blockTarget_coordinate
#print axioms GMZP0.blockTarget_injective
#print axioms GMZP0.blockTarget_collision
#print axioms GMZP0.collision_in_blockTargets
#print axioms GMZP0.blockFinLabels_membership
#print axioms GMZP0.horizontalKernel_label_formula
#print axioms GMZP0.horizontalBlock_action_labels
#print axioms GMZP0.blockCoefficient_character
#print axioms GMZP0.oneBasedIndex_of_label
#print axioms GMZP0.blockLabelEquiv_symm_value
#print axioms GMZP0.horizontalBlock_action_integer_labels
#print axioms GMZP0.label_difference_bound
#print axioms GMZP0.lagSource_coordinate
#print axioms GMZP0.lagSource_injective
#print axioms GMZP0.lagSource_self
#print axioms GMZP0.lagSource_eq_self_iff
#print axioms GMZP0.lagSource_collision
#print axioms GMZP0.collision_in_lagSources
#print axioms GMZP0.horizontalKernel_lag_weighted_sum
#print axioms GMZP0.horizontalGram_action_labels
#print axioms GMZP0.horizontalGram_offDiagonal_labels
#print axioms GMZP0.horizontalGram_offDiagonal_original_phase
#print axioms GMZP0.lagLabels_empty_of_large_lag
#print axioms GMZP0.mem_lagPairDomain_iff
#print axioms GMZP0.integer_label_pair_sum
#print axioms GMZP0.sum_blockFinLabels
#print axioms GMZP0.label_difference_ne_zero_iff
#print axioms GMZP0.distinct_label_pair_sum
#print axioms GMZP0.originalFieldExtension_vertical_outside
#print axioms GMZP0.originalFieldExtension_base
#print axioms GMZP0.originalFieldExtension_lagSource
#print axioms GMZP0.originalFieldExtension_blockTarget
#print axioms GMZP0.originalLagSummand_labels
#print axioms GMZP0.horizontalGram_offDiagonal_lag
#print axioms GMZP0.secondOffDiagonalEnergy_lag
#print axioms GMZP0.finiteSignedDoubleStatistic_eq_lag
#print axioms GMZP0.original_window_statistic_eq_lag
#print axioms GMZP0.uniform_positive_safe_lag_statistic
#print axioms GMZP0.mem_rerootLabels_iff
#print axioms GMZP0.reroot_lag_bound
#print axioms GMZP0.mem_rerootPairDomain_iff
#print axioms GMZP0.lag_sum_reroot
#print axioms GMZP0.originalLagSummand_zero_lag
#print axioms GMZP0.originalLagSummand_zero_nonneg
#print axioms GMZP0.lag_sum_split_zero
#print axioms GMZP0.fullLagNumerator_split
#print axioms GMZP0.fullLagStatistic_split
#print axioms GMZP0.lagDiagonalStatistic_nonneg
#print axioms GMZP0.lagSigned_le_full
#print axioms GMZP0.lagLabels_zero
#print axioms GMZP0.blockLabels_card_le
#print axioms GMZP0.zero_lag_row_le
#print axioms GMZP0.zeroLagNumerator_le
#print axioms GMZP0.lagDiagonalStatistic_le
#print axioms GMZP0.original_window_lag_diagonal_le
#print axioms GMZP0.originalLagSummand_reroot
#print axioms GMZP0.rerooted_inner_average
#print axioms GMZP0.fullLagNumerator_reroot
#print axioms GMZP0.fullLagStatistic_reroot
#print axioms GMZP0.signed_plus_diagonal_reroot
#print axioms GMZP0.originalFieldExtension_property
#print axioms GMZP0.norm_circleCharacter
#print axioms GMZP0.rerootedOuterPhase_norm
#print axioms GMZP0.rerootedLagG_norm_le
#print axioms GMZP0.lagInnerInterval_card_le
#print axioms GMZP0.rerootedLagB_norm_le
#print axioms GMZP0.rerootedWeightedSum_le_normSum
#print axioms GMZP0.lagSigned_le_rerootedNormSum
#print axioms GMZP0.sum_original_integer_labels
#print axioms GMZP0.sum_rerootLabels
#print axioms GMZP0.finiteRerootedNormAverage_eq
#print axioms GMZP0.uniform_positive_rerooted_average
#print axioms GMZP0.cyclicRow_value
#print axioms GMZP0.cyclicRow_injective
#print axioms GMZP0.cyclicField_original
#print axioms GMZP0.cyclicRow_range_iff
#print axioms GMZP0.cyclicField_outside_range
#print axioms GMZP0.cyclicField_shift
#print axioms GMZP0.cyclic_original_weighted_sum
#print axioms GMZP0.cyclicField_lag
#print axioms GMZP0.cyclicField_reroot_target
#print axioms GMZP0.cyclicLagG_original
#print axioms GMZP0.cyclicLagP_original
#print axioms GMZP0.cyclicLagB_original
#print axioms GMZP0.cyclic_weighted_B_norm_sum
#print axioms GMZP0.horizontalGap_bound
#print axioms GMZP0.horizontalShiftLabels_card
#print axioms GMZP0.horizontal_shift_sum
#print axioms GMZP0.cyclicShiftLagP_gap
#print axioms GMZP0.cyclicShiftLagB_gap
#print axioms GMZP0.cyclicPairNormNumerator_original
#print axioms GMZP0.cyclicPairNormNumerator_shift
#print axioms GMZP0.cyclicModulusAverage_eq
#print axioms GMZP0.finite_to_cyclic_modulus_average
#print axioms GMZP0.cyclic_average_positive_of_finite
#print axioms GMZP0.cyclicField_property
#print axioms GMZP0.cyclicLagG_norm_le
#print axioms GMZP0.cyclicShiftLagB_norm_le
#print axioms GMZP0.uniform_positive_cyclic_average
#print axioms GMZP0.card_cyclicSamplingSpace
#print axioms GMZP0.cyclicWeight_bounds
#print axioms GMZP0.cyclicModulusAverage_as_uniform_mean
#print axioms GMZP0.exists_prime_cyclic_modulus
#print axioms GMZP0.norm_sum_bounded
#print axioms GMZP0.norm_sum_sub_sum_le_sdiff
#print axioms GMZP0.sum_Icc_translate
#print axioms GMZP0.norm_Icc_translate_nonneg
#print axioms GMZP0.norm_Icc_translate
#print axioms GMZP0.lagInnerInterval_eq_Icc
#print axioms GMZP0.norm_lag_sum_translate
#print axioms GMZP0.complexUniformMean_const
#print axioms GMZP0.complexUniformMean_sub
#print axioms GMZP0.norm_complexUniformMean_le
#print axioms GMZP0.norm_complexUniformMean_sub_le
#print axioms GMZP0.complexUniformMean_sum_div
#print axioms GMZP0.weighted_norm_mean_stability
#print axioms GMZP0.card_smoothingShiftLabels
#print axioms GMZP0.card_fourShiftSpace
#print axioms GMZP0.fourShiftSum_abs_le
#print axioms GMZP0.fourShiftSmoothedAverage_eq
#print axioms GMZP0.norm_fourShiftSmoothedAverage_sub_le
#print axioms GMZP0.smoothingRadius_error
#print axioms GMZP0.cyclicLagSequence_norm_le
#print axioms GMZP0.cyclicSmoothedLagB_error
#print axioms GMZP0.cyclic_smoothed_average_positive
#print axioms GMZP0.uniform_positive_smoothed_average
#print axioms GMZP0.cubicFaceCoefficient_independent
#print axioms GMZP0.sum_cubicFaceCoefficient
#print axioms GMZP0.cubicFacePhase_norm
#print axioms GMZP0.cubicFacePhase_independent
#print axioms GMZP0.cubicPhase_four_faces
#print axioms GMZP0.cyclicShiftLagP_four_faces
#print axioms GMZP0.cyclicLagSequence_four_faces
#print axioms GMZP0.cyclicSmoothedLagB_four_faces
#print axioms GMZP0.realUniformMean_nonneg
#print axioms GMZP0.realUniformMean_mono
#print axioms GMZP0.realUniformMean_const
#print axioms GMZP0.realUniformMean_const_mul
#print axioms GMZP0.complexUniformMean_mul_const
#print axioms GMZP0.complexUniformMean_const_mul
#print axioms GMZP0.complexUniformMean_conj
#print axioms GMZP0.complexUniformMean_re
#print axioms GMZP0.complexUniformMean_prod
#print axioms GMZP0.realUniformMean_prod
#print axioms GMZP0.complexUniformMean_comm
#print axioms GMZP0.complexUniformMean_equiv
#print axioms GMZP0.complexUniformMean_cons
#print axioms GMZP0.norm_complexUniformMean_le_mean_norm
#print axioms GMZP0.realUniformMean_sq_le
#print axioms GMZP0.norm_complexUniformMean_sq_le
#print axioms GMZP0.realUniformMean_pow_two_le
#print axioms GMZP0.complexUniformMean_pair_mul_conj
#print axioms GMZP0.complexUniformMean_pair_norm_sq
#print axioms GMZP0.mean_inner_norm_sq_eq_pair
#print axioms GMZP0.box_remove_unit_face
#print axioms GMZP0.box_remove_unit_face_nonneg
#print axioms GMZP0.boxDoubledFaces_norm
#print axioms GMZP0.boxDoubledFaces_independent
#print axioms GMZP0.boxTailIntegrand_pair
#print axioms GMZP0.boxCorrelation_split_head
#print axioms GMZP0.boxCorrelation_sq_le_doubled
#print axioms GMZP0.boxMoment_nonneg
#print axioms GMZP0.faceIndependent_one_const
#print axioms GMZP0.boxCorrelation_one
#print axioms GMZP0.box_cauchy_schwarz
#print axioms GMZP0.boxMoment_le_one
#print axioms GMZP0.iteratedSqrt_nonneg
#print axioms GMZP0.iteratedSqrt_pow
#print axioms GMZP0.boxNorm_nonneg
#print axioms GMZP0.boxNorm_pow
#print axioms GMZP0.boxCorrelation_le_boxNorm
#print axioms GMZP0.boxNorm_le_one
#print axioms GMZP0.shiftCubicFaces_norm
#print axioms GMZP0.shiftCubicFaces_independent
#print axioms GMZP0.cyclicLagBoxNorm_nonneg
#print axioms GMZP0.cyclicLagBoxNorm_le_one
#print axioms GMZP0.cyclicLagBoxNorm_pow
#print axioms GMZP0.cyclicShiftMean_le_boxNorm
#print axioms GMZP0.cyclicSmoothedLagB_le_boxSum
#print axioms GMZP0.fullLagLabels_card
#print axioms GMZP0.lagInnerInterval_subset_full
#print axioms GMZP0.fullLag_sum_eq_card_mean
#print axioms GMZP0.weighted_lag_sum_le_three_mean
#print axioms GMZP0.card_cyclicBoxSamplingSpace
#print axioms GMZP0.cyclicSmoothedModulusAverage_le_three_boxMean
#print axioms GMZP0.cyclicBoxNormAverage_pow_le
#print axioms GMZP0.positive_cyclic_box_average
#print axioms GMZP0.uniform_positive_box_average
#print axioms GMZP0.cubeConj_mul
#print axioms GMZP0.cubeConj_conj
#print axioms GMZP0.cubeConj_ofReal
#print axioms GMZP0.cubeConj_norm
#print axioms GMZP0.cubeSign_eq_parity
#print axioms GMZP0.cubeConj_character
#print axioms GMZP0.card_booleanVertices
#print axioms GMZP0.complexUniformMean_unique
#print axioms GMZP0.complexUniformMean_ofReal
#print axioms GMZP0.prod_boolean_cons
#print axioms GMZP0.cubeVertex_cons
#print axioms GMZP0.cubeProduct_zero
#print axioms GMZP0.cubeProduct_succ
#print axioms GMZP0.cubeMean_succ
#print axioms GMZP0.cubeMean_one
#print axioms GMZP0.cubeMean_eq_boxMoment
#print axioms GMZP0.boxMoment_eq_cubeMean_re
#print axioms GMZP0.cubeMean_nonneg_real
#print axioms GMZP0.circleCharacter_sum
#print axioms GMZP0.alternating_weighted_character_product
#print axioms GMZP0.circle_cubic_translate
#print axioms GMZP0.circle_cubic_sum
#print axioms GMZP0.card_cubeShiftPairs
#print axioms GMZP0.cyclic_cube_expansion
#print axioms GMZP0.cyclicCubeAverage_re
#print axioms GMZP0.cyclicLagG_shift_reroot
#print axioms GMZP0.cyclicCubeProduct_reroot
#print axioms GMZP0.cyclicCubeAverage_reroot
#print axioms GMZP0.cyclicRerootedCubeAverage_eq_moment
#print axioms GMZP0.cyclicRerootedCubeProduct_factorized
#print axioms GMZP0.cyclicCubePhase_polynomial
#print axioms GMZP0.cyclicCubeCoefficients_top
#print axioms GMZP0.cyclicCubeWeight_bounds
#print axioms GMZP0.cyclicCubeAlignment_norm
#print axioms GMZP0.cyclicRerootedCubeProduct_norm
#print axioms GMZP0.uniform_positive_cube_average
#print axioms GMZP0.card_cubeWeylParameters
#print axioms GMZP0.cyclicRerootedCubeAverage_split_time
#print axioms GMZP0.cyclicCubeTimeAverage_norm_le
#print axioms GMZP0.cyclicCubeAverage_le_weightedTimeNorm
#print axioms GMZP0.cyclicCubeWeight_ne_zero_vertices
#print axioms GMZP0.cyclicCube_original_vertices
#print axioms GMZP0.uniform_positive_weighted_time_average
#print axioms GMZP0.circleCharacter_nsmul
#print axioms GMZP0.circle_norm_le_chord
#print axioms GMZP0.linearPhaseMean_geometric
#print axioms GMZP0.linearPhaseMean_chord_bound
#print axioms GMZP0.linear_weyl_inverse
#print axioms GMZP0.sum_fin_labels
#print axioms GMZP0.integerIntervalMean_eq_fin
#print axioms GMZP0.interval_pair_difference_sum
#print axioms GMZP0.weyl_correlation_sum
#print axioms GMZP0.weyl_mean_square_identity
#print axioms GMZP0.weylCorrelation_norm_le
#print axioms GMZP0.weyl_nonzero_correlation_lower
#print axioms GMZP0.sum_le_large_card_add
#print axioms GMZP0.many_large_weyl_correlations
#print axioms GMZP0.largeWeylShifts_mem
#print axioms GMZP0.weyl_small_scale_obstruction
#print axioms GMZP0.sum_Icc_as_fin
#print axioms GMZP0.linear_phase_sum_geometric
#print axioms GMZP0.linear_phase_sum_chord_bound
#print axioms GMZP0.linear_interval_sum_chord_bound
#print axioms GMZP0.linear_interval_weyl_inverse
#print axioms GMZP0.quadraticCirclePolynomial_difference
#print axioms GMZP0.cubicCirclePolynomial_difference
#print axioms GMZP0.weylCorrelation_phase_interval
#print axioms GMZP0.quadratic_weyl_correlation
#print axioms GMZP0.cubic_weyl_correlation
#print axioms GMZP0.quadratic_large_shift_control
#print axioms GMZP0.quadratic_many_returns
#print axioms GMZP0.close_integer_pair
#print axioms GMZP0.affine_return_small_multiple
#print axioms GMZP0.integer_card_le_diameter
#print axioms GMZP0.affine_fiber_spread
#print axioms GMZP0.affine_slope_from_rounded_returns
#print axioms GMZP0.card_returnRoundTargets
#print axioms GMZP0.rounded_affine_target_mem
#print axioms GMZP0.multiplied_affine_return_lift
#print axioms GMZP0.affine_return_amplification
#print axioms GMZP0.dense_returns_seed_card
#print axioms GMZP0.uniform_affine_dense_returns
#print axioms GMZP0.uniform_quadratic_weyl_large
#print axioms GMZP0.uniform_quadratic_weyl
#print axioms GMZP0.interval_length_card
#print axioms GMZP0.interval_mean_rescale
#print axioms GMZP0.interval_large_rescaling
#print axioms GMZP0.quadraticCirclePolynomial_translate
#print axioms GMZP0.uniform_quadratic_interval_weyl
#print axioms GMZP0.weylOverlap_card_le
#print axioms GMZP0.finite_positive_denominator_fiber
#print axioms GMZP0.uniform_cubic_dense_returns
#print axioms GMZP0.uniform_cubic_weyl_large
#print axioms GMZP0.uniform_cubic_weyl
#print axioms GMZP0.uniform_cubic_common_denominator
#print axioms GMZP0.cyclicCubeTimeAverage_as_polynomial
#print axioms GMZP0.uniform_original_cube_weyl
#print axioms GMZP0.weighted_condition_mass
#print axioms GMZP0.uniform_weighted_cube_weyl
#print axioms GMZP0.uniform_original_cube_capture

#check GMZP0.P0
#check GMZP0.WeightedCapture
#check GMZP0.p0_of_weightedCapture
#check GMZP0.FiniteMinorEstimate
#check GMZP0.finite_capture_from_model_operators
#check GMZP0.original_window_first_tt
#check GMZP0.original_window_finite_signed_lower
#check GMZP0.uniform_positive_safe_statistic
#check GMZP0.finiteSignedDoubleStatistic_eq_lag
#check GMZP0.uniform_positive_safe_lag_statistic
#check GMZP0.signed_plus_diagonal_reroot
#check GMZP0.uniform_positive_rerooted_average
#check GMZP0.finite_to_cyclic_modulus_average
#check GMZP0.uniform_positive_cyclic_average
#check GMZP0.cyclicModulusAverage_as_uniform_mean
#check GMZP0.exists_prime_cyclic_modulus
#check GMZP0.norm_Icc_translate
#check GMZP0.norm_fourShiftSmoothedAverage_sub_le
#check GMZP0.uniform_positive_smoothed_average
#check GMZP0.cyclicSmoothedLagB_four_faces
#check GMZP0.box_cauchy_schwarz
#check GMZP0.boxNorm_pow
#check GMZP0.cyclicSmoothedLagB_le_boxSum
#check GMZP0.cyclicBoxNormAverage_pow_le
#check GMZP0.uniform_positive_box_average
#check GMZP0.cubeMean_eq_boxMoment
#check GMZP0.cyclicRerootedCubeAverage_eq_moment
#check GMZP0.cyclicCubePhase_polynomial
#check GMZP0.cyclicRerootedCubeAverage_split_time
#check GMZP0.cyclicCube_original_vertices
#check GMZP0.uniform_positive_weighted_time_average
#check GMZP0.linear_interval_weyl_inverse
#check GMZP0.many_large_weyl_correlations
#check GMZP0.quadratic_many_returns
#check GMZP0.affine_return_small_multiple
#check GMZP0.uniform_affine_dense_returns
#check GMZP0.uniform_quadratic_weyl
#check GMZP0.uniform_quadratic_interval_weyl
#check GMZP0.uniform_cubic_weyl
#check GMZP0.uniform_cubic_common_denominator
#check GMZP0.uniform_original_cube_capture

example (hcapture : GMZP0.WeightedCapture) : GMZP0.P0 :=
  GMZP0.p0_of_weightedCapture hcapture

/-! F15: lag removal, sign reflection, and quantitative collision deletion. -/
#print axioms GMZP0.cyclicCubeVertex_zero_step
#print axioms GMZP0.cube_pair_collision_zero_step
#print axioms GMZP0.cube_pair_collision_zero_step_obstruction
#print axioms GMZP0.realUniformMean_resample
#print axioms GMZP0.uniform_event_le_one_over_card
#print axioms GMZP0.uniform_event_le_of_update_unique
#print axioms GMZP0.card_ascendingCubeLabelPairs
#print axioms GMZP0.cube_collision_probability
#print axioms GMZP0.positive_cube_collision_probability
#print axioms GMZP0.realUniformMean_equiv
#print axioms GMZP0.card_cubeSpatialParameters
#print axioms GMZP0.cyclicCubeNearMass_remove_lag
#print axioms GMZP0.cyclicCubeNearWeight_bounds
#print axioms GMZP0.cubeShiftSum_neg
#print axioms GMZP0.cyclicCubeVertex_neg_reflect
#print axioms GMZP0.cyclicCubeCubicCoeff_neg_reflect
#print axioms GMZP0.cyclicCubeWeight_neg_reflect
#print axioms GMZP0.cyclicCubeNearWeight_neg_reflect
#print axioms GMZP0.cubeNearWeight_mean_neg
#print axioms GMZP0.realUniformMean_sum
#print axioms GMZP0.uniform_event_union_le
#print axioms GMZP0.cubeShiftSum_flat
#print axioms GMZP0.flatCubeShiftSum_update_sub
#print axioms GMZP0.flatCubeShiftSum_update_other
#print axioms GMZP0.cube_collision_update_unique
#print axioms GMZP0.cube_pair_collision_probability
#print axioms GMZP0.realUniformMean_prod_four
#print axioms GMZP0.card_positiveCubeParameters
#print axioms GMZP0.cyclicSpatialCubeNearMass_positive
#print axioms GMZP0.cyclicCubeNearMass_positive
#print axioms GMZP0.smoothingShift_cast_injective
#print axioms GMZP0.positive_cube_step_ne_zero
#print axioms GMZP0.signedHorizontalLabel_injective
#print axioms GMZP0.signedHorizontalLabel_surjective
#print axioms GMZP0.real_signed_mean_eq_positive
#print axioms GMZP0.uniform_collision_scale
#print axioms GMZP0.cyclicDistinctCubeNearWeight_pos_iff
#print axioms GMZP0.uniform_distinct_original_cube_capture
#print axioms GMZP0.uniform_positive_original_cube_capture
#print axioms GMZP0.realUniformMean_add
#print axioms GMZP0.weighted_event_removal
#print axioms GMZP0.positive_cube_total_collision_probability
#print axioms GMZP0.cyclicDistinctPositiveCubeNearMass_lower
#check GMZP0.uniform_distinct_original_cube_capture

/-! F16: one simultaneous real lift, with original weights and responses. -/
#print axioms GMZP0.cube_choice_sum_eq
#print axioms GMZP0.exists_cube_integer_correction
#print axioms GMZP0.exists_cube_lift_zero
#print axioms GMZP0.frequency_coe_sum
#print axioms GMZP0.cubeRoundedSum_abs_le
#print axioms GMZP0.cubeRoundedSum_real_error
#print axioms GMZP0.cubeUnitRep_sum_coe
#print axioms GMZP0.cubeRoundedSum_circle_norm
#print axioms GMZP0.cube_rounding_branch
#print axioms GMZP0.cubeSign_one_or_neg_one
#print axioms GMZP0.cubeSign_abs
#print axioms GMZP0.card_positiveCubeVertices
#print axioms GMZP0.card_negativeCubeVertices
#print axioms GMZP0.bounded_integer_cube_sum
#print axioms GMZP0.exists_cyclic_lift_choice
#print axioms GMZP0.exists_cyclic_real_lift
#print axioms GMZP0.cyclicCube_scaled_frequency_sum
#print axioms GMZP0.cyclicCubeWeight_pos_vertices
#print axioms GMZP0.cyclic_lift_cube_probability
#print axioms GMZP0.cyclicDistinctCubeNearWeight_eq_ite_pos
#print axioms GMZP0.cyclicLiftValue_grid
#print axioms GMZP0.cyclicLiftValue_abs_le
#print axioms GMZP0.cyclicLiftValue_zero
#print axioms GMZP0.cyclicLiftValue_circle_error
#print axioms GMZP0.cyclicLiftValue_original_error
#print axioms GMZP0.separate_witnesses_not_one_global_witness
#print axioms GMZP0.exists_ge_realUniformMean
#print axioms GMZP0.mean_constant_event_weight
#print axioms GMZP0.exists_global_weighted_success
#print axioms GMZP0.realUniformMean_restrict
#print axioms GMZP0.uniform_singleton_probability
#print axioms GMZP0.uniform_restricted_assignment_probability
#print axioms GMZP0.uniform_restricted_event_lower
#print axioms GMZP0.realUniformMean_comm
#print axioms GMZP0.card_liftChoice
#print axioms GMZP0.liftChoice_bounds
#print axioms GMZP0.liftChoiceValue_grid
#print axioms GMZP0.liftChoiceValue_abs_le
#print axioms GMZP0.liftChoiceValue_circle_error
#print axioms GMZP0.liftGridSize_bounds
#print axioms GMZP0.uniform_lift_grid_scale
#print axioms GMZP0.frequencyUnitRep_bounds
#print axioms GMZP0.frequencyUnitRep_coe
#print axioms GMZP0.round_monotone_real
#print axioms GMZP0.round_between_integers
#print axioms GMZP0.liftRound_bounds
#print axioms GMZP0.liftRound_error
#print axioms GMZP0.liftRound_div_error
#print axioms GMZP0.uniform_original_real_lift
#check GMZP0.uniform_original_real_lift

-- F17: exact mesh, actual local fourth norm and original-data good fibres.
#print axioms GMZP0.circleCharacter_eq_one_iff
#print axioms GMZP0.completeCharacterMean_torsion
#print axioms GMZP0.short_rational_frequency_zero_iff
#print axioms GMZP0.rational_character_orthogonality
#print axioms GMZP0.realSignedCubeSum_grid
#print axioms GMZP0.realSignedCubeSum_abs_le
#print axioms GMZP0.realSignedCubeSum_abs_le_384
#print axioms GMZP0.realSignedCubeSum_grid_bound
#print axioms GMZP0.meshFrequency_mul_grid
#print axioms GMZP0.frequencyMeshMean_grid_integer
#print axioms GMZP0.frequencyMeshMean_real_zero
#print axioms GMZP0.frequencyMeshMean_realCube
#print axioms GMZP0.integer_frequency_alias_obstruction
#print axioms GMZP0.frequencyMeshMean_period
#print axioms GMZP0.frequency_mesh_size_obstruction
#print axioms GMZP0.localCubeMoment_nonneg
#print axioms GMZP0.localCubeMoment_le_one
#print axioms GMZP0.localCubeNorm_nonneg
#print axioms GMZP0.localCubeNorm_pow
#print axioms GMZP0.localCubeNorm_le_one
#print axioms GMZP0.localCubeMoment_complex
#print axioms GMZP0.weighted_real_cube_character
#print axioms GMZP0.weighted_frequency_cube_exact
#print axioms GMZP0.weighted_frequency_cube_real
#print axioms GMZP0.localBoxFunction_cyclic_vertex
#print axioms GMZP0.cyclicLocalMoment_expand
#print axioms GMZP0.modulatedCyclicField_norm
#print axioms GMZP0.modulatedCyclicField_norm_le
#print axioms GMZP0.cyclic_weighted_frequency_cube
#print axioms GMZP0.cyclic_local_frequency_row
#print axioms GMZP0.cyclicLocalFourMoment_eq_mass
#print axioms GMZP0.cyclicLocalFourthNormAverage_eq_moment
#print axioms GMZP0.cyclicLocalFourthNormAverage_eq_mass
#print axioms GMZP0.uniform_original_local_four
#print axioms GMZP0.bounded_moment_good_fibres
#print axioms GMZP0.cyclicLocalFourFiber_bounds
#print axioms GMZP0.cyclic_local_good_fibres
#print axioms GMZP0.uniform_original_local_fibres
#check GMZP0.uniform_original_local_four
#check GMZP0.uniform_original_local_fibres

-- F18: normalized Fourier, actual difference density, and the explicit twisted-cube interface.
#print axioms GMZP0.complexUniformMean_sum
#print axioms GMZP0.finite_character_pair_sum
#print axioms GMZP0.finiteFourier_inversion
#print axioms GMZP0.finiteFourier_inner
#print axioms GMZP0.finiteFourier_parseval
#print axioms GMZP0.finite_character_mul_conj
#print axioms GMZP0.correlation_character_factor
#print axioms GMZP0.finiteFourier_correlation
#print axioms GMZP0.realDifferenceDensity_nonneg
#print axioms GMZP0.finiteCorrelation_ofReal
#print axioms GMZP0.fourierEnergyWeight_nonneg
#print axioms GMZP0.fourierEnergyWeight_sum
#print axioms GMZP0.realDifferenceDensity_fourier
#print axioms GMZP0.positive_product_sum
#print axioms GMZP0.positive_product_mixture_bound
#print axioms GMZP0.differenceDensity_product_fourier
#print axioms GMZP0.differenceWeightedCubeMean_fourier
#print axioms GMZP0.differenceWeightedCubeMean_bound
#print axioms GMZP0.parameterDensity_nonneg
#print axioms GMZP0.parameterDensity_card
#print axioms GMZP0.parameterDensity_pushforward
#print axioms GMZP0.parameterDensity_mean_one
#print axioms GMZP0.parameterDensity_le_multiplicity
#print axioms GMZP0.parameterDensity_energy_le
#print axioms GMZP0.realDifferenceDensity_weighted
#print axioms GMZP0.parameterDifference_pushforward
#print axioms GMZP0.box_remove_bounded_face
#print axioms GMZP0.boxDoubledFaces_norm_le
#print axioms GMZP0.boxCorrelation_sq_le_doubled_bounded
#print axioms GMZP0.boxCorrelation_one_bounded
#print axioms GMZP0.box_cauchy_schwarz_bounded
#print axioms GMZP0.boxCorrelation_le_boxNorm_bounded
#print axioms GMZP0.uniform_product_pushforward
#print axioms GMZP0.localBoxFunction_additive_vertex
#print axioms GMZP0.local_cube_mean_reroot
#print axioms GMZP0.parameterDifference_product_pushforward
#print axioms GMZP0.localCubeMoment_difference
#print axioms GMZP0.localCubeMoment_eq_differenceWeighted
#print axioms GMZP0.localCubeMoment_fourier
#print axioms GMZP0.localCubeMoment_bound_of_twisted
#print axioms GMZP0.parameterDensity_identity
#print axioms GMZP0.localCubeMoment_const_one
#print axioms GMZP0.raw_probability_density_obstruction
#print axioms GMZP0.globalCubeMoment_additive
#check GMZP0.localCubeMoment_fourier
#check GMZP0.localCubeMoment_bound_of_twisted

#print axioms GMZP0.finite_self_correlation_le

#print axioms GMZP0.additiveCubeVertex_cons
#print axioms GMZP0.additiveCubeProduct_zero
#print axioms GMZP0.additiveCubeProduct_succ
#print axioms GMZP0.additiveCubeProduct_one
#print axioms GMZP0.crossCorrelation_character_factor
#print axioms GMZP0.finiteFourier_crossCorrelation
#print axioms GMZP0.finiteFourier_modulation
#print axioms GMZP0.derivativeFourier_crossCorrelation
#print axioms GMZP0.derivativeFourier_energy
#print axioms GMZP0.derivativeFourier_energy_le
#print axioms GMZP0.globalTwistedCubeMean_succ
#print axioms GMZP0.globalTwistedCubeMean_zero_twist
#print axioms GMZP0.globalTwistedCubeMean_one
#print axioms GMZP0.globalCubeMoment_nonneg
#print axioms GMZP0.globalCubeMoment_succ
#print axioms GMZP0.globalCubeMoment_one
#print axioms GMZP0.globalCubeMoment_two_fourier
#print axioms GMZP0.globalTwistedCubeMean_two_le
#print axioms GMZP0.globalTwistedCubeMean_le
#print axioms GMZP0.localCubeMoment_le_global
#print axioms GMZP0.globalCubeNorm_nonneg
#print axioms GMZP0.globalCubeNorm_pow
#print axioms GMZP0.localCubeNorm_le_global
#print axioms GMZP0.globalCubeMoment_lower_from_local
#print axioms GMZP0.character_first_cube_obstruction
#print axioms GMZP0.dimension_one_twist_obstruction
#check GMZP0.localCubeMoment_le_global
#check GMZP0.localCubeNorm_le_global
#check GMZP0.globalTwistedCubeMean_le

#print axioms GMZP0.globalCubeMoment_real_expansion
#print axioms GMZP0.global_frequency_moment_exact
#print axioms GMZP0.cyclicGlobalSeventhMoment_eq_mass
#check GMZP0.cyclicGlobalSeventhMoment_eq_mass

#print axioms GMZP0.exists_good_large_value
#print axioms GMZP0.cyclicPairLocalSeven_le_one
#print axioms GMZP0.original_scale_parameter_bound
#print axioms GMZP0.shrunk_radius_short
#print axioms GMZP0.nat_floor_ge_half
#print axioms GMZP0.shrunk_radius_lower
#print axioms GMZP0.pair_shift_integer_bound
#print axioms GMZP0.bounded_pair_values_no_wrap
#print axioms GMZP0.uniform_shrunk_radius_threshold
#print axioms GMZP0.cyclicLocalFourthNormAverage_le_one
#print axioms GMZP0.original_scale_bound_of_local_four
#check GMZP0.original_scale_bound_of_local_four
