import GMZP0

/-! Print transitive axioms of every exported project theorem. -/

#print axioms GMZP0.cubic_lag_difference
#print axioms GMZP0.lag_target_coordinate
#print axioms GMZP0.double_phase_reroot
#print axioms GMZP0.fourth_difference_cubic
#print axioms GMZP0.linear_collision_eight
#print axioms GMZP0.norm_cubicPhase
#print axioms GMZP0.card_base
#print axioms GMZP0.cubicPhase_coe_real
#print axioms GMZP0.cubicDistanceSq_nonneg
#print axioms GMZP0.cubicDistance_nonneg
#print axioms GMZP0.cubicDistance_sq
#print axioms GMZP0.norm_response_le_one
#print axioms GMZP0.mean_le_root_mean_square
#print axioms GMZP0.norm_response_sub_le
#print axioms GMZP0.aligned_response_transfer
#print axioms GMZP0.norm_response_transfer
#print axioms GMZP0.exists_ge_mean
#print axioms GMZP0.finite_response_selection
#print axioms GMZP0.original_response_of_finite_capture
#print axioms GMZP0.weighted_response_le_mean
#print axioms GMZP0.captured_response_lower_bound
#print axioms GMZP0.small_scale_selection
#print axioms GMZP0.exists_response_alignment
#print axioms GMZP0.thresholdWeight_bounds
#print axioms GMZP0.thresholdWeight_support
#print axioms GMZP0.thresholdWeight_mass
#print axioms GMZP0.original_admissible_data
#print axioms GMZP0.p0_of_weightedCapture
#print axioms GMZP0.root_sum_square_add_le
#print axioms GMZP0.cubicDistance_self
#print axioms GMZP0.cubicDistance_symm
#print axioms GMZP0.cubicDistance_triangle
#print axioms GMZP0.cubicDistance_le_of_label_bound
#print axioms GMZP0.exists_nearest_frequency_lift
#print axioms GMZP0.cubicPhase_add
#print axioms GMZP0.cubicPhase_zero
#print axioms GMZP0.norm_cubicPhase_sub
#print axioms GMZP0.real_cubicPhase_chord_le
#print axioms GMZP0.cubicPhase_chord_le
#print axioms GMZP0.cubicDistance_le_circle_scale
#print axioms GMZP0.cubicDistance_le_of_scaled_circle_error
#print axioms GMZP0.integer_cast_frequency
#print axioms GMZP0.zero_branch_division_counterexample
#print axioms GMZP0.circle_root_decomposition
#print axioms GMZP0.circle_root_with_real_error
#print axioms GMZP0.circle_approx_root_decomposition
#print axioms GMZP0.circle_approx_root_fullLabel
#print axioms GMZP0.real_grid_rounding
#print axioms GMZP0.cubic_scale_grid_rounding
#print axioms GMZP0.grid_index_mem
#print axioms GMZP0.gridIndices_nonempty
#print axioms GMZP0.majorArc_grid_approximation
#print axioms GMZP0.majorArc_universal_list
#print axioms GMZP0.weighted_mass_le_energy
#print axioms GMZP0.retained_mass_from_energy
#print axioms GMZP0.assigned_weighted_energy
#print axioms GMZP0.assigned_minor_energy
#print axioms GMZP0.major_mass_of_minor_energy
#print axioms GMZP0.endpoint_eq_inputPoint
#print axioms GMZP0.card_inputBox
#print axioms GMZP0.inputEnergy_le
#print axioms GMZP0.finiteResponse_original
#print axioms GMZP0.profileMinorEnergy_of_finite_estimate
#print axioms GMZP0.finite_estimates_assigned_energy
#print axioms GMZP0.freezing_energy_budget
#print axioms GMZP0.finite_capture_from_model_energy
#print axioms GMZP0.finite_capture_from_model_operators
#print axioms GMZP0.inputPoint_injective
#print axioms GMZP0.endpointIndex_label_injective
#print axioms GMZP0.endpointIndex_base_injective
#print axioms GMZP0.endpointIndex_same_horizontal
#print axioms GMZP0.integer_parabola_collision
#print axioms GMZP0.collision_lag_displacement
#print axioms GMZP0.kernel_adjoint_identity
#print axioms GMZP0.kernel_comp_adjoint
#print axioms GMZP0.gramKernel_conjugate
#print axioms GMZP0.responseKernel_action
#print axioms GMZP0.finiteResponse_adjoint_identity
#print axioms GMZP0.responseKernel_gram
#print axioms GMZP0.responseKernel_gram_same_horizontal
#print axioms GMZP0.responseKernel_horizontal_block
#print axioms GMZP0.finiteEnergy_nonneg
#print axioms GMZP0.finitePairing_self
#print axioms GMZP0.finitePairing_norm_sq_le
#print axioms GMZP0.weighted_original_pairing
#print axioms GMZP0.weighted_original_adjoint_sq_le
#print axioms GMZP0.weighted_original_adjoint_lower
#print axioms GMZP0.alignedWeightVector_energy_le
#print axioms GMZP0.finiteAdjoint_energy_gram
#print axioms GMZP0.weighted_original_response_lower
#print axioms GMZP0.gram_same_horizontal_energy
#print axioms GMZP0.finiteAdjoint_energy_split
#print axioms GMZP0.weighted_offHorizontal_lower
#print axioms GMZP0.originalScaledWeight_bounds
#print axioms GMZP0.originalScaledWeight_mass
#print axioms GMZP0.originalScaledWeight_support
#print axioms GMZP0.originalScaledWeight_response
#print axioms GMZP0.original_window_response_lower
#print axioms GMZP0.offHorizontalEnergy_blocks
#print axioms GMZP0.offBlockNormSum_nonneg
#print axioms GMZP0.offHorizontalEnergy_le_blocks
#print axioms GMZP0.weighted_first_tt_lower
#print axioms GMZP0.original_window_first_tt
#print axioms GMZP0.horizontalPairing_adjoint_bound
#print axioms GMZP0.horizontalPairing_zero_left
#print axioms GMZP0.horizontalPairing_zero_right
#print axioms GMZP0.offBlockNormSum_restrict
#print axioms GMZP0.secondAdjointEnergy_nonneg
#print axioms GMZP0.offBlockNormSum_sq_le
#print axioms GMZP0.offBlockNormSum_second_adjoint
#print axioms GMZP0.original_window_second_adjoint
#print axioms GMZP0.endpointIndex_collision_iff
#print axioms GMZP0.nonparallel_collision_unique
#print axioms GMZP0.collision_target_unique
#print axioms GMZP0.horizontalKernel_of_collision
#print axioms GMZP0.horizontalKernel_no_collision
#print axioms GMZP0.horizontalKernel_norm
#print axioms GMZP0.horizontal_collision_count
#print axioms GMZP0.horizontalKernel_row_energy_le
#print axioms GMZP0.kernelAdjoint_energy_gram
#print axioms GMZP0.gram_diagonal_interaction
#print axioms GMZP0.gram_interaction_original_weights
#print axioms GMZP0.zero_pairing_nonzero_adjoint
#print axioms GMZP0.kernelAdjoint_energy_split
#print axioms GMZP0.finite_signed_original_weights
#print axioms GMZP0.secondDiagonalEnergy_nonneg
#print axioms GMZP0.secondAdjointEnergy_split
#print axioms GMZP0.secondDiagonalEnergy_le
#print axioms GMZP0.original_window_second_diagonal
#print axioms GMZP0.original_window_finite_signed_lower
#print axioms GMZP0.parabola_shift_abs_le
#print axioms GMZP0.safe_vertical_shift
#print axioms GMZP0.safe_parabola_target
#print axioms GMZP0.safe_lag_target
#print axioms GMZP0.exists_original_vertical_point
#print axioms GMZP0.safe_original_target_exists
#print axioms GMZP0.horizontal_interval_gap
#print axioms GMZP0.vertical_lag_zero_iff
#print axioms GMZP0.fin_initial_strip_card_le
#print axioms GMZP0.fin_final_strip_card_le
#print axioms GMZP0.fin_boundary_strips_card_le
#print axioms GMZP0.mem_safeRows_iff
#print axioms GMZP0.boundaryBaseSet_card_le
#print axioms GMZP0.boundary_original_mass_le
#print axioms GMZP0.safe_boundary_mass_partition
#print axioms GMZP0.safe_original_mass_lower
#print axioms GMZP0.horizontal_partition_cover
#print axioms GMZP0.horizontalChunk_interval
#print axioms GMZP0.mem_horizontalChunk_iff
#print axioms GMZP0.horizontalChunk_gap
#print axioms GMZP0.chunkWindow_geometry
#print axioms GMZP0.chunkWindow_mass_partition
#print axioms GMZP0.exists_mean_chunk
#print axioms GMZP0.exists_heavy_chunk
#print axioms GMZP0.windowModulus_pos
#print axioms GMZP0.safeWindowMass_pos
#print axioms GMZP0.window_boundary_budget
#print axioms GMZP0.exists_original_safe_chunk
#print axioms GMZP0.uniform_safe_window
#print axioms GMZP0.safe_chunk_target_exists
#print axioms GMZP0.original_weight_mass_le_one
#print axioms GMZP0.positive_from_signed_bound
#print axioms GMZP0.finiteStatisticThreshold_pos
#print axioms GMZP0.uniform_positive_from_signed_bound
#print axioms GMZP0.uniform_positive_safe_statistic
#print axioms GMZP0.circleCharacter_add
#print axioms GMZP0.circleCharacter_neg
#print axioms GMZP0.circleCharacter_sub
#print axioms GMZP0.circleCharacter_real
#print axioms GMZP0.cubicPhase_integer
#print axioms GMZP0.double_phase_character
#print axioms GMZP0.doublePhaseCoefficient_reroot
#print axioms GMZP0.integer_label_bounds
#print axioms GMZP0.horizontalGap_ne_zero
#print axioms GMZP0.mem_blockLabels_iff
#print axioms GMZP0.mem_lagLabels_iff
#print axioms GMZP0.lag_labels_bound
#print axioms GMZP0.lag_domain_reroot
#print axioms GMZP0.double_collision_coordinates
#print axioms GMZP0.double_collision_labels
#print axioms GMZP0.double_collision_zero_lag_iff
#print axioms GMZP0.double_kernel_original_phase
#print axioms GMZP0.double_kernel_original_weighted_phase
#print axioms GMZP0.oneBasedIndex_label
#print axioms GMZP0.shiftedBlockLabel_value
#print axioms GMZP0.blockTarget_coordinate
#print axioms GMZP0.blockTarget_injective
#print axioms GMZP0.blockTarget_collision
#print axioms GMZP0.collision_in_blockTargets
#print axioms GMZP0.blockFinLabels_membership
#print axioms GMZP0.horizontalKernel_label_formula
#print axioms GMZP0.horizontalBlock_action_labels
#print axioms GMZP0.blockCoefficient_character
#print axioms GMZP0.oneBasedIndex_of_label
#print axioms GMZP0.blockLabelEquiv_symm_value
#print axioms GMZP0.horizontalBlock_action_integer_labels
#print axioms GMZP0.label_difference_bound
#print axioms GMZP0.lagSource_coordinate
#print axioms GMZP0.lagSource_injective
#print axioms GMZP0.lagSource_self
#print axioms GMZP0.lagSource_eq_self_iff
#print axioms GMZP0.lagSource_collision
#print axioms GMZP0.collision_in_lagSources
#print axioms GMZP0.horizontalKernel_lag_weighted_sum
#print axioms GMZP0.horizontalGram_action_labels
#print axioms GMZP0.horizontalGram_offDiagonal_labels
#print axioms GMZP0.horizontalGram_offDiagonal_original_phase
#print axioms GMZP0.lagLabels_empty_of_large_lag
#print axioms GMZP0.mem_lagPairDomain_iff
#print axioms GMZP0.integer_label_pair_sum
#print axioms GMZP0.sum_blockFinLabels
#print axioms GMZP0.label_difference_ne_zero_iff
#print axioms GMZP0.distinct_label_pair_sum
#print axioms GMZP0.originalFieldExtension_vertical_outside
#print axioms GMZP0.originalFieldExtension_base
#print axioms GMZP0.originalFieldExtension_lagSource
#print axioms GMZP0.originalFieldExtension_blockTarget
#print axioms GMZP0.originalLagSummand_labels
#print axioms GMZP0.horizontalGram_offDiagonal_lag
#print axioms GMZP0.secondOffDiagonalEnergy_lag
#print axioms GMZP0.finiteSignedDoubleStatistic_eq_lag
#print axioms GMZP0.original_window_statistic_eq_lag
#print axioms GMZP0.uniform_positive_safe_lag_statistic
#print axioms GMZP0.mem_rerootLabels_iff
#print axioms GMZP0.reroot_lag_bound
#print axioms GMZP0.mem_rerootPairDomain_iff
#print axioms GMZP0.lag_sum_reroot
#print axioms GMZP0.originalLagSummand_zero_lag
#print axioms GMZP0.originalLagSummand_zero_nonneg
#print axioms GMZP0.lag_sum_split_zero
#print axioms GMZP0.fullLagNumerator_split
#print axioms GMZP0.fullLagStatistic_split
#print axioms GMZP0.lagDiagonalStatistic_nonneg
#print axioms GMZP0.lagSigned_le_full
#print axioms GMZP0.lagLabels_zero
#print axioms GMZP0.blockLabels_card_le
#print axioms GMZP0.zero_lag_row_le
#print axioms GMZP0.zeroLagNumerator_le
#print axioms GMZP0.lagDiagonalStatistic_le
#print axioms GMZP0.original_window_lag_diagonal_le
#print axioms GMZP0.originalLagSummand_reroot
#print axioms GMZP0.rerooted_inner_average
#print axioms GMZP0.fullLagNumerator_reroot
#print axioms GMZP0.fullLagStatistic_reroot
#print axioms GMZP0.signed_plus_diagonal_reroot
#print axioms GMZP0.originalFieldExtension_property
#print axioms GMZP0.norm_circleCharacter
#print axioms GMZP0.rerootedOuterPhase_norm
#print axioms GMZP0.rerootedLagG_norm_le
#print axioms GMZP0.lagInnerInterval_card_le
#print axioms GMZP0.rerootedLagB_norm_le
#print axioms GMZP0.rerootedWeightedSum_le_normSum
#print axioms GMZP0.lagSigned_le_rerootedNormSum
#print axioms GMZP0.sum_original_integer_labels
#print axioms GMZP0.sum_rerootLabels
#print axioms GMZP0.finiteRerootedNormAverage_eq
#print axioms GMZP0.uniform_positive_rerooted_average
#print axioms GMZP0.cyclicRow_value
#print axioms GMZP0.cyclicRow_injective
#print axioms GMZP0.cyclicField_original
#print axioms GMZP0.cyclicRow_range_iff
#print axioms GMZP0.cyclicField_outside_range
#print axioms GMZP0.cyclicField_shift
#print axioms GMZP0.cyclic_original_weighted_sum
#print axioms GMZP0.cyclicField_lag
#print axioms GMZP0.cyclicField_reroot_target
#print axioms GMZP0.cyclicLagG_original
#print axioms GMZP0.cyclicLagP_original
#print axioms GMZP0.cyclicLagB_original
#print axioms GMZP0.cyclic_weighted_B_norm_sum
#print axioms GMZP0.horizontalGap_bound
#print axioms GMZP0.horizontalShiftLabels_card
#print axioms GMZP0.horizontal_shift_sum
#print axioms GMZP0.cyclicShiftLagP_gap
#print axioms GMZP0.cyclicShiftLagB_gap
#print axioms GMZP0.cyclicPairNormNumerator_original
#print axioms GMZP0.cyclicPairNormNumerator_shift
#print axioms GMZP0.cyclicModulusAverage_eq
#print axioms GMZP0.finite_to_cyclic_modulus_average
#print axioms GMZP0.cyclic_average_positive_of_finite
#print axioms GMZP0.cyclicField_property
#print axioms GMZP0.cyclicLagG_norm_le
#print axioms GMZP0.cyclicShiftLagB_norm_le
#print axioms GMZP0.uniform_positive_cyclic_average
#print axioms GMZP0.card_cyclicSamplingSpace
#print axioms GMZP0.cyclicWeight_bounds
#print axioms GMZP0.cyclicModulusAverage_as_uniform_mean
#print axioms GMZP0.exists_prime_cyclic_modulus
#print axioms GMZP0.norm_sum_bounded
#print axioms GMZP0.norm_sum_sub_sum_le_sdiff
#print axioms GMZP0.sum_Icc_translate
#print axioms GMZP0.norm_Icc_translate_nonneg
#print axioms GMZP0.norm_Icc_translate
#print axioms GMZP0.lagInnerInterval_eq_Icc
#print axioms GMZP0.norm_lag_sum_translate
#print axioms GMZP0.complexUniformMean_const
#print axioms GMZP0.complexUniformMean_sub
#print axioms GMZP0.norm_complexUniformMean_le
#print axioms GMZP0.norm_complexUniformMean_sub_le
#print axioms GMZP0.complexUniformMean_sum_div
#print axioms GMZP0.weighted_norm_mean_stability
#print axioms GMZP0.card_smoothingShiftLabels
#print axioms GMZP0.card_fourShiftSpace
#print axioms GMZP0.fourShiftSum_abs_le
#print axioms GMZP0.fourShiftSmoothedAverage_eq
#print axioms GMZP0.norm_fourShiftSmoothedAverage_sub_le
#print axioms GMZP0.smoothingRadius_error
#print axioms GMZP0.cyclicLagSequence_norm_le
#print axioms GMZP0.cyclicSmoothedLagB_error
#print axioms GMZP0.cyclic_smoothed_average_positive
#print axioms GMZP0.uniform_positive_smoothed_average
#print axioms GMZP0.cubicFaceCoefficient_independent
#print axioms GMZP0.sum_cubicFaceCoefficient
#print axioms GMZP0.cubicFacePhase_norm
#print axioms GMZP0.cubicFacePhase_independent
#print axioms GMZP0.cubicPhase_four_faces
#print axioms GMZP0.cyclicShiftLagP_four_faces
#print axioms GMZP0.cyclicLagSequence_four_faces
#print axioms GMZP0.cyclicSmoothedLagB_four_faces
#print axioms GMZP0.realUniformMean_nonneg
#print axioms GMZP0.realUniformMean_mono
#print axioms GMZP0.realUniformMean_const
#print axioms GMZP0.realUniformMean_const_mul
#print axioms GMZP0.complexUniformMean_mul_const
#print axioms GMZP0.complexUniformMean_const_mul
#print axioms GMZP0.complexUniformMean_conj
#print axioms GMZP0.complexUniformMean_re
#print axioms GMZP0.complexUniformMean_prod
#print axioms GMZP0.realUniformMean_prod
#print axioms GMZP0.complexUniformMean_comm
#print axioms GMZP0.complexUniformMean_equiv
#print axioms GMZP0.complexUniformMean_cons
#print axioms GMZP0.norm_complexUniformMean_le_mean_norm
#print axioms GMZP0.realUniformMean_sq_le
#print axioms GMZP0.norm_complexUniformMean_sq_le
#print axioms GMZP0.realUniformMean_pow_two_le
#print axioms GMZP0.complexUniformMean_pair_mul_conj
#print axioms GMZP0.complexUniformMean_pair_norm_sq
#print axioms GMZP0.mean_inner_norm_sq_eq_pair
#print axioms GMZP0.box_remove_unit_face
#print axioms GMZP0.box_remove_unit_face_nonneg
#print axioms GMZP0.boxDoubledFaces_norm
#print axioms GMZP0.boxDoubledFaces_independent
#print axioms GMZP0.boxTailIntegrand_pair
#print axioms GMZP0.boxCorrelation_split_head
#print axioms GMZP0.boxCorrelation_sq_le_doubled
#print axioms GMZP0.boxMoment_nonneg
#print axioms GMZP0.faceIndependent_one_const
#print axioms GMZP0.boxCorrelation_one
#print axioms GMZP0.box_cauchy_schwarz
#print axioms GMZP0.boxMoment_le_one
#print axioms GMZP0.iteratedSqrt_nonneg
#print axioms GMZP0.iteratedSqrt_pow
#print axioms GMZP0.boxNorm_nonneg
#print axioms GMZP0.boxNorm_pow
#print axioms GMZP0.boxCorrelation_le_boxNorm
#print axioms GMZP0.boxNorm_le_one
#print axioms GMZP0.shiftCubicFaces_norm
#print axioms GMZP0.shiftCubicFaces_independent
#print axioms GMZP0.cyclicLagBoxNorm_nonneg
#print axioms GMZP0.cyclicLagBoxNorm_le_one
#print axioms GMZP0.cyclicLagBoxNorm_pow
#print axioms GMZP0.cyclicShiftMean_le_boxNorm
#print axioms GMZP0.cyclicSmoothedLagB_le_boxSum
#print axioms GMZP0.fullLagLabels_card
#print axioms GMZP0.lagInnerInterval_subset_full
#print axioms GMZP0.fullLag_sum_eq_card_mean
#print axioms GMZP0.weighted_lag_sum_le_three_mean
#print axioms GMZP0.card_cyclicBoxSamplingSpace
#print axioms GMZP0.cyclicSmoothedModulusAverage_le_three_boxMean
#print axioms GMZP0.cyclicBoxNormAverage_pow_le
#print axioms GMZP0.positive_cyclic_box_average
#print axioms GMZP0.uniform_positive_box_average
#print axioms GMZP0.cubeConj_mul
#print axioms GMZP0.cubeConj_conj
#print axioms GMZP0.cubeConj_ofReal
#print axioms GMZP0.cubeConj_norm
#print axioms GMZP0.cubeSign_eq_parity
#print axioms GMZP0.cubeConj_character
#print axioms GMZP0.card_booleanVertices
#print axioms GMZP0.complexUniformMean_unique
#print axioms GMZP0.complexUniformMean_ofReal
#print axioms GMZP0.prod_boolean_cons
#print axioms GMZP0.cubeVertex_cons
#print axioms GMZP0.cubeProduct_zero
#print axioms GMZP0.cubeProduct_succ
#print axioms GMZP0.cubeMean_succ
#print axioms GMZP0.cubeMean_one
#print axioms GMZP0.cubeMean_eq_boxMoment
#print axioms GMZP0.boxMoment_eq_cubeMean_re
#print axioms GMZP0.cubeMean_nonneg_real
#print axioms GMZP0.circleCharacter_sum
#print axioms GMZP0.alternating_weighted_character_product
#print axioms GMZP0.circle_cubic_translate
#print axioms GMZP0.circle_cubic_sum
#print axioms GMZP0.card_cubeShiftPairs
#print axioms GMZP0.cyclic_cube_expansion
#print axioms GMZP0.cyclicCubeAverage_re
#print axioms GMZP0.cyclicLagG_shift_reroot
#print axioms GMZP0.cyclicCubeProduct_reroot
#print axioms GMZP0.cyclicCubeAverage_reroot
#print axioms GMZP0.cyclicRerootedCubeAverage_eq_moment
#print axioms GMZP0.cyclicRerootedCubeProduct_factorized
#print axioms GMZP0.cyclicCubePhase_polynomial
#print axioms GMZP0.cyclicCubeCoefficients_top
#print axioms GMZP0.cyclicCubeWeight_bounds
#print axioms GMZP0.cyclicCubeAlignment_norm
#print axioms GMZP0.cyclicRerootedCubeProduct_norm
#print axioms GMZP0.uniform_positive_cube_average
#print axioms GMZP0.card_cubeWeylParameters
#print axioms GMZP0.cyclicRerootedCubeAverage_split_time
#print axioms GMZP0.cyclicCubeTimeAverage_norm_le
#print axioms GMZP0.cyclicCubeAverage_le_weightedTimeNorm
#print axioms GMZP0.cyclicCubeWeight_ne_zero_vertices
#print axioms GMZP0.cyclicCube_original_vertices
#print axioms GMZP0.uniform_positive_weighted_time_average
#print axioms GMZP0.circleCharacter_nsmul
#print axioms GMZP0.circle_norm_le_chord
#print axioms GMZP0.linearPhaseMean_geometric
#print axioms GMZP0.linearPhaseMean_chord_bound
#print axioms GMZP0.linear_weyl_inverse
#print axioms GMZP0.sum_fin_labels
#print axioms GMZP0.integerIntervalMean_eq_fin
#print axioms GMZP0.interval_pair_difference_sum
#print axioms GMZP0.weyl_correlation_sum
#print axioms GMZP0.weyl_mean_square_identity
#print axioms GMZP0.weylCorrelation_norm_le
#print axioms GMZP0.weyl_nonzero_correlation_lower
#print axioms GMZP0.sum_le_large_card_add
#print axioms GMZP0.many_large_weyl_correlations
#print axioms GMZP0.largeWeylShifts_mem
#print axioms GMZP0.weyl_small_scale_obstruction
#print axioms GMZP0.sum_Icc_as_fin
#print axioms GMZP0.linear_phase_sum_geometric
#print axioms GMZP0.linear_phase_sum_chord_bound
#print axioms GMZP0.linear_interval_sum_chord_bound
#print axioms GMZP0.linear_interval_weyl_inverse
#print axioms GMZP0.quadraticCirclePolynomial_difference
#print axioms GMZP0.cubicCirclePolynomial_difference
#print axioms GMZP0.weylCorrelation_phase_interval
#print axioms GMZP0.quadratic_weyl_correlation
#print axioms GMZP0.cubic_weyl_correlation
#print axioms GMZP0.quadratic_large_shift_control
#print axioms GMZP0.quadratic_many_returns
#print axioms GMZP0.close_integer_pair
#print axioms GMZP0.affine_return_small_multiple
#print axioms GMZP0.integer_card_le_diameter
#print axioms GMZP0.affine_fiber_spread
#print axioms GMZP0.affine_slope_from_rounded_returns
#print axioms GMZP0.card_returnRoundTargets
#print axioms GMZP0.rounded_affine_target_mem
#print axioms GMZP0.multiplied_affine_return_lift
#print axioms GMZP0.affine_return_amplification
#print axioms GMZP0.dense_returns_seed_card
#print axioms GMZP0.uniform_affine_dense_returns
#print axioms GMZP0.uniform_quadratic_weyl_large
#print axioms GMZP0.uniform_quadratic_weyl
#print axioms GMZP0.interval_length_card
#print axioms GMZP0.interval_mean_rescale
#print axioms GMZP0.interval_large_rescaling
#print axioms GMZP0.quadraticCirclePolynomial_translate
#print axioms GMZP0.uniform_quadratic_interval_weyl
#print axioms GMZP0.weylOverlap_card_le
#print axioms GMZP0.finite_positive_denominator_fiber
#print axioms GMZP0.uniform_cubic_dense_returns
#print axioms GMZP0.uniform_cubic_weyl_large
#print axioms GMZP0.uniform_cubic_weyl
#print axioms GMZP0.uniform_cubic_common_denominator
#print axioms GMZP0.cyclicCubeTimeAverage_as_polynomial
#print axioms GMZP0.uniform_original_cube_weyl
#print axioms GMZP0.weighted_condition_mass
#print axioms GMZP0.uniform_weighted_cube_weyl
#print axioms GMZP0.uniform_original_cube_capture

#check GMZP0.P0
#check GMZP0.WeightedCapture
#check GMZP0.p0_of_weightedCapture
#check GMZP0.FiniteMinorEstimate
#check GMZP0.finite_capture_from_model_operators
#check GMZP0.original_window_first_tt
#check GMZP0.original_window_finite_signed_lower
#check GMZP0.uniform_positive_safe_statistic
#check GMZP0.finiteSignedDoubleStatistic_eq_lag
#check GMZP0.uniform_positive_safe_lag_statistic
#check GMZP0.signed_plus_diagonal_reroot
#check GMZP0.uniform_positive_rerooted_average
#check GMZP0.finite_to_cyclic_modulus_average
#check GMZP0.uniform_positive_cyclic_average
#check GMZP0.cyclicModulusAverage_as_uniform_mean
#check GMZP0.exists_prime_cyclic_modulus
#check GMZP0.norm_Icc_translate
#check GMZP0.norm_fourShiftSmoothedAverage_sub_le
#check GMZP0.uniform_positive_smoothed_average
#check GMZP0.cyclicSmoothedLagB_four_faces
#check GMZP0.box_cauchy_schwarz
#check GMZP0.boxNorm_pow
#check GMZP0.cyclicSmoothedLagB_le_boxSum
#check GMZP0.cyclicBoxNormAverage_pow_le
#check GMZP0.uniform_positive_box_average
#check GMZP0.cubeMean_eq_boxMoment
#check GMZP0.cyclicRerootedCubeAverage_eq_moment
#check GMZP0.cyclicCubePhase_polynomial
#check GMZP0.cyclicRerootedCubeAverage_split_time
#check GMZP0.cyclicCube_original_vertices
#check GMZP0.uniform_positive_weighted_time_average
#check GMZP0.linear_interval_weyl_inverse
#check GMZP0.many_large_weyl_correlations
#check GMZP0.quadratic_many_returns
#check GMZP0.affine_return_small_multiple
#check GMZP0.uniform_affine_dense_returns
#check GMZP0.uniform_quadratic_weyl
#check GMZP0.uniform_quadratic_interval_weyl
#check GMZP0.uniform_cubic_weyl
#check GMZP0.uniform_cubic_common_denominator
#check GMZP0.uniform_original_cube_capture

example (hcapture : GMZP0.WeightedCapture) : GMZP0.P0 :=
  GMZP0.p0_of_weightedCapture hcapture

/-! F15: lag removal, sign reflection, and quantitative collision deletion. -/
#print axioms GMZP0.cyclicCubeVertex_zero_step
#print axioms GMZP0.cube_pair_collision_zero_step
#print axioms GMZP0.cube_pair_collision_zero_step_obstruction
#print axioms GMZP0.realUniformMean_resample
#print axioms GMZP0.uniform_event_le_one_over_card
#print axioms GMZP0.uniform_event_le_of_update_unique
#print axioms GMZP0.card_ascendingCubeLabelPairs
#print axioms GMZP0.cube_collision_probability
#print axioms GMZP0.positive_cube_collision_probability
#print axioms GMZP0.realUniformMean_equiv
#print axioms GMZP0.card_cubeSpatialParameters
#print axioms GMZP0.cyclicCubeNearMass_remove_lag
#print axioms GMZP0.cyclicCubeNearWeight_bounds
#print axioms GMZP0.cubeShiftSum_neg
#print axioms GMZP0.cyclicCubeVertex_neg_reflect
#print axioms GMZP0.cyclicCubeCubicCoeff_neg_reflect
#print axioms GMZP0.cyclicCubeWeight_neg_reflect
#print axioms GMZP0.cyclicCubeNearWeight_neg_reflect
#print axioms GMZP0.cubeNearWeight_mean_neg
#print axioms GMZP0.realUniformMean_sum
#print axioms GMZP0.uniform_event_union_le
#print axioms GMZP0.cubeShiftSum_flat
#print axioms GMZP0.flatCubeShiftSum_update_sub
#print axioms GMZP0.flatCubeShiftSum_update_other
#print axioms GMZP0.cube_collision_update_unique
#print axioms GMZP0.cube_pair_collision_probability
#print axioms GMZP0.realUniformMean_prod_four
#print axioms GMZP0.card_positiveCubeParameters
#print axioms GMZP0.cyclicSpatialCubeNearMass_positive
#print axioms GMZP0.cyclicCubeNearMass_positive
#print axioms GMZP0.smoothingShift_cast_injective
#print axioms GMZP0.positive_cube_step_ne_zero
#print axioms GMZP0.signedHorizontalLabel_injective
#print axioms GMZP0.signedHorizontalLabel_surjective
#print axioms GMZP0.real_signed_mean_eq_positive
#print axioms GMZP0.uniform_collision_scale
#print axioms GMZP0.cyclicDistinctCubeNearWeight_pos_iff
#print axioms GMZP0.uniform_distinct_original_cube_capture
#print axioms GMZP0.uniform_positive_original_cube_capture
#print axioms GMZP0.realUniformMean_add
#print axioms GMZP0.weighted_event_removal
#print axioms GMZP0.positive_cube_total_collision_probability
#print axioms GMZP0.cyclicDistinctPositiveCubeNearMass_lower
#check GMZP0.uniform_distinct_original_cube_capture

/-! F16: one simultaneous real lift, with original weights and responses. -/
#print axioms GMZP0.cube_choice_sum_eq
#print axioms GMZP0.exists_cube_integer_correction
#print axioms GMZP0.exists_cube_lift_zero
#print axioms GMZP0.frequency_coe_sum
#print axioms GMZP0.cubeRoundedSum_abs_le
#print axioms GMZP0.cubeRoundedSum_real_error
#print axioms GMZP0.cubeUnitRep_sum_coe
#print axioms GMZP0.cubeRoundedSum_circle_norm
#print axioms GMZP0.cube_rounding_branch
#print axioms GMZP0.cubeSign_one_or_neg_one
#print axioms GMZP0.cubeSign_abs
#print axioms GMZP0.card_positiveCubeVertices
#print axioms GMZP0.card_negativeCubeVertices
#print axioms GMZP0.bounded_integer_cube_sum
#print axioms GMZP0.exists_cyclic_lift_choice
#print axioms GMZP0.exists_cyclic_real_lift
#print axioms GMZP0.cyclicCube_scaled_frequency_sum
#print axioms GMZP0.cyclicCubeWeight_pos_vertices
#print axioms GMZP0.cyclic_lift_cube_probability
#print axioms GMZP0.cyclicDistinctCubeNearWeight_eq_ite_pos
#print axioms GMZP0.cyclicLiftValue_grid
#print axioms GMZP0.cyclicLiftValue_abs_le
#print axioms GMZP0.cyclicLiftValue_zero
#print axioms GMZP0.cyclicLiftValue_circle_error
#print axioms GMZP0.cyclicLiftValue_original_error
#print axioms GMZP0.separate_witnesses_not_one_global_witness
#print axioms GMZP0.exists_ge_realUniformMean
#print axioms GMZP0.mean_constant_event_weight
#print axioms GMZP0.exists_global_weighted_success
#print axioms GMZP0.realUniformMean_restrict
#print axioms GMZP0.uniform_singleton_probability
#print axioms GMZP0.uniform_restricted_assignment_probability
#print axioms GMZP0.uniform_restricted_event_lower
#print axioms GMZP0.realUniformMean_comm
#print axioms GMZP0.card_liftChoice
#print axioms GMZP0.liftChoice_bounds
#print axioms GMZP0.liftChoiceValue_grid
#print axioms GMZP0.liftChoiceValue_abs_le
#print axioms GMZP0.liftChoiceValue_circle_error
#print axioms GMZP0.liftGridSize_bounds
#print axioms GMZP0.uniform_lift_grid_scale
#print axioms GMZP0.frequencyUnitRep_bounds
#print axioms GMZP0.frequencyUnitRep_coe
#print axioms GMZP0.round_monotone_real
#print axioms GMZP0.round_between_integers
#print axioms GMZP0.liftRound_bounds
#print axioms GMZP0.liftRound_error
#print axioms GMZP0.liftRound_div_error
#print axioms GMZP0.uniform_original_real_lift
#check GMZP0.uniform_original_real_lift

-- F17: exact mesh, actual local fourth norm and original-data good fibres.
#print axioms GMZP0.circleCharacter_eq_one_iff
#print axioms GMZP0.completeCharacterMean_torsion
#print axioms GMZP0.short_rational_frequency_zero_iff
#print axioms GMZP0.rational_character_orthogonality
#print axioms GMZP0.realSignedCubeSum_grid
#print axioms GMZP0.realSignedCubeSum_abs_le
#print axioms GMZP0.realSignedCubeSum_abs_le_384
#print axioms GMZP0.realSignedCubeSum_grid_bound
#print axioms GMZP0.meshFrequency_mul_grid
#print axioms GMZP0.frequencyMeshMean_grid_integer
#print axioms GMZP0.frequencyMeshMean_real_zero
#print axioms GMZP0.frequencyMeshMean_realCube
#print axioms GMZP0.integer_frequency_alias_obstruction
#print axioms GMZP0.frequencyMeshMean_period
#print axioms GMZP0.frequency_mesh_size_obstruction
#print axioms GMZP0.localCubeMoment_nonneg
#print axioms GMZP0.localCubeMoment_le_one
#print axioms GMZP0.localCubeNorm_nonneg
#print axioms GMZP0.localCubeNorm_pow
#print axioms GMZP0.localCubeNorm_le_one
#print axioms GMZP0.localCubeMoment_complex
#print axioms GMZP0.weighted_real_cube_character
#print axioms GMZP0.weighted_frequency_cube_exact
#print axioms GMZP0.weighted_frequency_cube_real
#print axioms GMZP0.localBoxFunction_cyclic_vertex
#print axioms GMZP0.cyclicLocalMoment_expand
#print axioms GMZP0.modulatedCyclicField_norm
#print axioms GMZP0.modulatedCyclicField_norm_le
#print axioms GMZP0.cyclic_weighted_frequency_cube
#print axioms GMZP0.cyclic_local_frequency_row
#print axioms GMZP0.cyclicLocalFourMoment_eq_mass
#print axioms GMZP0.cyclicLocalFourthNormAverage_eq_moment
#print axioms GMZP0.cyclicLocalFourthNormAverage_eq_mass
#print axioms GMZP0.uniform_original_local_four
#print axioms GMZP0.bounded_moment_good_fibres
#print axioms GMZP0.cyclicLocalFourFiber_bounds
#print axioms GMZP0.cyclic_local_good_fibres
#print axioms GMZP0.uniform_original_local_fibres
#check GMZP0.uniform_original_local_four
#check GMZP0.uniform_original_local_fibres

-- F18: normalized Fourier, actual difference density, and the explicit twisted-cube interface.
#print axioms GMZP0.complexUniformMean_sum
#print axioms GMZP0.finite_character_pair_sum
#print axioms GMZP0.finiteFourier_inversion
#print axioms GMZP0.finiteFourier_inner
#print axioms GMZP0.finiteFourier_parseval
#print axioms GMZP0.finite_character_mul_conj
#print axioms GMZP0.correlation_character_factor
#print axioms GMZP0.finiteFourier_correlation
#print axioms GMZP0.realDifferenceDensity_nonneg
#print axioms GMZP0.finiteCorrelation_ofReal
#print axioms GMZP0.fourierEnergyWeight_nonneg
#print axioms GMZP0.fourierEnergyWeight_sum
#print axioms GMZP0.realDifferenceDensity_fourier
#print axioms GMZP0.positive_product_sum
#print axioms GMZP0.positive_product_mixture_bound
#print axioms GMZP0.differenceDensity_product_fourier
#print axioms GMZP0.differenceWeightedCubeMean_fourier
#print axioms GMZP0.differenceWeightedCubeMean_bound
#print axioms GMZP0.parameterDensity_nonneg
#print axioms GMZP0.parameterDensity_card
#print axioms GMZP0.parameterDensity_pushforward
#print axioms GMZP0.parameterDensity_mean_one
#print axioms GMZP0.parameterDensity_le_multiplicity
#print axioms GMZP0.parameterDensity_energy_le
#print axioms GMZP0.realDifferenceDensity_weighted
#print axioms GMZP0.parameterDifference_pushforward
#print axioms GMZP0.box_remove_bounded_face
#print axioms GMZP0.boxDoubledFaces_norm_le
#print axioms GMZP0.boxCorrelation_sq_le_doubled_bounded
#print axioms GMZP0.boxCorrelation_one_bounded
#print axioms GMZP0.box_cauchy_schwarz_bounded
#print axioms GMZP0.boxCorrelation_le_boxNorm_bounded
#print axioms GMZP0.uniform_product_pushforward
#print axioms GMZP0.localBoxFunction_additive_vertex
#print axioms GMZP0.local_cube_mean_reroot
#print axioms GMZP0.parameterDifference_product_pushforward
#print axioms GMZP0.localCubeMoment_difference
#print axioms GMZP0.localCubeMoment_eq_differenceWeighted
#print axioms GMZP0.localCubeMoment_fourier
#print axioms GMZP0.localCubeMoment_bound_of_twisted
#print axioms GMZP0.parameterDensity_identity
#print axioms GMZP0.localCubeMoment_const_one
#print axioms GMZP0.raw_probability_density_obstruction
#print axioms GMZP0.globalCubeMoment_additive
#check GMZP0.localCubeMoment_fourier
#check GMZP0.localCubeMoment_bound_of_twisted

#print axioms GMZP0.finite_self_correlation_le

#print axioms GMZP0.additiveCubeVertex_cons
#print axioms GMZP0.additiveCubeProduct_zero
#print axioms GMZP0.additiveCubeProduct_succ
#print axioms GMZP0.additiveCubeProduct_one
#print axioms GMZP0.crossCorrelation_character_factor
#print axioms GMZP0.finiteFourier_crossCorrelation
#print axioms GMZP0.finiteFourier_modulation
#print axioms GMZP0.derivativeFourier_crossCorrelation
#print axioms GMZP0.derivativeFourier_energy
#print axioms GMZP0.derivativeFourier_energy_le
#print axioms GMZP0.globalTwistedCubeMean_succ
#print axioms GMZP0.globalTwistedCubeMean_zero_twist
#print axioms GMZP0.globalTwistedCubeMean_one
#print axioms GMZP0.globalCubeMoment_nonneg
#print axioms GMZP0.globalCubeMoment_succ
#print axioms GMZP0.globalCubeMoment_one
#print axioms GMZP0.globalCubeMoment_two_fourier
#print axioms GMZP0.globalTwistedCubeMean_two_le
#print axioms GMZP0.globalTwistedCubeMean_le
#print axioms GMZP0.localCubeMoment_le_global
#print axioms GMZP0.globalCubeNorm_nonneg
#print axioms GMZP0.globalCubeNorm_pow
#print axioms GMZP0.localCubeNorm_le_global
#print axioms GMZP0.globalCubeMoment_lower_from_local
#print axioms GMZP0.character_first_cube_obstruction
#print axioms GMZP0.dimension_one_twist_obstruction
#check GMZP0.localCubeMoment_le_global
#check GMZP0.localCubeNorm_le_global
#check GMZP0.globalTwistedCubeMean_le

#print axioms GMZP0.globalCubeMoment_real_expansion
#print axioms GMZP0.global_frequency_moment_exact
#print axioms GMZP0.cyclicGlobalSeventhMoment_eq_mass
#check GMZP0.cyclicGlobalSeventhMoment_eq_mass

#print axioms GMZP0.exists_good_large_value
#print axioms GMZP0.cyclicPairLocalSeven_le_one
#print axioms GMZP0.original_scale_parameter_bound
#print axioms GMZP0.shrunk_radius_short
#print axioms GMZP0.nat_floor_ge_half
#print axioms GMZP0.shrunk_radius_lower
#print axioms GMZP0.pair_shift_integer_bound
#print axioms GMZP0.bounded_pair_values_no_wrap
#print axioms GMZP0.uniform_shrunk_radius_threshold
#print axioms GMZP0.cyclicLocalFourthNormAverage_le_one
#print axioms GMZP0.original_scale_bound_of_local_four
#check GMZP0.original_scale_bound_of_local_four

-- F21: core pair geometry and original seven-cubes with an explicit external input.
#print axioms GMZP0.pair_equal_value_gcd_divisibility
#print axioms GMZP0.pair_representation_code_bound
#print axioms GMZP0.integer_pair_representation_count
#print axioms GMZP0.cyclic_pair_representation_count
#print axioms GMZP0.cyclic_pair_density_energy
#print axioms GMZP0.pair_density_scale_bound
#print axioms GMZP0.pairDensityConstant_pos
#print axioms GMZP0.cyclic_pair_density_uniform
#print axioms GMZP0.global_seventh_moment_of_good_pair
#print axioms GMZP0.positive_label_multiple_mean
#print axioms GMZP0.positive_label_multiple_probability
#print axioms GMZP0.small_positive_label_probability
#print axioms GMZP0.pair_common_divisor_probability
#print axioms GMZP0.reciprocal_square_tail
#print axioms GMZP0.pair_large_gcd_probability
#print axioms GMZP0.exceptional_pair_probability
#print axioms GMZP0.pairCutoff_pos
#print axioms GMZP0.exceptional_pair_probability_cutoff
#print axioms GMZP0.exists_good_cyclic_pair
#print axioms GMZP0.pairSeventhLower_pos
#print axioms GMZP0.global_seventh_from_pair_average
#print axioms GMZP0.cyclic_global_seventh_of_good_fibres
#print axioms GMZP0.cyclic_real_seven_of_pair_family
#print axioms GMZP0.uniform_original_real_seven_of_concatenation
#check GMZP0.CyclicConcatenationInput
#check GMZP0.uniform_original_real_seven_of_concatenation

-- F22: exact seven-cube preparation and transport to original retained points.
#print axioms GMZP0.additiveCubeVertex_update_difference
#print axioms GMZP0.additive_cube_pair_update_unique
#print axioms GMZP0.additive_cube_pair_collision_probability
#print axioms GMZP0.card_ascendingSevenLabelPairs
#print axioms GMZP0.global_seven_collision_probability
#print axioms GMZP0.bounded_product_le_factor
#print axioms GMZP0.bounded_product_threshold_indicator
#print axioms GMZP0.globalThresholdCubeDensity_bounds
#print axioms GMZP0.globalDistinctThresholdCubeDensity_bounds
#print axioms GMZP0.global_threshold_density_lower
#print axioms GMZP0.globalDistinctThresholdCubeDensity_eq_count
#print axioms GMZP0.distinct_seven_cube_count_lower
#print axioms GMZP0.global_seven_threshold_collision_removal
#print axioms GMZP0.weighted_real_seven_to_distinct_threshold
#print axioms GMZP0.cyclic_prepared_seven_lower
#print axioms GMZP0.preparedSevenFibers_card
#print axioms GMZP0.preparedSevenFibers_cube_count
#print axioms GMZP0.uniform_seven_collision_threshold
#print axioms GMZP0.cyclic_nonzero_weight_in_original_range
#print axioms GMZP0.cyclic_row_preimage_card
#print axioms GMZP0.retainedOriginalFibers_card
#print axioms GMZP0.retainedOriginalFibers_support
#print axioms GMZP0.retainedOriginalFibers_weight_lower
#print axioms GMZP0.retainedOriginalFibers_mass
#print axioms GMZP0.retainedOriginalFibers_circle_error
#print axioms GMZP0.retainedOriginalFibers_uniform_mass
#print axioms GMZP0.retainedOriginalFibers_original_response
#print axioms GMZP0.uniform_original_prepared_seven_of_concatenation
#check GMZP0.uniform_original_prepared_seven_of_concatenation
#check GMZP0.retainedOriginalFibers_uniform_mass

-- F23: finite block Schur bounds for the exact original response and arbitrary masks.
#print axioms GMZP0.symmetric_nonnegative_form_bound
#print axioms GMZP0.kernel_action_energy_of_adjoint
#print axioms GMZP0.kernel_adjoint_energy_of_gram_rows
#print axioms GMZP0.kernel_action_energy_of_gram_rows
#print axioms GMZP0.kernel_action_sqrt_bound
#print axioms GMZP0.kernel_gram_row_bound
#print axioms GMZP0.kernel_action_energy_of_rows_columns
#print axioms GMZP0.kernel_adjoint_energy_of_action
#print axioms GMZP0.kernel_pairing_bound_of_energy
#print axioms GMZP0.outputMaskedKernel_action
#print axioms GMZP0.outputMaskedKernel_adjoint
#print axioms GMZP0.finiteEnergy_mask_le
#print axioms GMZP0.masked_action_energy_of_supported_adjoint
#print axioms GMZP0.gram_row_bound_needs_square_root
#print axioms GMZP0.kernelAdjoint_energy_blocks
#print axioms GMZP0.kernel_adjoint_energy_of_block_rows
#print axioms GMZP0.kernel_action_energy_of_block_rows
#print axioms GMZP0.blockGramKernel_adjoint
#print axioms GMZP0.blockGramKernel_energy_bound_symm
#print axioms GMZP0.outputMaskedKernel_gram
#print axioms GMZP0.blockGramKernel_masked_action
#print axioms GMZP0.blockGramKernel_mask_bound
#print axioms GMZP0.largeBlockCoefficient_nonneg
#print axioms GMZP0.largeBlockCoefficient_symm
#print axioms GMZP0.largeBlockCoefficient_row
#print axioms GMZP0.blockGramKernel_zero_outside
#print axioms GMZP0.largeBlockCoefficient_bounds_blocks
#print axioms GMZP0.kernel_energy_of_few_large_blocks
#print axioms GMZP0.horizontalKernel_row_norm_sum
#print axioms GMZP0.horizontalKernel_column_norm_sum
#print axioms GMZP0.original_horizontal_block_bound
#print axioms GMZP0.masked_original_horizontal_block_bound
#print axioms GMZP0.masked_original_energy_of_few_large_blocks
#print axioms GMZP0.masked_original_response_energy
#print axioms GMZP0.minorOutputMask_bound
#print axioms GMZP0.minorOutputMask_energy
#print axioms GMZP0.finiteMinorEstimate_of_few_large_compressed_blocks
#print axioms GMZP0.uniform_compressed_block_error_budget
#print axioms GMZP0.uniform_finiteMinorEstimate_of_compressed_counts
#check GMZP0.masked_original_response_energy
#check GMZP0.uniform_finiteMinorEstimate_of_compressed_counts

-- F24: original operator stability, actual assignment, and conditional freezing-step assembly.
#print axioms GMZP0.finiteResponse_energy_le
#print axioms GMZP0.positiveFiniteAverage_nonneg
#print axioms GMZP0.finiteResponse_zero_norm_input
#print axioms GMZP0.positiveFiniteAverage_energy_le
#print axioms GMZP0.finiteResponse_difference_le_average
#print axioms GMZP0.masked_response_difference_energy
#print axioms GMZP0.cubicPhase_le_of_scaled_circle_error
#print axioms GMZP0.masked_response_circle_stability
#print axioms GMZP0.disjoint_assignment_energy_obstruction
#print axioms GMZP0.finiteEnergy_assignment_eq_sum
#print axioms GMZP0.assignmentOutputMask_bound
#print axioms GMZP0.masked_minor_energy_le
#print axioms GMZP0.masked_finiteMinorEstimate
#print axioms GMZP0.assigned_masked_minor_energy
#print axioms GMZP0.assigned_child_error_budget
#print axioms GMZP0.finiteEnergy_sqrt_triangle
#print axioms GMZP0.finiteEnergy_add_bound
#print axioms GMZP0.finiteEnergy_three_piece_budget
#print axioms GMZP0.majorArc_transfer_without_closeness_obstruction
#print axioms GMZP0.majorArc_nearby_transfer
#print axioms GMZP0.minorArc_nearby_transfer
#print axioms GMZP0.freezing_circle_error_le_unit_scale
#print axioms GMZP0.freezing_manuscript_circle_scale
#print axioms GMZP0.restrictOutputMask_bound
#print axioms GMZP0.restrictOutputMask_ne_zero
#print axioms GMZP0.complementOutputMask_bound
#print axioms GMZP0.complementOutputMask_ne_zero
#print axioms GMZP0.outputMask_three_piece_decomposition
#print axioms GMZP0.masked_freezing_step
#print axioms GMZP0.finiteMinorEstimate_freezing_step
#print axioms GMZP0.uniform_freezing_step_from_compressed_counts
#check GMZP0.masked_response_circle_stability
#check GMZP0.uniform_freezing_step_from_compressed_counts
#print axioms GMZP0.truncated_sum_modulus_obstruction
#print axioms GMZP0.wideVerticalCoordinate_injective
#print axioms GMZP0.wideVerticalEmbed_coordinate
#print axioms GMZP0.wideVerticalEmbed_injective
#print axioms GMZP0.wideVerticalIndex_coordinate
#print axioms GMZP0.wide_parabola_target_bounds
#print axioms GMZP0.wideParabolaTarget_coordinate
#print axioms GMZP0.wideBlockTarget_coordinate
#print axioms GMZP0.wideBlockTarget_injective
#print axioms GMZP0.wideBlockTarget_original_collision
#print axioms GMZP0.wideZeroExtension_original
#print axioms GMZP0.wideZeroExtension_outside
#print axioms GMZP0.wideZeroExtension_energy
#print axioms GMZP0.kernelAction_wideZeroExtension
#print axioms GMZP0.wideHorizontalKernel_at_target
#print axioms GMZP0.wideHorizontalKernel_no_target
#print axioms GMZP0.original_collision_wide_label
#print axioms GMZP0.wideHorizontalKernel_original
#print axioms GMZP0.wideHorizontalKernel_original_action
#print axioms GMZP0.original_block_bound_of_wide
#print axioms GMZP0.masked_original_block_bound_of_wide
#print axioms GMZP0.wideBlockTarget_shared_iff
#print axioms GMZP0.wideHorizontalKernel_gram_labels
#print axioms GMZP0.wideBlockCoefficient_shared_product
#print axioms GMZP0.wideBlockCoefficient_double_phase
#print axioms GMZP0.wideHorizontalKernel_gram_phase_pairs
#print axioms GMZP0.complete_blockFinLabels_pair_sum
#print axioms GMZP0.wideHorizontalKernel_gram_lags
#print axioms GMZP0.wideDoublePhase_zero_lag
#print axioms GMZP0.wideLagSum_zero
#print axioms GMZP0.wideLagSum_norm_le
#print axioms GMZP0.original_vertical_single_fiber_sum_le
#print axioms GMZP0.wideHorizontalKernel_gram_row_le
#print axioms GMZP0.wide_lag_total_bound
#print axioms GMZP0.wide_block_energy_of_lag_bounds
#print axioms GMZP0.wide_nonzero_lag_sum
#print axioms GMZP0.wide_lag_maximizing_roots
#print axioms GMZP0.masked_large_block_lag_sum_lower
#print axioms GMZP0.sum_le_large_card_scaled
#print axioms GMZP0.many_large_lag_envelopes
#print axioms GMZP0.masked_large_block_many_lags
#print axioms GMZP0.uniform_masked_large_block_many_lags
#check GMZP0.wideHorizontalKernel_original_action
#check GMZP0.wide_block_energy_of_lag_bounds
#check GMZP0.uniform_masked_large_block_many_lags
#print axioms GMZP0.cubicCirclePolynomial_translate
#print axioms GMZP0.uniform_cubic_interval_common_denominator
#print axioms GMZP0.lagLabels_eq_interval
#print axioms GMZP0.lagLabels_interval_length_le
#print axioms GMZP0.uniform_cubic_lag_common_denominator
#print axioms GMZP0.affine_profile_agreement
#print axioms GMZP0.affine_double_phase_polynomial
#print axioms GMZP0.affine_wideDoublePhase
#print axioms GMZP0.affine_wideLagSum
#print axioms GMZP0.affineBlockCubic_reverse
#print axioms GMZP0.affine_two_direction_elimination
#print axioms GMZP0.affine_direction_branch_obstruction
#print axioms GMZP0.uniform_affine_power_returns
#print axioms GMZP0.uniform_bounded_multiplier_affine_returns
#print axioms GMZP0.uniform_affine_block_direction
#print axioms GMZP0.affine_two_direction_norm_bound
#print axioms GMZP0.uniform_affine_block_row_relation
#print axioms GMZP0.horizontalGap_injective_right
#print axioms GMZP0.uniform_affine_many_blocks_top_relation
#print axioms GMZP0.uniform_affine_no_relation_count
#print axioms GMZP0.affineVerticalProfile_real_eval
#print axioms GMZP0.largeBlockNeighbors_empty_of_zero_row
#print axioms GMZP0.uniform_affine_no_relation_operator
#print axioms GMZP0.affineNoRelationMask_bound
#print axioms GMZP0.uniform_affine_no_relation_mask_energy
#check GMZP0.uniform_affine_block_row_relation
#check GMZP0.uniform_affine_many_blocks_top_relation
#check GMZP0.uniform_affine_no_relation_mask_energy
#print axioms GMZP0.majorArc_grid_circle_approximation
#print axioms GMZP0.majorArc_universal_circle_list
#print axioms GMZP0.affine_increment_majorArc
#print axioms GMZP0.affineConstantChild_vertical_constant
#print axioms GMZP0.affine_child_error
#print axioms GMZP0.uniform_affine_constant_children
#print axioms GMZP0.mem_affineNoRelationPoints
#print axioms GMZP0.not_mem_affineNoRelationPoints
#print axioms GMZP0.uniform_affine_freezing_of_constant
#check GMZP0.uniform_affine_constant_children
#check GMZP0.UniformConstantFreezing
#check GMZP0.uniform_affine_freezing_of_constant
#print axioms GMZP0.cyclic_character_frequency
#print axioms GMZP0.cyclicConstantResponse_as_translation
#print axioms GMZP0.horizontalCubicResponse_as_fiber
#print axioms GMZP0.cyclicConstantResponse_energy
#print axioms GMZP0.cyclicConstantResponse_original
#print axioms GMZP0.original_constant_energy_of_horizontal
#print axioms GMZP0.finiteMinorEstimate_of_horizontal
#print axioms GMZP0.uniform_constant_freezing_of_horizontal
#print axioms GMZP0.finiteCyclicIndex_val
#print axioms GMZP0.finiteCyclicIndex_injective
#print axioms GMZP0.cyclicZeroExtend_original
#print axioms GMZP0.cyclicZeroExtend_outside
#print axioms GMZP0.cyclicZeroExtend_energy
#print axioms GMZP0.finiteCyclicIndex_energy_le
#print axioms GMZP0.endpointIndex_horizontal
#print axioms GMZP0.endpointIndex_cyclic
#print axioms GMZP0.cyclicInput_endpoint
#print axioms GMZP0.cyclicInput_energy
#print axioms GMZP0.finiteFourier_sum
#print axioms GMZP0.finiteFourier_const_mul
#print axioms GMZP0.finiteFourier_translate
#print axioms GMZP0.verticalTranslationSum_fourier
#print axioms GMZP0.verticalTranslationSum_energy
#check GMZP0.UniformHorizontalConstantFreezing
#check GMZP0.uniform_constant_freezing_of_horizontal
#print axioms GMZP0.uniform_constant_entry_return
#print axioms GMZP0.uniform_constant_many_entries_majorArc
#print axioms GMZP0.uniform_horizontal_constant_freezing_of_weyl
#print axioms GMZP0.uniform_constant_freezing_of_weyl
#print axioms GMZP0.uniform_affine_freezing_of_weyl
#print axioms GMZP0.gram_row_of_few_large_entries
#print axioms GMZP0.outputMaskedKernel_gram_norm_le
#print axioms GMZP0.masked_energy_of_few_horizontal_entries
#print axioms GMZP0.horizontalMinorMask_bound
#print axioms GMZP0.horizontal_minor_energy_of_counts
#print axioms GMZP0.constant_finiteMinorEstimate_of_counts
#print axioms GMZP0.uniform_constant_estimate_of_counts
#print axioms GMZP0.horizontalFourierPhase_product
#print axioms GMZP0.constantGramPhase_coefficients
#print axioms GMZP0.horizontalCubicKernel_gram_integer
#print axioms GMZP0.blockLabels_eq_interval
#print axioms GMZP0.horizontalCubicKernel_gram_norm_le
#print axioms GMZP0.horizontalCubicKernel_large_sum
#print axioms GMZP0.constant_two_coefficient_return
#print axioms GMZP0.constant_leading_coefficient_obstruction
#print axioms GMZP0.horizontalEndpointIndex_injective
#print axioms GMZP0.horizontalEndpointIndex_collision_iff
#print axioms GMZP0.horizontalEndpointIndex_shifted
#print axioms GMZP0.horizontalEndpointIndex_collision_mem
#print axioms GMZP0.horizontal_collision_sum
#print axioms GMZP0.norm_horizontalFourierPhase
#print axioms GMZP0.horizontalFourierPhase_label
#print axioms GMZP0.horizontalCubicKernel_action
#print axioms GMZP0.horizontalCubicKernel_gram
#print axioms GMZP0.horizontalCubicKernel_diagonal
#print axioms GMZP0.horizontalCubicKernel_gram_labels
#check GMZP0.CubicTwoCoefficientWeylInput
#check GMZP0.uniform_constant_freezing_of_weyl
#check GMZP0.uniform_affine_freezing_of_weyl
#print axioms GMZP0.uniform_polynomial_lag_leading_coefficient
#print axioms GMZP0.ordinary_top_scalar_factor
#print axioms GMZP0.ordinary_power_return_reverse
#print axioms GMZP0.uniform_ordinary_block_partner_relation
#print axioms GMZP0.uniform_ordinary_block_row_relation
#print axioms GMZP0.ordinary_profile_agreement
#print axioms GMZP0.ordinary_profile_original_response
#print axioms GMZP0.ordinary_wideDoublePhase
#print axioms GMZP0.ordinary_wideLagSum
#print axioms GMZP0.ordinary_wide_top_coefficient
#print axioms GMZP0.ordinary_wide_top_coefficient_reverse
#print axioms GMZP0.ordinary_profile_degree_zero
#print axioms GMZP0.ordinary_profile_degree_one
#print axioms GMZP0.uniform_ordinary_freezing_zero
#print axioms GMZP0.uniform_ordinary_freezing_one
#print axioms GMZP0.ordinary_affine_comp_degree
#print axioms GMZP0.ordinary_affine_comp_coeff
#print axioms GMZP0.cubicShiftDifference_expansion
#print axioms GMZP0.cubicShiftDifference_degree
#print axioms GMZP0.cubicShiftDifference_coeff_two
#print axioms GMZP0.ordinaryDoublePhasePolynomial_eval
#print axioms GMZP0.ordinaryDoublePhasePolynomial_degree
#print axioms GMZP0.ordinaryDoublePhasePolynomial_top_coeff
#print axioms GMZP0.ordinary_degree_one_top_obstruction
#print axioms GMZP0.ordinary_eval_degree_zero
#print axioms GMZP0.ordinary_eval_degree_one
#check GMZP0.PolynomialLeadingWeylInput
#check GMZP0.UniformOrdinaryFreezing
#check GMZP0.uniform_ordinary_block_row_relation
#print axioms GMZP0.ordinaryTopRelation_one
#print axioms GMZP0.ordinary_erase_degree
#print axioms GMZP0.ordinary_erase_eval
#print axioms GMZP0.ordinaryChildPolynomial_coeff
#print axioms GMZP0.ordinaryChildPolynomial_degree
#print axioms GMZP0.ordinary_child_error
#print axioms GMZP0.ordinary_child_zero_branch_obstruction
#print axioms GMZP0.ordinary_increment_majorArc
#print axioms GMZP0.majorArc_universal_real_list
#print axioms GMZP0.uniform_ordinary_lower_children
#print axioms GMZP0.uniform_degree_one_monomial_returns
#print axioms GMZP0.uniform_bounded_multiplier_monomial_returns
#print axioms GMZP0.uniform_ordinary_many_blocks_top_relation
#print axioms GMZP0.uniform_ordinary_no_relation_count
#print axioms GMZP0.uniform_ordinary_no_relation_operator
#print axioms GMZP0.mem_ordinaryNoRelationPoints
#print axioms GMZP0.not_mem_ordinaryNoRelationPoints
#print axioms GMZP0.uniform_ordinary_freezing_step
#print axioms GMZP0.uniform_ordinary_freezing_of_returns
#check GMZP0.MonomialDenseReturns
#check GMZP0.uniform_ordinary_freezing_of_returns
#print axioms GMZP0.integer_monomial_interpolation
#print axioms GMZP0.uniform_monomial_pattern_seed
#print axioms GMZP0.bounded_integer_cluster
#print axioms GMZP0.dense_monomial_cluster_card
#print axioms GMZP0.uniform_monomial_seed
#print axioms GMZP0.nonnegative_monomial_returns
#print axioms GMZP0.nonnegative_power_gap
#print axioms GMZP0.monomial_fiber_spread
#print axioms GMZP0.monomial_from_rounded_returns
#print axioms GMZP0.rounded_monomial_target_mem
#print axioms GMZP0.uniform_monomial_amplification
#print axioms GMZP0.monomial_dense_returns
#print axioms GMZP0.uniform_ordinary_freezing_of_weyl
#check GMZP0.monomial_dense_returns
#check GMZP0.uniform_ordinary_freezing_of_weyl
#print axioms GMZP0.observationTranslate_apply
#print axioms GMZP0.observationTranslate_comp
#print axioms GMZP0.observationTranslate_one
#print axioms GMZP0.observation_difference_mem
#print axioms GMZP0.observation_difference_translate_mem
#print axioms GMZP0.observation_invariant_constant
#print axioms GMZP0.observation_annihilator_iff
#print axioms GMZP0.observation_integer_translate
#print axioms GMZP0.observationConstant_apply
#print axioms GMZP0.observation_constant_mem_difference
#print axioms GMZP0.observation_mul_base
#print axioms GMZP0.observation_mul_obs
#print axioms GMZP0.observation_one_base
#print axioms GMZP0.observation_one_obs
#print axioms GMZP0.observation_inv_base
#print axioms GMZP0.observation_inv_obs
#print axioms GMZP0.observation_lattice_mem
#print axioms GMZP0.observation_representative_eq
#print axioms GMZP0.observation_correction_mul
#print axioms GMZP0.observation_phase_lattice_change
#print axioms GMZP0.observation_circle_lattice_invariant
#print axioms GMZP0.quotient_observation_mk
#print axioms GMZP0.observation_at_canonical
#print axioms GMZP0.quotient_observation_norm
#print axioms GMZP0.observation_curve_real_phase
#print axioms GMZP0.observation_curve_quotient
#print axioms GMZP0.observation_profile_agreement
#print axioms GMZP0.observation_profile_original_response
#print axioms GMZP0.observation_block_circle_phase
#print axioms GMZP0.observation_wide_lag_sum
#print axioms GMZP0.observation_character_curve
#print axioms GMZP0.observation_difference_nonzero
#print axioms GMZP0.observation_one_mem_difference_of_flag
#print axioms GMZP0.affine_real_observation_one
#print axioms GMZP0.observation_missing_pullback_obstruction
#print axioms GMZP0.mem_weightedPolynomialBelow
#print axioms GMZP0.weightedPolynomialBelow_zero
#print axioms GMZP0.weightedPolynomialBelow_mono
#print axioms GMZP0.weighted_monomial_mem
#print axioms GMZP0.weighted_constant_mem
#print axioms GMZP0.weighted_variable_mem
#print axioms GMZP0.weighted_mul_le
#print axioms GMZP0.weighted_mul_lt
#print axioms GMZP0.weighted_mul_lt_right
#print axioms GMZP0.weighted_substitution_product
#print axioms GMZP0.weighted_substitution_power
#print axioms GMZP0.weighted_substitution_variable
#print axioms GMZP0.weighted_substitution_monomial
#print axioms GMZP0.weighted_substitution_difference
#print axioms GMZP0.weighted_substitution_preserves
#print axioms GMZP0.coordinatePolynomialEvaluation_apply
#print axioms GMZP0.coordinate_evaluation_translate
#print axioms GMZP0.mem_coordinateObservationFlag
#print axioms GMZP0.coordinateObservationFlag_zero
#print axioms GMZP0.coordinateObservationFlag_mono
#print axioms GMZP0.coordinateObservationFlag_lowers
#print axioms GMZP0.coordinateObservationFlag_top
#print axioms GMZP0.observation_one_mem_difference_of_coordinates
#print axioms GMZP0.observation_difference_proper_of_flag
#print axioms GMZP0.observation_difference_structure_of_coordinates
#print axioms GMZP0.observation_integer_difference_saturated
#print axioms GMZP0.weighted_monomial_weight_le
#print axioms GMZP0.weighted_polynomial_mem_of_totalDegree
#print axioms GMZP0.triangular_monomial_weight_lt
#print axioms GMZP0.triangular_correction_mem
#print axioms GMZP0.triangular_observation_uniform_bound
#print axioms GMZP0.observation_difference_structure_of_triangular
#print axioms GMZP0.triangular_ordinary_degree_obstruction
#print axioms GMZP0.observation_base_inclusion_base
#print axioms GMZP0.observation_base_inclusion_obs
#print axioms GMZP0.observation_fiber_inclusion_base
#print axioms GMZP0.observation_fiber_inclusion_obs
#print axioms GMZP0.observation_base_fiber_decomposition
#print axioms GMZP0.observation_base_projection_surjective
#print axioms GMZP0.observation_commutator_base
#print axioms GMZP0.observation_commutator_obs
#print axioms GMZP0.observation_commutator_base_fiber
#print axioms GMZP0.observation_commutator_fiber
#print axioms GMZP0.observation_two_translates_difference_mem
#print axioms GMZP0.observation_commutator_obs_mem
#print axioms GMZP0.observation_difference_fiber_smul_mem
#print axioms GMZP0.observation_difference_fiber_mem
#print axioms GMZP0.observation_base_commutator_mem
#print axioms GMZP0.observation_commutator_eq
#print axioms GMZP0.observationFiberSubgroup_bot
#print axioms GMZP0.observation_eq_fiber_of_base_one
#print axioms GMZP0.observation_fiber_commutator_le
#print axioms GMZP0.observation_lowerCentral_projection
#print axioms GMZP0.observation_lowerCentral_fiber_start
#print axioms GMZP0.observation_lowerCentral_fiber_descent
#print axioms GMZP0.observation_lowerCentral_vanishes_of_flag
#print axioms GMZP0.observation_nilpotent_of_flag
#print axioms GMZP0.observation_nilpotent_of_triangular
#print axioms GMZP0.observation_character_decomposition
#print axioms GMZP0.observation_character_annihilates_difference
#print axioms GMZP0.observation_character_translate_invariant
#print axioms GMZP0.observation_character_linear_form
#print axioms GMZP0.observation_actual_character_curve
#print axioms GMZP0.observation_character_base_integral
#print axioms GMZP0.observation_character_fiber_integral
#print axioms GMZP0.affine_observation_unit_difference
#print axioms GMZP0.observation_abelian_base_obstruction
#print axioms GMZP0.observation_base_inclusion_continuous
#print axioms GMZP0.observation_fiber_inclusion_continuous
#print axioms GMZP0.observation_character_base_continuous
#print axioms GMZP0.observation_character_fiber_continuous
#print axioms GMZP0.observationContinuousFiber_apply
#print axioms GMZP0.observation_continuous_character_form
#print axioms GMZP0.observation_continuous_character_curve
#print axioms GMZP0.observation_continuous_fiber_integral
#print axioms GMZP0.observation_continuous_character_nontrivial
#print axioms GMZP0.coordinatePolynomialSpace_finiteDimensional
#print axioms GMZP0.observation_le_coordinatePolynomialSpace
#print axioms GMZP0.observation_finiteDimensional_of_degree
#print axioms GMZP0.observation_finrank_le_polynomial
#print axioms GMZP0.observation_has_moduleTopology
#print axioms GMZP0.observation_translate_continuous
#print axioms GMZP0.observation_difference_closed
#print axioms GMZP0.observation_basis_coordinates_continuous
#print axioms GMZP0.vectorPolynomialValue_linear
#print axioms GMZP0.vectorPolynomial_coefficient_mem
#print axioms GMZP0.vectorPolynomial_span_values
#print axioms GMZP0.rationalBasisVector_repr
#print axioms GMZP0.observation_difference_mem_of_basis
#print axioms GMZP0.observation_polynomial_coefficient_mem
#print axioms GMZP0.observation_difference_eq_coefficient_span
#print axioms GMZP0.observationRationalGenerators_card
#print axioms GMZP0.observationRationalGenerators_image
#print axioms GMZP0.observation_difference_rational_of_polynomial
#print axioms GMZP0.observation_evaluation_basis
#print axioms GMZP0.observation_evaluation_continuous
#print axioms GMZP0.observation_translate_joint_continuous
#print axioms GMZP0.observation_pair_coordinates_continuous
#print axioms GMZP0.observation_group_mul_continuous
#print axioms GMZP0.observation_group_inv_continuous
#print axioms GMZP0.observation_isTopologicalGroup
#print axioms GMZP0.observation_function_continuous_of_coordinates
#print axioms GMZP0.observation_topologicalGroup_of_degree
#print axioms GMZP0.rationalMatrixSupport_contains
#print axioms GMZP0.rational_polynomial_eval_on_support
#print axioms GMZP0.rational_matrix_vector_expansion
#print axioms GMZP0.observation_matrix_translation_expansion
#print axioms GMZP0.observation_difference_rational_of_matrix
#print axioms GMZP0.polynomial_restricted_parameter_obstruction
#print axioms GMZP0.rational_polynomial_integer_multiple
#print axioms GMZP0.real_polynomial_zero_of_integer_values
#print axioms GMZP0.observationEvaluation_apply
#print axioms GMZP0.observation_finite_determining_points
#print axioms GMZP0.observation_integer_discrete_of_evaluations
#print axioms GMZP0.observation_integer_discrete
#print axioms GMZP0.observation_integer_points_separate
#print axioms GMZP0.observation_integer_discrete_of_coordinates
#print axioms GMZP0.observationIntegerLattice_mem
#print axioms GMZP0.observation_rational_integer_multiple
#print axioms GMZP0.observation_integer_span_top
#print axioms GMZP0.observation_representatives_of_rational_basis
#print axioms GMZP0.observation_integer_full_lattice
#print axioms GMZP0.observation_integer_floor_cast
#print axioms GMZP0.observationIntegerEvaluation_cast
#print axioms GMZP0.observationIntegerEvaluation_injective
#print axioms GMZP0.observation_integer_basis_of_evaluations
#print axioms GMZP0.observation_integer_basis
#print axioms GMZP0.observation_integer_basis_of_presentation
#print axioms GMZP0.observationIntegerDifferenceModule_mem
#print axioms GMZP0.observationIntegerToRealQuotient_ker
#print axioms GMZP0.observationIntegerQuotientEmbedding_mk
#print axioms GMZP0.observationIntegerQuotientEmbedding_injective
#print axioms GMZP0.observation_integer_quotient_torsionFree
#print axioms GMZP0.observation_integer_module_finite
#print axioms GMZP0.observation_integer_quotient_basis
#print axioms GMZP0.observation_integer_quotient_section
#print axioms GMZP0.observation_integer_section_remainder
#print axioms GMZP0.observationIntegerSplitEquiv_apply
#print axioms GMZP0.observation_integer_adapted_basis
#print axioms GMZP0.observation_integer_quotient_reconstruction
#print axioms GMZP0.observationFiniteRealEvaluation_cast
#print axioms GMZP0.observation_integer_family_real_independent
#print axioms GMZP0.observation_integer_basis_real_span
#print axioms GMZP0.observationRealBasis_apply
#print axioms GMZP0.observation_integer_basis_card
#print axioms GMZP0.observationRealBasis_repr_int
#print axioms GMZP0.observation_rational_combination_evaluation
#print axioms GMZP0.observation_rational_combination_integer_multiple
#print axioms GMZP0.observation_integer_intersection_real_span
#print axioms GMZP0.observation_adapted_left_real_span
#print axioms GMZP0.observationQuotientCoordinates_apply
#print axioms GMZP0.observation_quotient_coefficient_decomposition
#print axioms GMZP0.observation_quotient_coordinates_kernel
#print axioms GMZP0.observation_quotient_coordinates_surjective
#print axioms GMZP0.observation_quotient_coordinates_integral
#print axioms GMZP0.observation_quotient_coordinates_integer_surjective
#print axioms GMZP0.observation_quotient_coordinates_polynomial
#print axioms GMZP0.observation_adapted_bases_of_presentation
#print axioms GMZP0.observation_adapted_bases_of_matrix
#print axioms GMZP0.integer_quotient_torsion_obstruction
#print axioms GMZP0.integer_quotient_section_obstruction
#print axioms GMZP0.observationClosedCell_mem
#print axioms GMZP0.observation_closedCell_compact
#print axioms GMZP0.observation_lattice_rounding_sum
#print axioms GMZP0.observation_lattice_remainder_coordinates
#print axioms GMZP0.observation_reduce_to_closedCell
#print axioms GMZP0.observation_integer_quotient_compact
#print axioms GMZP0.observation_group_lattice_discrete
#print axioms GMZP0.observation_group_closedCell_compact
#print axioms GMZP0.observation_right_lattice_reduction
#print axioms GMZP0.observation_group_quotient_compact
#print axioms GMZP0.compact_quotient_right_cover
#print axioms GMZP0.observation_group_quotient_compact_of_base
#print axioms GMZP0.observation_group_cocompact_of_presentation
#print axioms GMZP0.observation_group_lattice_of_presentation
#print axioms GMZP0.observationFiberPhase_mk
#print axioms GMZP0.observationFiberCharacter_mk
#print axioms GMZP0.observationFiberCharacter_add
#print axioms GMZP0.observationFiberCharacter_norm
#print axioms GMZP0.observationFiberPhase_continuous
#print axioms GMZP0.observationFiberCharacter_continuous
#print axioms GMZP0.observation_half_character
#print axioms GMZP0.observationFiberCharacter_half_translate
#print axioms GMZP0.observationFiberPhase_surjective
#print axioms GMZP0.observationFiberCharacter_nontrivial
#print axioms GMZP0.observationFiberPoint_mk
#print axioms GMZP0.quotient_observation_fiber
#print axioms GMZP0.observationQuotientBaseProjection_mk
#print axioms GMZP0.observationFiberPoint_projection
#print axioms GMZP0.observationFiberPoint_injective
#print axioms GMZP0.observationFiberPoint_range
#print axioms GMZP0.observationFiberPoint_continuous
#print axioms GMZP0.observation_integer_lattice_closed
#print axioms GMZP0.observationFiber_t2
#print axioms GMZP0.observationFiberCharacter_integrable
#print axioms GMZP0.observationFiberCharacter_integral_zero
#print axioms GMZP0.quotient_observation_fiber_mean_zero
#print axioms GMZP0.quotient_observation_fiber_cutoff_mean_zero
#print axioms GMZP0.observation_fiber_haar_of_presentation
#print axioms GMZP0.observation_zero_module_mean_obstruction
#print axioms GMZP0.observation_constant_action_base
#print axioms GMZP0.quotient_observation_constant_action
#print axioms GMZP0.quotient_observation_cutoff_half_action
#print axioms GMZP0.quotient_observation_cutoff_integral_zero
#print axioms GMZP0.compact_local_homeomorph_measurable_section
#print axioms GMZP0.observation_section_idempotent
#print axioms GMZP0.observation_section_range_fixed
#print axioms GMZP0.observation_section_unique_correction
#print axioms GMZP0.observation_section_measurable_range
#print axioms GMZP0.observation_correction_measurable
#print axioms GMZP0.observation_measurable_section_exists
#print axioms GMZP0.observation_measurable_section_exists_polish
#print axioms GMZP0.observation_measurable_section_in_cover
#print axioms GMZP0.observation_compact_measurable_section_exists
#print axioms GMZP0.observation_borel_fundamental_domain_exists
#print axioms GMZP0.observation_real_phase_measurable
#print axioms GMZP0.quotient_observation_measurable
#print axioms GMZP0.observation_quotient_base_measurable
#print axioms GMZP0.quotient_observation_cutoff_measurable
#print axioms GMZP0.observation_quotient_measurable_action
#print axioms GMZP0.quotient_observation_measurable_cutoff_integral_zero
#print axioms GMZP0.observation_space_polish
#print axioms GMZP0.observation_group_polish
#print axioms GMZP0.observation_group_locallyCompact
#print axioms GMZP0.observation_group_t2
#print axioms GMZP0.observation_quotient_borel
#print axioms GMZP0.observation_borel_domain_of_presentation
#print axioms GMZP0.strict_right_domain_inverse
#print axioms GMZP0.strict_left_domain_right_preimage
#print axioms GMZP0.haar_right_invariant_of_compact_left_domain
#print axioms GMZP0.cocompact_lattice_haar_right_invariant
#print axioms GMZP0.strict_right_domain_fundamental
#print axioms GMZP0.compact_quotient_invariant_probability
#print axioms GMZP0.observation_quotient_probability_of_presentation
#print axioms GMZP0.observation_global_mean_zero_of_presentation
#print axioms GMZP0.observationQuotientSection_mk
#print axioms GMZP0.observationQuotientSection_rightInverse
#print axioms GMZP0.quotient_periodization_translate
#print axioms GMZP0.quotient_section_domain_translate
#print axioms GMZP0.observationQuotientSection_measurable
#print axioms GMZP0.quotient_section_domain_measurable
#print axioms GMZP0.quotient_periodization_measurable
#print axioms GMZP0.quotient_countingLift_lintegral
#print axioms GMZP0.quotient_countingLift_leftInvariant
#print axioms GMZP0.quotient_countingLift_recover
#print axioms GMZP0.quotient_countingLift_domain_mass
#print axioms GMZP0.quotient_countingLift_finite_compacts
#print axioms GMZP0.compact_quotient_bounded_section
#print axioms GMZP0.compact_quotient_invariant_probability_unique
#print axioms GMZP0.observationQuotientBaseProjection_smul
#print axioms GMZP0.observation_base_marginal_invariant
#print axioms GMZP0.observation_base_projection_measurePreserving
#print axioms GMZP0.observation_measure_identification_of_presentation
#print axioms GMZP0.integer_half_open_cell_unique
#print axioms GMZP0.triangular_integer_cell
#print axioms GMZP0.polynomial_eval_eq_of_prefix
#print axioms GMZP0.triangular_diagonal_cancellation_obstruction
#print axioms GMZP0.triangular_coordinate_cell_correction
#print axioms GMZP0.observation_sections_eq_on_strict_domain
#print axioms GMZP0.coordinate_half_open_cell_measurable
#print axioms GMZP0.coordinate_half_open_cell_compact_closure
#print axioms GMZP0.quotient_compact_of_strict_cell
#print axioms GMZP0.measurable_section_of_strict_domain
#print axioms GMZP0.specified_section_measurable_of_strict_domain
#print axioms GMZP0.canonical_coordinate_section
#print axioms GMZP0.specified_canonical_coordinate_section_measurable
#print axioms GMZP0.canonical_original_observation_mean_zero
#print axioms GMZP0.original_correction_locally_constant
#print axioms GMZP0.original_section_continuousAt_interior
#print axioms GMZP0.coordinate_cell_interior_of_strict
#print axioms GMZP0.specified_coordinate_section_continuousAt
#print axioms GMZP0.original_observation_phase_continuousAt
#print axioms GMZP0.original_quotient_observation_pullback_continuousAt
#print axioms GMZP0.boundary_cutoff_empty
#print axioms GMZP0.boundary_cutoff_bounds
#print axioms GMZP0.boundary_cutoff_zero_near
#print axioms GMZP0.boundary_majorant_zero_outside
#print axioms GMZP0.boundary_cutoff_one_outside
#print axioms GMZP0.boundary_majorant_lipschitz
#print axioms GMZP0.boundary_cutoff_lipschitz
#print axioms GMZP0.boundary_majorant_integrable
#print axioms GMZP0.boundary_majorant_integral_le_tube
#print axioms GMZP0.orbit_discrepancy_real
#print axioms GMZP0.orbit_boundary_majorant_mean_le
#print axioms GMZP0.unit_observation_cutoff_error
#print axioms GMZP0.boundary_orbit_observation_bound
#print axioms GMZP0.boundary_error_parameters
#print axioms GMZP0.uniform_boundary_nonequidistribution
#print axioms GMZP0.original_boundary_cutoff_mean_zero
#print axioms GMZP0.original_boundary_orbit_bound
#print axioms GMZP0.original_boundary_nonequidistribution
#print axioms GMZP0.orbit_boundary_visit_fraction_le
#print axioms GMZP0.null_boundary_full_orbit_visits
#print axioms GMZP0.coordinate_last_split_apply
#print axioms GMZP0.coordinate_last_split_volume
#print axioms GMZP0.measurable_snoc_zero
#print axioms GMZP0.triangular_correction_ignore_last
#print axioms GMZP0.triangular_translation_volume
#print axioms GMZP0.triangular_polynomial_volume
#print axioms GMZP0.triangular_volume_diagonal_obstruction
#print axioms GMZP0.coordinate_volume_preserving
#print axioms GMZP0.coordinate_volume_finite_compacts
#print axioms GMZP0.coordinate_volume_open_positive
#print axioms GMZP0.coordinate_volume_left_invariant
#print axioms GMZP0.coordinate_volume_isHaar
#print axioms GMZP0.coordinate_cell_volume_one
#print axioms GMZP0.coordinate_quotient_volume_probability
#print axioms GMZP0.coordinate_quotient_volume_invariant
#print axioms GMZP0.coordinate_quotient_volume_identification
#print axioms GMZP0.coordinate_quotient_event_bound
#print axioms GMZP0.coordinate_lower_strip_volume
#print axioms GMZP0.coordinate_upper_strip_volume
#print axioms GMZP0.coordinate_boundary_strip_measurable
#print axioms GMZP0.coordinate_boundary_strip_volume
#print axioms GMZP0.coordinate_face_tube_subset_strip
#print axioms GMZP0.coordinate_face_tube_volume
#print axioms GMZP0.specified_section_fixes_strict_domain
#print axioms GMZP0.coordinate_quotient_strip_event_bound
#print axioms GMZP0.original_section_boundary_strip_mass
#print axioms GMZP0.coordinate_cell_closure
#print axioms GMZP0.coordinate_cell_interior
#print axioms GMZP0.coordinate_cell_frontier
#print axioms GMZP0.strict_domain_translated_frontier_avoids_interior
#print axioms GMZP0.coordinate_near_complement_mem_strip
#print axioms GMZP0.metric_boundary_tube_measurable
#print axioms GMZP0.original_coset_infDist_lt_iff
#print axioms GMZP0.quotient_mk_lipschitz_of_coset_formula
#print axioms GMZP0.original_cell_face_image_compact
#print axioms GMZP0.original_quotient_face_tube_strip_cover
#print axioms GMZP0.coordinate_quotient_face_tube_measure_le
#print axioms GMZP0.local_probability_bound_global
#print axioms GMZP0.original_quotient_face_tube_linear_bound
#print axioms GMZP0.cubic_coordinate_comparison_obstruction
#print axioms GMZP0.compact_locally_lipschitz_uniform
#print axioms GMZP0.coordinate_cell_uniform_local_metric
#print axioms GMZP0.original_quotient_face_tube_linear_of_locallyLipschitz
#print axioms GMZP0.original_corrections_finite_on_compact
#print axioms GMZP0.original_representative_interior_off_faces
#print axioms GMZP0.original_correction_constant_off_faces
#print axioms GMZP0.original_correction_change_crosses_faces
#print axioms GMZP0.original_correction_change_boundary_distance
#print axioms GMZP0.real_circle_character_chord
#print axioms GMZP0.observation_evaluation_difference_bound
#print axioms GMZP0.original_observation_same_correction_bound
#print axioms GMZP0.unit_cutoff_product_difference
#print axioms GMZP0.boundary_cutoff_le_distance_div
#print axioms GMZP0.boundary_cutoff_lipschitz_of_local_alternative
#print axioms GMZP0.original_observation_local_alternative
#print axioms GMZP0.original_observation_cutoff_lipschitz_of_charts
#print axioms GMZP0.original_boundary_nonequidistribution_of_charts
#print axioms GMZP0.boundary_cutoff_unrelated_jump_obstruction
#print axioms GMZP0.compact_coordinate_short_paths
#print axioms GMZP0.original_pair_charts_of_controlled_lifts
#print axioms GMZP0.coset_metric_compact_of_cover
#print axioms GMZP0.coset_metric_isQuotientMap
#print axioms GMZP0.coset_metric_topology_eq_coinduced
#print axioms GMZP0.compact_coset_pair_lifts
#print axioms GMZP0.compact_coset_coordinate_pair_lifts
#print axioms GMZP0.lipschitz_of_uniform_local_bound
#print axioms GMZP0.observation_metric_cell_compact
#print axioms GMZP0.observation_metric_locallyCompact
#print axioms GMZP0.original_observation_controlled_pair_lifts
#print axioms GMZP0.original_projection_local_bound
#print axioms GMZP0.original_projection_lipschitz_of_lifts
#print axioms GMZP0.original_observation_metric_cutoff
#print axioms GMZP0.large_N_normalized_sum
#print axioms GMZP0.N_normalized_orbit_forcing
#print axioms GMZP0.interval_normalization_cardinality_obstruction
#print axioms GMZP0.original_metric_boundary_nonequidistribution
#print axioms GMZP0.original_coset_range_right_translate
#print axioms GMZP0.original_coset_range_representative
#print axioms GMZP0.original_coset_infDist_first_translate
#print axioms GMZP0.original_coset_infDist_second_translate
#print axioms GMZP0.original_coset_infDist_self
#print axioms GMZP0.original_coset_infDist_symm
#print axioms GMZP0.original_coset_infDist_triangle
#print axioms GMZP0.original_coset_range_closed
#print axioms GMZP0.original_coset_infDist_zero_implies_eq
#print axioms GMZP0.original_coset_infDist_respects
#print axioms GMZP0.original_quotient_distance_mk
#print axioms GMZP0.original_raw_coset_metric_topology
#print axioms GMZP0.original_coset_metric_formula
#print axioms GMZP0.original_coset_metric_topology
#print axioms GMZP0.original_coset_metric_mk_lipschitz
#print axioms GMZP0.observation_integer_functions_closed_by_values
#print axioms GMZP0.observation_lattice_closed_by_values
#print axioms GMZP0.original_observation_cutoff_from_isometric_actions
#print axioms GMZP0.cubic_coordinate_translation_not_isometry
#print axioms GMZP0.identity_metric_peak_bounds
#print axioms GMZP0.identity_metric_peak_eq_one
#print axioms GMZP0.identity_metric_peak_lipschitz
#print axioms GMZP0.right_regular_peak_injective
#print axioms GMZP0.right_regular_peak_dist_le_one
#print axioms GMZP0.right_regular_peak_dist_right
#print axioms GMZP0.right_regular_peak_relative_lower
#print axioms GMZP0.right_regular_raw_metric_isometry
#print axioms GMZP0.right_regular_peak_compact_upper
#print axioms GMZP0.right_regular_peak_relative_small
#print axioms GMZP0.right_regular_peak_compact_lower
#print axioms GMZP0.right_regular_peak_locally_lipschitz
#print axioms GMZP0.right_regular_peak_local_inverse
#print axioms GMZP0.right_regular_original_to_raw_locally_lipschitz
#print axioms GMZP0.right_regular_raw_to_original_locally_lipschitz
#print axioms GMZP0.right_regular_raw_topology
#print axioms GMZP0.compatible_right_metric_topology
#print axioms GMZP0.compatible_right_metric_isometry
#print axioms GMZP0.compatible_right_metric_local_comparison
#print axioms GMZP0.coordinate_polynomial_contDiff
#print axioms GMZP0.joint_coordinate_polynomials_locally_lipschitz
#print axioms GMZP0.original_coordinate_metric_isometry
#print axioms GMZP0.original_coordinate_metric_proper
#print axioms GMZP0.polynomial_coordinate_multiplication_locally_lipschitz
#print axioms GMZP0.polynomial_group_right_metric
#print axioms GMZP0.right_regular_real_global_comparison_obstruction
#print axioms GMZP0.polynomial_group_and_coset_metrics
#print axioms GMZP0.observation_coefficients_from_finite_values
#print axioms GMZP0.observation_full_coordinates_base
#print axioms GMZP0.observation_full_coordinates_fiber
#print axioms GMZP0.observation_basis_polynomials_continuous
#print axioms GMZP0.observation_base_product_polynomial_eval
#print axioms GMZP0.observation_translated_value_polynomial_eval
#print axioms GMZP0.observation_group_joint_polynomial_presentation
#print axioms GMZP0.finite_coordinate_restriction_lipschitz
#print axioms GMZP0.original_observation_source_metrics
#print axioms GMZP0.original_polynomial_boundary_nonequidistribution
#print axioms GMZP0.rational_polynomial_eval_cast
#print axioms GMZP0.observation_rational_recovery_of_values
#print axioms GMZP0.observation_rational_recovery_on_integer_points
#print axioms GMZP0.rational_translated_basis_polynomial_eval
#print axioms GMZP0.observation_rational_translation_matrix
#print axioms GMZP0.observation_rational_difference_matrix
#print axioms GMZP0.observation_difference_rational_from_base_law
#print axioms GMZP0.rational_observation_product_polynomial_eval
#print axioms GMZP0.observation_group_rational_polynomial_presentation
#print axioms GMZP0.observation_integer_coordinates_rational
#print axioms GMZP0.observation_integer_rational_polynomial
#print axioms GMZP0.observation_compatible_rational_bases
#print axioms GMZP0.rational_polynomial_real_map_eval
#print axioms GMZP0.original_rational_boundary_nonequidistribution
#print axioms GMZP0.rational_scalar_recovery_denominator
#print axioms GMZP0.rational_scalar_recovery_no_uniform_height
#print axioms GMZP0.observation_compatible_basis_integer_coordinates
#print axioms GMZP0.observation_lattice_full_integer_coordinates
#print axioms GMZP0.observation_rational_group_full_lattice_presentation
#print axioms GMZP0.rational_triangular_inverse_polynomial_eval
#print axioms GMZP0.original_group_rational_inverse_polynomials
#print axioms GMZP0.rational_observation_inverse_polynomial_eval
#print axioms GMZP0.observation_group_rational_inverse_presentation
#print axioms GMZP0.observation_rational_operations_full_lattice
#print axioms GMZP0.rational_polynomial_scaled_integer_increment
#print axioms GMZP0.rational_polynomial_scaled_integer_values
#print axioms GMZP0.rational_polynomial_array_integer_multiple
#print axioms GMZP0.rational_polynomial_array_scaled_integer_values
#print axioms GMZP0.rational_coordinate_integer_image_sandwich
#print axioms GMZP0.original_logarithmic_lattice_sandwich
#print axioms GMZP0.rational_affine_origin_obstruction
#print axioms GMZP0.rational_triangular_lattice_image_not_additive
#print axioms GMZP0.rational_coordinate_polynomial_contDiff
#print axioms GMZP0.rational_coordinate_lie_group
#print axioms GMZP0.coordinate_group_contractible
#print axioms GMZP0.original_observation_coordinate_lie_group
