import Mathlib.Algebra.Lie.Nilpotent
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.Data.Real.Basic

/-! Actual Lie-ideal brackets are generated by brackets of a fixed
basis with a spanning family. No replacement bracket is introduced. -/
noncomputable section
open Module
namespace GMZP0
variable {L iota : Type*} [LieRing L] [LieAlgebra ℝ L] [Fintype iota]

/-- Bracketing any original vector with a vector in a given linear span
lies in the span of the corresponding original basis brackets. -/
theorem lie_basis_bracket_mem_span (b : Basis iota ℝ L) (S : Set L)
    (x y : L) (hy : y ∈ Submodule.span ℝ S) :
    ⁅x, y⁆ ∈ Submodule.span ℝ {z | ∃ i, ∃ v ∈ S, z = ⁅b i, v⁆} := by
  let U := Submodule.span ℝ {z | ∃ i, ∃ v ∈ S, z = ⁅b i, v⁆}
  induction hy using Submodule.span_induction with
  | mem y hy =>
    rw [← b.sum_repr x, sum_lie]
    apply U.sum_mem
    intro i _
    rw [smul_lie]
    exact U.smul_mem _ (Submodule.subset_span ⟨i, y, hy, rfl⟩)
  | zero => simpa only [lie_zero] using U.zero_mem
  | add y z hy hz hiy hiz =>
    rw [lie_add]
    exact U.add_mem hiy hiz
  | smul a y hy hiy =>
    rw [lie_smul]
    exact U.smul_mem a hiy

/-- An actual lower-central step equals the real span of basis brackets
with any spanning set of the original Lie ideal. -/
theorem lie_ideal_basis_bracket_span (b : Basis iota ℝ L) (N : LieIdeal ℝ L)
    (S : Set L) (hN : N.toSubmodule = Submodule.span ℝ S) :
    (⁅(⊤ : LieIdeal ℝ L), N⁆ : LieIdeal ℝ L).toSubmodule =
      Submodule.span ℝ {z | ∃ i, ∃ v ∈ S, z = ⁅b i, v⁆} := by
  apply le_antisymm
  · rw [LieSubmodule.lieIdeal_oper_eq_linear_span']
    apply Submodule.span_le.mpr
    rintro z ⟨x, hx, y, hy, rfl⟩
    apply lie_basis_bracket_mem_span b S x y
    rw [← hN]
    exact hy
  · apply Submodule.span_le.mpr
    rintro z ⟨i, y, hy, rfl⟩
    apply LieSubmodule.lie_mem_lie (LieSubmodule.mem_top (b i))
    change y ∈ N.toSubmodule
    rw [hN]
    exact Submodule.subset_span hy

end GMZP0
