import GMZP0.ObservationModule
import GMZP0.PolynomialValueSpan
import Mathlib.LinearAlgebra.Basis.Defs

/-! The actual difference space is generated by the rational coefficient
vectors of a polynomial translation presentation. Coordinate surjectivity
is explicit: restricted parameter values alone cannot recover coefficients. -/
noncomputable section
open Module
namespace GMZP0
variable {G sigma iota : Type*} [Group G] [Fintype iota]

/-- A vector with rational coordinates in the supplied actual real basis. -/
def rationalBasisVector {E : Type*} [AddCommGroup E] [Module ℝ E]
    (b : Basis iota ℝ E) (q : iota → ℚ) : E := ∑ i, (q i : ℝ) • b i

/-- Rationality means a finite real span of actual vectors with rational basis coordinates. -/
def RationalInBasis {E : Type*} [AddCommGroup E] [Module ℝ E]
    (b : Basis iota ℝ E) (U : Submodule ℝ E) : Prop :=
  ∃ S : Finset (iota → ℚ), U = Submodule.span ℝ (rationalBasisVector b '' (S : Set (iota → ℚ)))

/-- The displayed rational vector really has the specified rational coordinates. -/
theorem rationalBasisVector_repr {E : Type*} [AddCommGroup E] [Module ℝ E]
    (b : Basis iota ℝ E) (q : iota → ℚ) (i : iota) :
    b.repr (rationalBasisVector b q) i = (q i : ℝ) := by
  classical
  simp [rationalBasisVector, Finsupp.single_apply]

/-- Basis differences generate every actual function difference by exact real linearity. -/
theorem observation_difference_mem_of_basis (V : ObservationModule G) (b : Basis iota ℝ V.space)
    (U : Submodule ℝ V.space)
    (hb : ∀ g j, observationTranslate V g (b j) - b j ∈ U) (g : G) (P : V.space) :
    observationTranslate V g P - P ∈ U := by
  have he : observationTranslate V g P - P =
      ∑ j, b.repr P j • (observationTranslate V g (b j) - b j) := by
    calc
      _ = (observationTranslate V g - (LinearMap.id : V.space →ₗ[ℝ] V.space))
          (∑ j, b.repr P j • b j) := by
        rw [b.sum_repr]
        rfl
      _ = _ := by simp only [map_sum, map_smul, LinearMap.sub_apply, LinearMap.id_apply]
  rw [he]
  exact U.sum_mem fun j _ => U.smul_mem _ (hb g j)

omit [Fintype iota] in
/-- All real coefficient vectors belong to W when the presentation holds on every real coordinate. -/
theorem observation_polynomial_coefficient_mem (V : ObservationModule G)
    (b : Basis iota ℝ V.space) (coord : G → sigma → ℝ) (hcoord : Function.Surjective coord)
    (S : Finset (sigma →₀ ℕ)) (v : iota → (sigma →₀ ℕ) → V.space)
    (htranslate : ∀ g j, observationTranslate V g (b j) - b j = vectorPolynomialValue S (v j) (coord g))
    (j : iota) (d : sigma →₀ ℕ) (hd : d ∈ S) : v j d ∈ observationDifferenceSpace V := by
  apply vectorPolynomial_coefficient_mem S (v j) _ _ d hd
  intro x
  obtain ⟨g, rfl⟩ := hcoord x
  rw [← htranslate]
  exact observation_difference_mem V g (b j)

/-- The exact real difference span equals the coefficient-vector span of the actual translation matrices. -/
theorem observation_difference_eq_coefficient_span (V : ObservationModule G)
    (b : Basis iota ℝ V.space) (coord : G → sigma → ℝ) (hcoord : Function.Surjective coord)
    (S : Finset (sigma →₀ ℕ)) (v : iota → (sigma →₀ ℕ) → V.space)
    (htranslate : ∀ g j, observationTranslate V g (b j) - b j = vectorPolynomialValue S (v j) (coord g)) :
    observationDifferenceSpace V =
      Submodule.span ℝ {P | ∃ j d, d ∈ S ∧ P = v j d} := by
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro P ⟨g, Q, rfl⟩
    apply observation_difference_mem_of_basis V b
    intro h j
    rw [htranslate]
    apply Submodule.sum_mem
    intro d hd
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨j, d, hd, rfl⟩)
  · apply Submodule.span_le.mpr
    rintro P ⟨j, d, hd, rfl⟩
    exact observation_polynomial_coefficient_mem V b coord hcoord S v htranslate j d hd

/-- The finite rational generator list is chosen from the fixed coefficient array. -/
def observationRationalGenerators (S : Finset (sigma →₀ ℕ))
    (A : iota → (sigma →₀ ℕ) → iota → ℚ) : Finset (iota → ℚ) := by
  classical
  exact (Finset.univ.product S).image (fun jd => A jd.1 jd.2)

/-- The generator-list size is bounded before the translating group element or observation is chosen. -/
theorem observationRationalGenerators_card (S : Finset (sigma →₀ ℕ))
    (A : iota → (sigma →₀ ℕ) → iota → ℚ) :
    (observationRationalGenerators S A).card ≤ Fintype.card iota * S.card := by
  classical
  exact Finset.card_image_le.trans (by simp)

/-- Every listed rational vector is precisely a coefficient vector of the actual presentation. -/
theorem observationRationalGenerators_image (V : ObservationModule G) (b : Basis iota ℝ V.space)
    (S : Finset (sigma →₀ ℕ)) (A : iota → (sigma →₀ ℕ) → iota → ℚ) :
    rationalBasisVector b '' (observationRationalGenerators S A : Set (iota → ℚ)) =
      {P | ∃ j d, d ∈ S ∧ P = rationalBasisVector b (A j d)} := by
  classical
  ext P
  simp only [Set.mem_image, Finset.mem_coe, observationRationalGenerators, Finset.mem_image,
    Set.mem_ofPred_eq]
  constructor
  · rintro ⟨q, ⟨⟨j, d⟩, hd, rfl⟩, rfl⟩
    exact ⟨j, d, (Finset.mem_product.mp hd).2, rfl⟩
  · rintro ⟨j, d, hd, rfl⟩
    exact ⟨A j d, ⟨(j, d), Finset.mem_product.mpr ⟨Finset.mem_univ _, hd⟩, rfl⟩, rfl⟩

/-- Actual rational polynomial translation coefficients prove rationality of W in the given basis. -/
theorem observation_difference_rational_of_polynomial (V : ObservationModule G)
    (b : Basis iota ℝ V.space) (coord : G → sigma → ℝ) (hcoord : Function.Surjective coord)
    (S : Finset (sigma →₀ ℕ)) (A : iota → (sigma →₀ ℕ) → iota → ℚ)
    (htranslate : ∀ g j, observationTranslate V g (b j) - b j =
      vectorPolynomialValue S (fun d => rationalBasisVector b (A j d)) (coord g)) :
    RationalInBasis b (observationDifferenceSpace V) := by
  refine ⟨observationRationalGenerators S A, ?_⟩
  rw [observationRationalGenerators_image]
  exact observation_difference_eq_coefficient_span V b coord hcoord S _ htranslate

end GMZP0
