import GMZP0.PhaseAlgebra
import GMZP0.Definitions
import GMZP0.Response
import GMZP0.FiniteSelection
import GMZP0.CaptureToP0
import GMZP0.CubicMetric
import GMZP0.PhaseScale
import GMZP0.CircleRoots
import GMZP0.RealGrid
import GMZP0.MajorArcGrid
import GMZP0.WeightedEnergy
import GMZP0.FiniteOperator
import GMZP0.TerminalCapture
import GMZP0.ParabolaGeometry
import GMZP0.FiniteAdjoint
import GMZP0.WeightedAdjoint
import GMZP0.DiagonalEnergy
import GMZP0.OriginalWeights
import GMZP0.HorizontalBlocks
import GMZP0.SecondAdjoint
import GMZP0.BlockCollisions
import GMZP0.BlockRowEnergy
import GMZP0.GramEnergy
import GMZP0.SecondStatistic
import GMZP0.SafeWindowGeometry
import GMZP0.VerticalStrips
import GMZP0.HorizontalPartition
import GMZP0.UniformSafeWindow
import GMZP0.PositiveSafeStatistic
import GMZP0.CircleCharacter
import GMZP0.LagGeometry
import GMZP0.DoubleKernelPhase
import GMZP0.BlockTargets
import GMZP0.SingleBlockFormula
import GMZP0.IntegerBlockFormula
import GMZP0.LagSources
import GMZP0.DoubleBlockFormula
import GMZP0.LagReindexing
import GMZP0.OriginalFieldExtension
import GMZP0.LagStatistic
import GMZP0.PositiveLagStatistic
import GMZP0.Rerooting
import GMZP0.ZeroLag
import GMZP0.ZeroLagBounds
import GMZP0.RerootedPhase
import GMZP0.RerootedStatistic
import GMZP0.RerootedBounds
import GMZP0.RerootedAverage
import GMZP0.CyclicOriginalFields
import GMZP0.CyclicLag
import GMZP0.HorizontalShiftReindexing
import GMZP0.CyclicNormalization
import GMZP0.CyclicBounds
import GMZP0.PositiveCyclicAverage
import GMZP0.CyclicSampling
import GMZP0.PrimeCyclicModulus
import GMZP0.IntervalTranslation
import GMZP0.FiniteAverages
import GMZP0.FourShiftSmoothing
import GMZP0.CyclicSmoothing
import GMZP0.PositiveSmoothedAverage
import GMZP0.CubicFaces
import GMZP0.MeanAlgebra
import GMZP0.BoxCauchyStep
import GMZP0.BoxFaces
import GMZP0.BoxMoment
import GMZP0.BoxNorm
import GMZP0.CyclicBoxNorm
import GMZP0.FullLagAverage
import GMZP0.PositiveBoxAverage
import GMZP0.UniformBoxAverage
import GMZP0.CubeConjugation
import GMZP0.CubeExpansion
import GMZP0.CubePhaseAlgebra
import GMZP0.CyclicCubeExpansion
import GMZP0.CyclicCubeReroot
import GMZP0.CyclicCubePhase
import GMZP0.UniformCubeAverage
import GMZP0.CyclicCubeTime
import GMZP0.OriginalCubeVertices
import GMZP0.UniformWeightedTimeAverage
import GMZP0.LinearWeyl
import GMZP0.WeylDifferencing
import GMZP0.WeylLargeCorrelations
import GMZP0.IntervalWeyl
import GMZP0.PolynomialDifferencing
import GMZP0.AffineReturnSeed
import GMZP0.ReturnFiber
import GMZP0.AffineReturnAmplification
import GMZP0.UniformAffineReturns
import GMZP0.QuadraticWeyl
import GMZP0.IntervalRescaling
import GMZP0.QuadraticIntervalWeyl
import GMZP0.DenominatorFiber
import GMZP0.CubicWeylReturns
import GMZP0.CubicWeyl
import GMZP0.CubicCommonDenominator
import GMZP0.OriginalCubeWeyl
import GMZP0.WeightedCubeWeyl
import GMZP0.UniformOriginalCubeCapture

import GMZP0.CollisionObstruction
import GMZP0.CoordinateMean
import GMZP0.CubeCollision
import GMZP0.CubeLagRemoval
import GMZP0.CubeSignSymmetry
import GMZP0.FiniteUnionMean
import GMZP0.FlatCubeCoordinates
import GMZP0.PairCollision
import GMZP0.PositiveCubeAverage
import GMZP0.ShiftResidues
import GMZP0.SignedShiftMean
import GMZP0.UniformCollisionScale
import GMZP0.UniformDistinctCubeCapture
import GMZP0.UniformPositiveCubeCapture
import GMZP0.WeightedCollisionRemoval

import GMZP0.CubeLiftCorrection
import GMZP0.CubeRounding
import GMZP0.CubeSignCounts
import GMZP0.CyclicGlobalLift
import GMZP0.CyclicLiftProbability
import GMZP0.CyclicLiftValues
import GMZP0.GlobalChoiceObstruction
import GMZP0.GlobalFiniteChoice
import GMZP0.IndependentAssignments
import GMZP0.LiftChoices
import GMZP0.LiftGridScale
import GMZP0.LiftRounding
import GMZP0.UniformOriginalRealLift

import GMZP0.FiniteCharacterOrthogonality
import GMZP0.RealCubeGrid
import GMZP0.FrequencyMesh
import GMZP0.FrequencyAliasing
import GMZP0.LocalCubeNorm
import GMZP0.WeightedFrequencyCube
import GMZP0.CyclicLocalCube
import GMZP0.CyclicFrequencyAverage
import GMZP0.UniformOriginalLocalFour
import GMZP0.LocalGoodFibers
import GMZP0.UniformOriginalLocalFibers

import GMZP0.FiniteFourier
import GMZP0.FiniteFourierEnergy
import GMZP0.DifferenceFourier
import GMZP0.PositiveFourierMixture
import GMZP0.FourierCubeExpansion
import GMZP0.ParameterDensity
import GMZP0.ParameterEnergy
import GMZP0.DifferenceDensity
import GMZP0.BoundedBoxFaces
import GMZP0.ProductPushforward
import GMZP0.AdditiveCube
import GMZP0.LocalCubeDifference
import GMZP0.LocalFourierBound
import GMZP0.DensityNormalization
import GMZP0.GlobalCube

import GMZP0.FiniteEnergyPermutation



import GMZP0.CubeDerivative
import GMZP0.FiniteCrossCorrelation
import GMZP0.TwistedCube
import GMZP0.LocalGlobalComparison
import GMZP0.TwistObstructions
import GMZP0.GlobalFrequencyAverage
import GMZP0.PairGeometry
import GMZP0.PairScale
import GMZP0.PairRepresentations
import GMZP0.PairDensity
import GMZP0.ExceptionalPairs
import GMZP0.PairSeventhMoment
import GMZP0.ConcatenationInterface
import GMZP0.UniformOriginalRealSeven
import GMZP0.GlobalCubeCollision
import GMZP0.GlobalCubeThreshold
import GMZP0.PreparedSevenFibers
import GMZP0.OriginalFiberRetention
import GMZP0.UniformPreparedSeven
import GMZP0.FiniteSchur
import GMZP0.BlockSchur
import GMZP0.FewLargeBlocks
import GMZP0.OriginalBlockSchur
import GMZP0.OperatorStability
import GMZP0.AssignedOperator
import GMZP0.FiniteEnergyTriangle
import GMZP0.MajorArcStability
import GMZP0.FreezingStep
import GMZP0.WideVertical
import GMZP0.WideBlock
import GMZP0.WideGram
import GMZP0.WideLagBounds
import GMZP0.LargeBlockLags
import GMZP0.CubicIntervalWeyl
import GMZP0.AffineBlockPhase
import GMZP0.PowerAffineReturns
import GMZP0.AffineBlockRelations
import GMZP0.AffineTopRelation
import GMZP0.AffineNoRelation
import GMZP0.CircleGrid
import GMZP0.AffineChildren
import GMZP0.AffineFreezing
import GMZP0.FourierTranslation
import GMZP0.CyclicInput
import GMZP0.ConstantFourier
import GMZP0.HorizontalCubicKernel
import GMZP0.ConstantGramPhase
import GMZP0.HorizontalSchur
import GMZP0.ConstantFreezing
import GMZP0.OrdinaryPolynomialAlgebra
import GMZP0.OrdinaryProfiles
import GMZP0.OrdinaryBlockRelations
import GMZP0.OrdinaryChildren
import GMZP0.MonomialReturnInterface
import GMZP0.OrdinaryTopRelation
import GMZP0.OrdinaryFreezing
import GMZP0.MonomialInterpolation
import GMZP0.MonomialSeed
import GMZP0.MonomialAmplification
import GMZP0.MonomialReturns
import GMZP0.ObservationModule
import GMZP0.ObservationGroup
import GMZP0.ObservationQuotient
import GMZP0.ObservationPhase
import GMZP0.ObservationFlag
import GMZP0.ObservationObstruction
import GMZP0.WeightedPolynomial
import GMZP0.WeightedSubstitution
import GMZP0.CoordinateObservation
import GMZP0.ObservationProper
import GMZP0.TriangularCoordinates
import GMZP0.TriangularObstruction
import GMZP0.ObservationCommutator
import GMZP0.ObservationNilpotent
import GMZP0.ObservationCharacters
import GMZP0.ObservationCommutatorObstruction
import GMZP0.ObservationContinuousCharacters

/-! Components of the P0 manuscript. This is not yet a proof of P0. -/
