name = "GMZP0"
version = "0.1.0"
defaultTargets = ["GMZP0"]

[[lean_lib]]
name = "GMZP0"

[[require]]
name = "mathlib"
path = "vendor/mathlib4-4.33.0"

[[require]]
name = "plausible"
path = "vendor/plausible"

[[require]]
name = "LeanSearchClient"
path = "vendor/LeanSearchClient"

[[require]]
name = "importGraph"
path = "vendor/importGraph"

[[require]]
name = "proofwidgets"
path = "vendor/proofwidgets"

[[require]]
name = "aesop"
path = "vendor/aesop"

[[require]]
name = "Qq"
path = "vendor/Qq"

[[require]]
name = "batteries"
path = "vendor/batteries"

[[require]]
name = "Cli"
path = "vendor/Cli"
