"""Build actual proofs, then audit every project theorem's transitive axioms."""
from pathlib import Path
import json
import re
import shutil
import subprocess
import sys

sys.stdout.reconfigure(encoding='utf-8')

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'verification'
OUT.mkdir(exist_ok=True)
lake = shutil.which('lake')
if not lake:
    raise SystemExit('Lake is unavailable')

def run(args, filename):
    result = subprocess.run([lake, *args], cwd=ROOT, capture_output=True,
                            encoding='utf-8', errors='replace')
    output = result.stdout + result.stderr
    (OUT / filename).write_text(output, encoding='utf-8')
    if result.returncode:
        print(output)
        raise SystemExit(result.returncode)
    return output

run(['build', 'GMZP0', 'GMZP0.Audit'], 'build.log')
output = run(['env', 'lean', 'GMZP0/Audit.lean'], 'axioms.log')

def without_comments(source):
    """Remove line and nested block comments before the complementary lexical guard."""
    out, i, depth = [], 0, 0
    while i < len(source):
        if source.startswith('/-', i):
            depth += 1
            out.append(' ')
            i += 2
        elif depth and source.startswith('-/', i):
            depth -= 1
            out.append(' ')
            i += 2
        elif depth:
            out.append('\n' if source[i] == '\n' else ' ')
            i += 1
        elif source.startswith('--', i):
            end = source.find('\n', i)
            i = len(source) if end < 0 else end
        else:
            out.append(source[i])
            i += 1
    if depth:
        raise SystemExit('Unclosed Lean block comment')
    return ''.join(out)

theorems = set()
for path in (ROOT / 'GMZP0').glob('*.lean'):
    source = without_comments(path.read_text(encoding='utf-8'))
    for name in re.findall(r'\btheorem\s+(\w+)', source):
        theorems.add('GMZP0.' + name)
    # This lexical guard complements, and does not replace, the kernel axiom report.
    if re.search(r'\b(?:sorry|admit|axiom)\b', source):
        raise SystemExit(f'Unproved placeholder or axiom declaration in {path.name}')
reports = re.findall(r"'(GMZP0\.\w+)' depends on axioms: \[([^\]]*)\]", output)
allowed = {'propext', 'Classical.choice', 'Quot.sound'}
audit = {}
for name, values in reports:
    axioms = {v.strip() for v in values.split(',') if v.strip()}
    if not axioms <= allowed:
        raise SystemExit(f'Unexpected axiom dependency: {name}: {axioms - allowed}')
    audit[name] = sorted(axioms)
if set(audit) != theorems:
    raise SystemExit(f'Incomplete audit: missing={theorems - set(audit)}; extra={set(audit) - theorems}')
result = dict(build='passed', checked_theorems=len(audit), transitive_axioms=audit,
              main_P0='NOT_proved', weighted_capture='NOT_proved',
              rational_original_coefficient_recovery='checked at F53: the literal original rational basis and complete original integer coordinate grid yield at most dim(V) actual subgroup points and one rational recovery matrix, before all original real observations; rational basis evaluations and finite-dimensional separation prove a rational left inverse, whose real extension recovers every unrestricted original coefficient exactly',
              rational_original_translation_and_group='checked at F53: the original rational joint base law and actual polynomial basis derive the rational polynomial translation and difference matrices, rationality of the actual W, and a rational joint multiplication law on the original H with unchanged pullback order; these matrices and H laws are conclusions, not presentation fields',
              rational_integer_basis_and_full_lattice='checked at F53: every actual integer-valued observation has rational coordinates in the original basis and an actual rational polynomial representative; the full original integer lattice therefore has compatible integer/real bases retaining rational polynomial representatives; a combined theorem derives the rational H multiplication law and exact full-lattice integer grid in these same constructed coordinates, without replacing the original lattice by a sublattice',
              rational_original_full_orbit='checked conditionally at F53: the original rational basis, rational joint base law, strictly triangular base presentation and full integer grid construct the compatible integer/real bases inside the full original orbit theorem; source/quotient metrics and cutoff geometry are derived, preserving the original section, response, every index point and N denominator; rational heights, Lie/Malcev and external quantitative matching, descents and termination, original-frequency realization and final WeightedCapture/P0 remain open',
              rational_recovery_height_obstruction='checked at F53: for each positive integer n, any rational scalar a with a*n=1 has reduced denominator n; thus even one-dimensional constant-polynomial recovery has no denominator bound uniform over unrestricted structural coefficients; this excludes inferring uniform heights merely from rationality or fixed dimension/degree and is not a counterexample to P0',
              original_observation_joint_polynomials='checked at F52: finite-dimensional separation on the entire original group gives finitely many actual evaluation points and one real matrix recovering every original basis coefficient; the original base joint polynomial law and original basis polynomials therefore derive the actual H joint polynomial law for (g,P)*(h,Q)=(g*h,P composed with L_h + Q), with unrestricted real observation coefficients; no H polynomial law or evaluation frame is supplied, and no uniform rational height bound is claimed',
              original_observation_source_metrics='checked at F52: the original base coordinate homeomorphism, literal joint polynomial law and actual polynomial basis functions construct both G and H metrics with exact original topologies and every right translation isometric; actual G coordinates and inverse and actual H base/fiber maps are locally Lipschitz, without supplied metric or regularity assumptions',
              original_polynomial_full_orbit='checked conditionally at F52: original joint and strictly triangular base coordinate laws, full integer grid, compatible actual integer/real observation bases and polynomial basis functions construct source and quotient metrics and all geometric inputs inside the full original boundary forcing theorem; the H quotient metric precedes every section in the fixed cell, invariant probabilities, threshold, full finite orbit and N; one t and alpha precede all orbits and N, retaining the original N denominator and every point under card(I)<=N; uniform rational heights, external metric/test/filtration/interval-smoothness matching, general descents and termination, original-frequency realization and final WeightedCapture/P0 remain open',
              constructed_right_invariant_source_metric='checked at F51: the full original translate family of the fixed identity peak max(0,1-d0(x,1)) embeds the original group into bounded continuous functions; its induced metric is right-invariant and bounded by one; proper initial coordinate metric and locally Lipschitz multiplication give two-sided compact-set comparison and locally Lipschitz identities in both directions, proving exact original topology without assuming right invariance or coordinate comparison',
              polynomial_source_and_coset_metrics='checked at F51: a finite-dimensional original coordinate homeomorphism and literal joint polynomial group multiplication construct the proper initial coordinate metric and prove local Lipschitz multiplication; the right-invariant replacement has exactly the original topology and locally Lipschitz coordinates and inverse; with the original discrete lattice and actual compact cover, the genuine original coset metric and infimum formula are constructed as well, without normality; instantiating the exact semidirect observation group H joint coordinate law and base/fiber maps and matching the permitted external theorem quantitative metric remain open',
              bounded_right_metric_obstruction='checked at F51: the constructed distance is at most one everywhere; even for the actual additive real group there is no finite global constant bounding the unbounded original coordinate by this distance, as witnessed by x=L+1 for each proposed nonnegative L; the proved comparison is local or on fixed compact sets, not globally bi-Lipschitz; this is not a P0 counterexample',
              constructed_original_coset_metric='checked at F50: isometric actual right lattice translations make the one-sided original coset infimum representative-independent, symmetric and triangular, without normality or nearest-point attainment; closedness of the original lattice separates zero-distance cosets and constructs a genuine metric; an actual compact original cover identifies its topology exactly with the original quotient topology; the compatible metric retains the literal infimum formula and makes the original quotient map 1-Lipschitz',
              original_observation_lattice_closed='checked at F50 directly from all original integer evaluation conditions: the original integer-valued function subgroup is closed in its pointwise topology, without a discreteness or finite-test premise; with the closed original base lattice, the actual observation lattice is closed in the original product topology',
              cutoff_with_constructed_quotient_metrics='checked conditionally at F50: the actual G and H quotient metrics and their exact topology and distance formulas are constructed inside the original cutoff theorem, using source right lattice isometries, compatible H topology and original compact cells; this supplies the global H-to-G projection constant and C/t bound for the unchanged original observation; source metrics, their isometric actions and local coordinate regularity still need construction and matching from the complete original Malcev/Lie data, as do uniform heights and external quantitative theorem compatibility',
              right_isometry_obstruction='checked exact obstruction at F50: the real metric pulled back by x cubed is a genuine metric, but translation by the integer 1 changes the distance of 0 and 1 from 1 to 7; isometric right lattice action cannot be inferred for an arbitrary coordinate metric; this is not a counterexample to P0',
              compact_original_metric_lifts='checked at F49: the actual compact original cover and literal coset-distance formula imply compactness and exact original quotient topology for the supplied quotient metric; a compact thickening and one radius precede all nearby quotient pairs, whose actual representatives have distance at most twice their quotient distance; the second is an original lattice translate, without nearest-point attainment; locally Lipschitz actual coordinate maps give uniform base and fiber differences on the compact enlargement',
              constructed_observation_metric_geometry='checked conditionally at F49: explicit equality with H original product topology transports the actual compact base/fiber cell and local compactness; original compatible integer/real bases and literal H coset metric construct controlled original pair lifts; the literal G coset metric and bounded compact quotient extend the local base projection bound to one global constant; short paths and the original C/t cutoff bound are then derived, not supplied; intended metrics, their formulas and local coordinate regularity still need construction from original Malcev/Lie data',
              assembled_original_boundary_forcing='checked conditionally at F49: one theorem derives original cell corrections and section measurability, actual O(t) tube mass, original controlled pair lifts, short paths, uniform projection and cutoff Lipschitz bounds, original probability projection and zero cutoff mean; one t and alpha precede every finite original orbit, every length and every N-normalized orbit with card(I)<=N; no quantitative Leibman conclusion, full Lie metric construction, uniform heights, general descents, termination or final P0 is claimed',
              original_interval_mean_normalization='checked at F49: for all N>0 and complete finite index sets with card(I)<=N, gamma>0 and bounded original values, a sum divided by the original N of norm greater than gamma implies gamma*N<card(I), nonemptiness and full uniform mean of norm greater than gamma; the same orbit discrepancy tolerance is retained; the two-point constant-one example at N=1 disproves this transfer without the cardinality bound; matching the external theorem filtration, tests and original interval smoothness norm remains open',
              original_observation_branches='checked at F48: compact input and original representative sets meet only finitely many actual lattice corrections; the original correction is constant along every connected continuous path avoiding the actual quotient frontier image; a change forces a boundary crossing and gives a metric boundary-distance bound when the projected path radius is controlled; the actual finite basis gives one character-difference bound on all original branches before arbitrary unrestricted observation coefficients',
              original_cutoff_gluing='checked conditionally at F48: uniform compact pair lifts with controlled actual fiber coefficient differences and projected base paths imply a same-branch-or-near-boundary alternative for the unchanged original observation; this proves the actual cutoff product Lipschitz bound B/t for all 0<t<=1 with B fixed before t, without supplying the product bound as a premise; original zero mean and orbit estimates yield fixed scales before all finite orbits and lengths; constructing the intended metrics, original quotient pair lifts and uniform projection bounds remains an internal geometry obligation',
              original_coordinate_short_paths='checked at F48: local Lipschitz regularity of both directions of the actual finite-dimensional coordinate homeomorphism and compactness construct uniformly short base paths by actual coordinate segments; the literal base coset-distance formula and controlled original pair lifts then construct the path component of the pair-chart interface; these metric regularity and pair-lift inputs still need derivation from the full original Malcev/Lie data',
              cutoff_jump_obstruction='checked exact obstruction at F48: the empty-boundary cutoff is constant one and its product with the unit step taking values 1 and -1 is not Lipschitz for any finite constant; cutoff regularity alone cannot regularize an unrelated jump and this is not a counterexample to P0',
              original_quotient_boundary_geometry='checked conditionally at F47: the actual half-open coordinate cell has exactly the original coordinate faces as frontier; every original lattice translate of its frontier avoids its interior; the literal coset-infimum distance formula lifts every strict quotient tube bound to an actual original lattice translate, without assuming nearest points; uniform local coordinate comparison gives the actual coordinate strip cover and the original invariant-probability tube bound (2*m*L+1/r)*t at every positive scale',
              compact_coordinate_metric_constants='checked at F47: local Lipschitz coordinates on the original locally compact metric group and compact cell closure internally supply one L>=0 and r>0 before all cell points and nearby group points; with literal group laws, original integer grid and coset-distance formula, a tube constant C is selected before every specified invariant probability and all positive scales; the intended metric formula and local Lipschitz property still require derivation from original Malcev/Lie data, and no uniform bound across varying structural presentations is asserted',
              coordinate_metric_obstruction='checked exact obstruction at F47: no nonnegative L makes abs(x)<=L*abs(x^3) hold on [0,1]; topological coordinate compatibility alone does not imply the required metric comparison; this is not a counterexample to P0',
              triangular_coordinate_haar='checked at F46: every finite-dimensional measurable strictly prefix-dependent translation preserves actual Euclidean volume, by splitting the last coordinate and applying one-dimensional translation invariance through a skew product; literal lower-coordinate polynomial support supplies the hypotheses; the actual coordinate homeomorphism and actual triangular left-multiplication laws make coordinate volume a Haar measure, with compact-set finiteness and positivity on nonempty open sets proved internally',
              coordinate_quotient_probability='checked at F46: each translated half-open unit coordinate cell has exactly volume one; the actual full integer-grid subgroup and triangular laws give the strict domain, actual quotient compactness and Haar right invariance; restriction of coordinate Haar to that cell and pushforward through the original quotient map is a full-group invariant probability and equals every specified original invariant probability, without assuming coordinate-volume invariance or replacing the original section',
              original_coordinate_boundary='checked at F46: each coordinate face strip has exact positive-part width as volume, their union has volume at most ofReal(2*m*t), and the coordinate face tube inside the original closed unit cell is contained in that cover; every specified original section in the proved strict cell fixes it pointwise, so under every original invariant probability its representatives lie in these strips with mass at most ofReal(2*m*t); full Malcev/Lie presentation, quantitative covering of original quotient-metric tubes by these coordinate strips, uniform projection and original-observation cutoff Lipschitz constants, heights, external Leibman/interval matching, general descents and final P0 remain open',
              triangular_volume_obstruction='checked exact dimension-one obstruction at F46: allowing the correction to cancel its current coordinate collapses all of R to zero and does not preserve Lebesgue volume; the strict earlier-coordinate dependency cannot be dropped and this is not a counterexample to P0',
              metric_boundary_cutoffs='checked at F45: explicit distance majorants and complementary cutoffs lie in [0,1], suppress the closed t-tube, vanish or equal one outside the open 2t-tube, and have Lipschitz constant at most 1/t; empty boundaries are handled exactly; the majorant is integrable for every finite Borel base measure and its integral is bounded by the actual doubled-tube measure, without assuming an O(t) estimate',
              original_boundary_orbits='checked conditionally at F45: all bounded Lipschitz orbit tests, the actual measure-preserving base projection with constant J, and the original cutoff with constant K imply the original observation mean is at most actual doubled-tube measure plus alpha*(2+K+J/t); zero mean and integrability are proved for the actual original observation from its existing invariant-measure and measurable-section hypotheses; the exact fraction of boundary visits is also controlled; given explicit uniform O(t) tube and O(1/t) original cutoff bounds, one t and alpha are chosen before every finite index type, orbit length and orbit; deriving those geometric bounds and metric constants from full Malcev/Lie data, matching external Leibman inputs and original interval normalization, heights, general descents and final P0 remain open',
              null_boundary_orbit_obstruction='checked exact counterexample at F45: normalized Lebesgue measure on [0,1] gives mass zero to {0}, yet every nonempty finite constant-zero orbit has boundary-majorant mean one at every positive scale; small boundary measure alone gives no orbit-visit bound and this is not a counterexample to P0',
              triangular_canonical_cell='checked at F44 for every finite dimension and every fixed translated half-open unit coordinate cell: prefix-dependent corrections have a unique integer reduction, with existence by successive exact floor choices and uniqueness by prefix induction; literal lower-coordinate polynomial support proves the prefix property; the actual triangular group law, injective coordinates and full original integer-grid subgroup image give unique original right lattice corrections; a coordinate homeomorphism gives Borel cells with compact closure and the actual compact quotient; every specified original section in that same cell is pointwise identified and measurable',
              canonical_original_observation='checked at F44: a genuine coordinate homeomorphism supplies base Polish/local compactness, the proved strict cell supplies quotient compactness, and pointwise section identification discharges measurability for the specified original section; the literal rational observation presentation with constants constructs one invariant probability before all specified sections in the proved translated half-open coordinate cell and all bounded measurable base cutoffs, with actual integrability and zero mean; original corrections are locally constant above interior representatives, yielding local continuity of the specified section, original real phase and pullback of the original quotient observation; this does not give quantitative boundary neighborhoods, Lipschitz or orbit estimates, or identify a different chosen fundamental domain with this cell',
              triangular_cell_obstruction='checked exact counterexample at F44: allowing the correction to depend on and cancel the current coordinate makes every integer vector admissible in dimension one, so uniqueness fails; strict lower-coordinate dependence is not omitted',
              quotient_invariant_probability_unique='checked at F43: every two full-group invariant probabilities on the original discrete compact quotient of a locally compact Polish group coincide, without normality; a bounded measurable auxiliary section and counting of the actual Gamma fibers give left-invariant lifts, finite on compact sets by the finite intersection of Gamma with K-inverse times C; restriction to the strict domain recovers each original quotient measure exactly; ambient Haar uniqueness and total mass one identify the lifts and measures',
              observation_base_marginal='checked at F43: the actual H/Gamma_H to G/Gamma projection intertwines the full original actions; the marginal of every full-H invariant measure is full-G invariant, and the projection preserves any specified full-H and full-G invariant probability measures under the original base lattice hypotheses; the literal rational presentation gives the unique observation-quotient probability and its identification with every specified invariant base probability; no canonical section or original observation is replaced, while canonical-section geometry, coordinate-measure invariance where still unproved, quantitative boundary/Lipschitz/orbit estimates, full Malcev/Lie data and heights, general descents and original-frequency realization remain open',
              compact_quotient_probability='checked at F42: a locally compact Polish topological group with a discrete cocompact original subgroup has a full-group invariant probability on its actual possibly nonnormal quotient; inverse strict domains and their right preimages have equal finite positive left Haar mass, forcing ambient right invariance by Haar uniqueness; restriction, pushforward, finite positive total mass and normalization are all proved internally, with no unimodularity or supplied quotient-measure premise',
              observation_global_mean='checked at F42: the literal finite rational polynomial basis, continuous coordinates with full integer-grid Gamma image, and original locally compact Polish discrete/cocompact base hypotheses construct one full-H invariant probability on actual H/Gamma_H; if V contains constants, every specified measurable original section and every bounded measurable base cutoff yield an integrable original cutoff observation with integral zero under that same measure; canonical-section geometric regularity, identification with separately specified canonical quotient/base measures, quantitative boundaries and Lipschitz estimates, full Malcev/Lie data and heights, general descents and original-frequency realization remain open',
              observation_measurable_sections='checked at F41: finitely many local inverse charts construct a measurable section of a surjective local homeomorphism onto a compact target; discrete actual Gamma and compact G/Gamma supply an original measurable section, with the quotient Borel structure derived for Polish G; countable actual Gamma corrections reduce the section into a compact covering set, yielding a strict Borel fundamental domain with compact closure and unique right corrections everywhere',
              observation_original_measurability='checked at F41: for any given measurable original section, actual jointly continuous evaluation makes the original correction phase, quotient observation, base projection and measurable base cutoff measurable; the actual quotient action is measurable from H topological-group structure; the global zero integral now requires the actual invariant finite measure and the specified measurable section and bounded measurable cutoff, without separately assuming action measurability or a.e. strong measurability of the composite',
              observation_quotient_borel='checked at F41: the actual finite-dimensional V and product H are Polish and locally compact under the corresponding base assumptions; discreteness closes the actual lattice and makes the possibly nonnormal quotient Hausdorff with its Borel quotient structure; the literal rational polynomial and integer-grid presentation supplies an actual strict Borel domain in H with compact closure; a global invariant probability measure, specified canonical-section geometric boundary control, quantitative Lipschitz and orbit estimates, full Malcev/Lie data and uniform heights, general descents and original-frequency realization remain open',
              observation_fiber_geometry='checked at F40: the actual additive V/V_Z maps continuously and injectively to H/Gamma_H with image exactly the fiber over the original base coset; the original quotient observation restricts to evaluation at the original section correction; that evaluation is a continuous circle character, surjective when V contains constants',
              observation_fiber_integral='checked at F40: the literal rational polynomial basis and exact integer-grid Gamma image construct a compact Hausdorff original fiber and normalized additive Haar probability measure; every original fiber observation and scalar base cutoff is integrable and has zero Haar mean, by the actual half-constant translation; zero mean is not inferred from the default value of a nonintegrable integral',
              observation_global_cutoff_integral='checked conditionally at F40: the original constant-element action preserves the base projection and gives the exact half-translation sign of the original quotient observation and every base cutoff; a supplied actual invariant finite measure, measurable action, a.e. strongly measurable cutoff observation and pointwise bounded base cutoff imply integrability and global mean zero; construction of the global quotient measure and section measurability, quantitative boundary and Lipschitz estimates remain open',
              observation_zero_mean_obstruction='checked at F40: the actual zero observation module has a singleton compact fiber with normalized Haar probability, integrable constant-one exponential and integral one; nonzero evaluation cannot be omitted from the mean-zero argument; this is not a counterexample to P0',
              observation_cocompactness='checked at F39: compatible actual integer and real bases give a compact closed covering cell and compact V/V_Z; a locally compact topological base group with compact G/Gamma supplies a compact covering set; the actual right lattice reduction first pulls back the original observation by the base correction and then subtracts a genuine element of V_Z, proving compact H/Gamma_H without lattice normality or a global continuous section',
              observation_cocompact_presentation='checked at F39: an actual finite rational polynomial basis, continuous coordinates whose Gamma image is the full integer grid, a locally compact topological base group, discrete Gamma and compact G/Gamma imply topological-group structure of H, discrete Gamma_H and compact H/Gamma_H; integer bases and covering sets are constructed internally; full Malcev/Lie presentation, uniform heights, Haar/boundary analysis, general descents and original-frequency realization remain open',
              observation_integer_quotient='checked at F38: the actual V_Z/(W cap V_Z) embeds injectively into the actual real V/W; the integer quotient is torsion-free, has a finite integer basis when V_Z is finitely generated, and admits an integer-linear section; a direct product decomposition constructs an integer basis adapted to the actual intersection without presupposing one',
              observation_adapted_real_basis='checked at F38: finite actual integer evaluations transfer integer linear independence to real linear independence; any finite integer basis of a full-spanning V_Z becomes a real basis of V with identical vectors and integer coordinates, and its cardinal equals dim(V); rationality of W in an actual rational polynomial basis makes W cap V_Z span W; the literal rational translation matrix and exact coordinate presentation supply compatible adapted integer and real bases',
              observation_quotient_coordinates='checked at F38: the actual right basis coordinates have kernel exactly W, reconstruct every original real observation modulo W, map V_Z onto the full integer coordinate grid, and preserve finite polynomial expansions in the original variable; quantitative basis heights, full Malcev presentation, boundary estimates and general structural descents remain open; F39 proves qualitative cocompactness under its explicit base and rational-presentation hypotheses; the exact quotient Z/2Z obstruction prevents treating arbitrary integer quotients as torsion-free or split',
              observation_integer_lattice='checked at F37: a supplied actual finite real basis represented by rational coordinate polynomials, with the actual subgroup coordinate image equal to the full integer grid, implies DiscreteTopology of the original integer-valued subgroup and real span equal to V; this does not construct the rational presentation, prove a cocompact quotient theorem, or install a normed IsZLattice instance',
              observation_integer_basis='checked at F37: separating actual subgroup evaluations admit a determining family of at most dim(V) points; exact integer evaluation embeds the original integer-valued subgroup into a finite free integer module, and a basis of its actual range gives a finite integer basis; F38 proves qualitative adaptation to W and compatibility with a real basis under the explicit rational presentation, while uniform height bounds remain open',
              observation_finite_dimension='checked at F36: actual uniformly bounded-degree coordinate polynomial representatives put V in a finite-dimensional polynomial-value image; finrank(V) is bounded by the fixed restricted polynomial space, and the actual pointwise topology is the finite-dimensional module topology; W is closed',
              observation_topological_group='checked at F36: finite-dimensional continuous functions have jointly continuous evaluation; actual left translations, right-semidirect multiplication and inverse are jointly continuous; continuous coordinates and the same uniform representative degree bound supply these hypotheses; Lie structure and lattice cocompactness are not inferred',
              observation_rational_difference='checked at F36: every vector polynomial has equal real spans of all real values and actual coefficients; a surjective coordinate map and a literal rational polynomial matrix for actual basis translation differences give a finite rational-coordinate generating list for W, of size at most basis-card times combined-support-card; constructing that rational presentation from full Malcev data remains open',
              polynomial_parameter_obstruction='checked exact example: the nonzero polynomial X vanishes on the restricted coordinate image {0}, so the coefficient-span proof cannot simply discard its parameter-coverage hypothesis; this does not refute a proved determining-grid theorem or P0',
              observation_group_algebra='checked at F33: actual left-translation function module, constructed difference space, right semidirect group laws and inverse, integer-valued subgroup and all right lattice correction terms; F35 additionally proves commutators and nilpotence under explicit flag/triangular hypotheses; F36 proves topological group structure and rational W from explicit coordinate/matrix presentations; F37 proves fiber lattice discreteness and full real span from an actual rational polynomial basis and integer-grid presentation; F39 proves the original group lattice discrete and cocompact under the explicit locally compact base, discrete base lattice and compact base quotient hypotheses; constructing the full rational Malcev presentation remains open',
              observation_commutator='checked at F35: the actual subgroup commutator of H equals the pairs with base in [G,G] and fiber in the real difference span W; arbitrary real multiples are themselves generated by actual base-fiber commutators, with no closure enlargement or abelian-base assumption',
              observation_nilpotence='checked: a nilpotent base of class c and actual lowering flag of height K give lowerCentralSeries(H,c+K)=bottom; triangular coordinates with correction degree D and observation degree R give class(H)<=c+R*(D+1)^m+1, uniformly in coefficients; full rational Malcev presentation and Lie/topological structure remain open',
              observation_actual_characters='checked: every actual real-valued group character decomposes into base and additive fiber restrictions, and the fiber annihilates all of W; in the product topology with the pointwise observation subspace topology, continuity proves real linearity, source-term cancellation and a nontrivial component pair; actual lattice integrality restricts to both components; bounded integer bases and their quantitative bounds remain open',
              observation_commutator_obstruction='checked exact affine-function example over the additive real base: the base-fiber commutator is the nonzero constant-one fiber, so an abelian base does not make H abelian; not a counterexample to P0',
              observation_quotient='checked: fixed unit-modulus observation on the actual coset quotient by a possibly nonnormal subgroup; right lattice multiplication adds an actual integer to the real phase, so its circle value is invariant',
              observation_original_phase='checked: the curve (g, source*1 - A*(F composed with L_g)) gives the exact complete double phase and lag sum, with the same original label set and each original root; the observation-profile response uses the same input and all original labels; existence of a model for arbitrary original theta is not supplied',
              observation_character='checked: linear fiber functionals annihilating the constructed W combine with base characters to give actual group characters; 1 in W removes the source term; F34 constructs the common lowering flag from actual triangular coordinate corrections and bounded-degree polynomial representatives; F35 derives the linear form for actual continuous characters; the full rational Malcev presentation and bounded integer-character bases remain open',
              weighted_polynomial_lowering='checked at F34 for actual multivariate polynomial supports: coordinate corrections of weight strictly below their coordinate weight imply substitution preserves every weighted bound and lowers the actual polynomial difference by one; constants, zero terms and top cancellation are included',
              coordinate_observation_flag='checked: exact evaluation intertwines actual left translation with the proved polynomial substitution; intersecting the image of weighted support spaces with V constructs increasing flag levels with zero bottom and a supplied uniform top; no observation function is replaced by an unrelated polynomial witness',
              triangular_observation_structure='checked: for m triangular coordinates with all correction degrees <=D and actual observation representatives of degree <=R, weights (D+1)^i and flag height R*(D+1)^m+1 are chosen before coefficients and translations; the constructed flag proves 1 in W and W proper for a nonconstant module; matching the complete rational Malcev presentation remains open',
              observation_integer_saturation='checked: the actual additive subgroup W intersect V_Z is saturated inside V_Z, using nonzero-scalar cancellation only in the real vector space; full lattice, rationality, quotient integer bases and circle-root conclusions are not asserted',
              weighted_degree_obstruction='checked exact polynomial identity: X_1 -> X_1+X_0 gives a difference of unchanged ordinary total degree one, while the explicit triangular weights make the difference strictly lower; this refutes the unweighted shortcut, not P0',
              observation_obstruction='checked exact affine-coordinate example: omitting the left pullback changes the circle phase by 1/2; this refutes an algebraic shortcut, not P0 or structural freezing',
              conditional_P0_reduction='checked: WeightedCapture -> P0',
              conditional_terminal_capture='checked: explicit model approximation and finite minor-arc operator estimates imply original-weight finite capture',
              original_first_adjoint='checked: exact finite adjoint, endpoint Gram expansion, I/N same-horizontal block, original-weight energy lower bound and first grouped TT* inequality',
              second_adjoint_statistic='checked with explicit horizontal window X; normalized second diagonal <= mu(D)/N; complete original-label reindexing proves equality to the finite lag-indexed signed statistic at total scale N^(-6)',
              safe_window='checked: M=ceil(64/kappa), c=kappa/(4M), exact interval partition, original mass and supported original targets',
              positive_safe_statistic='checked: constants and scale threshold precede all original data; exact finite and lag statistics are equal and >= 2*zeta > 0, with original responses retained',
              lag_reindexing='checked: single block, full double-label sum, (r1,r2) to (k,r) and t=r+k-h finite-sum bijections; k=0 contribution explicit, nonnegative and <= mu(D)/N; original targets and weights preserved',
              rerooted_average='checked: exact g(k)e(P(k)) factorization, B normalized by N, S_lag+D_lag equals N^(-5) outer weighted sum, |g| and |B| <= 1, uniform positive finite modulus average',
              cyclic_average='checked: original supported field values and B survive cyclic embedding; complete horizontal reindexing has 2N shifts; exact finite modulus average = (2q/N^2) * cyclic modulus average; constants precede N, q and all original data; cyclic mean >= zeta/128, with weights in [0,1] on a 2qN^3-point sample space',
              prime_modulus='checked from Mathlib Bertrand: for every N>0 there is a prime 64N^2<q<128N^2',
              smoothing='checked: interval translation error for all signed shifts and empty intervals; four independent shifts on exactly (2*ell+1)^4 points; N-normalized error <= 8*ell/N <= a/8; the smoothed original weighted mean is >=7*a/8 with all constants preceding N, q and original data',
              cubic_faces='checked: explicit four unit circle-phase factors, each independent of its own coordinate; exact factorization of the actual cyclic smoothed sequence',
              box_cauchy_schwarz='checked for every dimension: coordinate doubling preserves unit face factors and independence; nonnegative recursively defined box moments and exact root-power identity; actual four-shift sequence is bounded by its box norm',
              positive_box_average='checked: weights removed only from a nonnegative box norm; full lag extension costs (2N+1)/N<=3; finite moment Jensen gives average box moment >=(a/4)^16 on 2qN^3(2N+1) outer samples; constants precede N, q and original data, original mass and complete response retained',
              cube_expansion='checked in every dimension: exact complex equality of recursive moment and full Boolean-vertex product with multiplicities and parity conjugation; four-dimensional shift pairs have (2*ell+1)^8 points',
              cube_rerooting='checked: full cyclic average reindexed by Y=y+2hk with explicit inverse; sixteen weights and alternating alignments factored; t-cubic coefficient is minus the signed original frequency sum and independent of k',
              weighted_time_average='checked: full t average separated by an exact finite bijection; all sixteen weights remain in an average >=(a/4)^16 with constants before N, q and original data; each nonzero-weight cube vertex is an actual retained original base point with the original complete response',
              linear_weyl='checked: inverse chord and geometric sums give ||a|| <= 1/(2*rho*N) for every affine phase and every integer interval with original N normalization',
              weyl_differencing='checked: exact whole pair-sum identity, explicit zero shift <=1, at least N*rho^2/4 nonzero signed shifts above rho^2/8 when N*rho^2>=2; exact N=1 obstruction to dropping this threshold',
              polynomial_differences='checked: exact circle-valued quadratic/cubic derivatives on actual overlap intervals; quadratic large shifts satisfy ||2*h*a2|| <= 4/(rho^2*N), without changing N normalization',
              affine_recurrence_seed='checked: explicit pigeonhole cardinality condition gives two nearby actual returns and a nonzero bounded multiple',
              affine_recurrence='checked: bounded actual rounding fibers amplify epsilon to E*epsilon/N when epsilon*N<=C; positive denominator bound, error factor and threshold precede N, a, b, epsilon and the retained set',
              quadratic_weyl='checked at every N>0: uniform bounded positive denominator and N^(-2) leading-coefficient error; actual shorter intervals retain their original N normalization',
              cubic_weyl='checked at every N>0: exact differencing, actual quadratic denominator fiber and affine recurrence give uniform bounded positive denominator and N^(-3) leading-coefficient error',
              common_denominator='checked: factorial of the uniform denominator bound yields one positive denominator fixed before N and all polynomial/original data',
              weighted_cube_capture='checked: actual original cubic time sum has the checked leading coefficient; successful N^(-3) cube coefficients retain original weighted mean >=(a/4)^16/2, all constants before N,q and original data, with original safe mass and complete responses preserved',
              lag_and_sign_reduction='checked: unused k average removed exactly; simultaneous h/shift reflection fixes every actual vertex and preserves all weights; positive-h mean equals the original signed mean',
              cube_collisions='checked: short shift interval embeds, 2h is nonzero for positive labels at the chosen scale, coordinate resampling gives pair probability <=1/(2*ell+1), all 120 unordered pairs give total <=120/(2*ell+1); zero modular step obstruction proved',
              distinct_original_cube_capture='checked: one scale threshold fixed before q and all original data ensures weighted distinct-vertex cube mass >=(a/4)^16/4 for prime q in the original range, while original safe mass and complete responses remain',
              real_lift_rounding='checked: one [0,1) representative, actual nearest integer, eight positive and eight negative signs, S=l*M+r with |l|<=8 and |r|<=9, and one allowed local correction makes the real cube sum exactly zero',
              global_assignment='checked: restriction of the full point-choice product to any injective vertex family is uniform; local success has probability >=57^(-16); finite weighted expectation produces one choice shared by all cubes without independence between cubes',
              simultaneous_real_lift='checked: M_lift=floor(N^3/E)>=9, all point values lie in M_lift^(-1)Z, |F|<=3, zero original weight gives F=0, supported circle error to d*theta is <=19*E/N^3, and original weighted real-zero cube mass is >=(a/4)^16/(4*57^16); all constants precede N,q and original data, original complete responses retained',
              exact_frequency_mesh='checked: all dimensions d<=7, grid differences k/M with |k|<=384M<1024M, complete j/1024 character orthogonality detects exact real zero; integer-frequency and missing-size-bound obstructions are proved',
              local_four_average='checked: generic finite multiset local moments are nonnegative, local norms have the exact 2^s power and are <=1 for bounded fields; the actual weighted mesh average equals the original real-zero four-cube mass with every multiplicity retained',
              original_local_fibres='checked: uniform original-data theorem gives local fourth-norm sixteenth moment >=beta=(a/4)^16/(4*57^16) and proportion >=beta/2 of actual (x,j) fibres with mean_h local norm >=beta/2; one fixed F, prior constants, original safe mass and full responses preserved',
              finite_fourier='checked: probability-normalized coefficients, unnormalized character synthesis, finite inversion and Parseval; difference correlation has coefficients |nu_hat|^2 with sum exactly E nu^2',
              parameter_difference_density='checked: actual parameter multiplicities give density |G|*count/|A| relative to uniform measure; exact weighted pushforward, independent pair differences, full product law, and density L2 <= |G|*K/|A| from representation multiplicity K',
              local_fourier_expansion='checked: local paired-shift moment equals the global additive cube mean weighted by the actual difference density; explicit nonnegative Fourier expansion retains all multiplicities and yields a bound conditional on every character-twisted global cube average',
              local_global_comparison='checked for every s>=2: all character-twisted global cube averages are bounded by the untwisted moment; actual multiset local moment <= C^s times global moment whenever the original uniform density energy <=C; no unproved twist or mixed-CS premise remains; exact norm and positive lower-moment consequences checked; family concatenation remains unproved',
              global_frequency_average='checked for every 1<=s<=7: the complete finite mesh mean of the global s-moment equals the weighted real-zero cube mass of the same F; actual cyclic seventh-moment identity preserves all original weights, without asserting an unproved positive lower bound',
              twisted_cube='checked: exact derivative recurrence, two-dimensional Fourier energy base, translation square-sum estimate and induction; exact one-dimensional nontrivial-character obstruction also checked',
              pair_geometry='checked: actual integer and cyclic multiplicity <=1+2*A^2; exceptional positive-label pairs have proportion <=3/A<=u/4 for A=ceil(12/u); finite reciprocal-square telescoping, short radius and no-wrap retain all multiplicities; uniform density energy <=2^24*(1+2*A^2)/(u^2*a^2)',
              conditional_original_real_seven='checked: CyclicConcatenationInput implies a uniform positive original weighted real-zero seventh-cube mass; constants precede N,q and original f,theta,lam,mu; the same real lift, original safe-window mass and all complete original responses remain; the external input is not proved',
              external_deep_theorem_scope='user instruction 2026-09-12: prioritize core proofs; external deep theorems are explicit hypotheses, not new axioms, and are not counted as proved',
              seven_cube_preparation='checked: threshold deletion costs <=tau; all 8128 unordered seven-vertex pairs cost <=8128/q; exact unweighted count denominator q^8; a uniform collision threshold and chi/512 level yield at least chi*N/4 good horizontal fibres with at least chi*q^8/4 distinct real-zero seven-cubes each, conditional on the existing concatenation input',
              original_fibre_transport='checked: supplied high-weight cyclic subsets are in the actual original box and D; exact preimage counts give original mass >=|H|*cModel*q*tau/N^3, hence >=64*rho*cModel*tau at the original prime scale; supplied matching values retain the circle error to d*theta and the full original response; no structural model existence is asserted',
              bounded_box_faces='checked in every dimension: the face-factor Cauchy-Schwarz estimate allows norm <=1, with independence and all finite means retained; this is not being asserted as a full mixed Gowers inequality',
              density_normalization_obstruction='checked: on ZMod 2 a constant function disproves use of raw probability masses in place of density relative to the uniform mean',
              finite_block_schur='checked: exact adjoint and Gram energy transfer, finite row-column Schur and symmetric block Schur; all original horizontal blocks have norm <=1/N; arbitrary pointwise contractive masks preserve this bound; at most rho*N actual large compressed blocks per retained horizontal row gives squared energy <=(rho+v+1/N)*input energy, hence the square-root operator bound',
              conditional_minor_block_criterion='checked: the actual pointwise minor-arc mask and original full response yield FiniteMinorEstimate from the displayed compressed-block count; positive rho,v and N0 are chosen before N,Q,p for each target s>0; the count remains open for general structural profiles, while the affine no-relation count is now proved separately',
              square_root_obstruction='checked: exact one-dimensional kernel K=1/2 has Gram row sum R=1/4 but its operator norm is greater than R; this refutes omission of the square root, not P0',
              original_operator_stability='checked: every original finite response operator is a contraction; a phase error <=epsilon on all original labels at nonzero masked points gives squared difference energy <=epsilon^2 times the same input energy; supported circle error epsilon/(2*pi*N^3) suffices',
              child_assignment='checked: arbitrary pointwise single-valued assignment splits output energy exactly; individual minor-arc estimates with different child cutoffs give J*t^2 times input energy; t=s/(3*sqrt(J)) gives (s/3)^2; an exact disjoint-output counterexample shows the J energy loss cannot simply be removed',
              major_arc_transfer='checked: Q>=2*Qchild and circle error <=N^(-3) transfer a child major-arc witness to the parent; contrapositively parent minor implies selected child minor; an exact quarter-frequency counterexample shows closeness is necessary; the paper restricts 0<s<=1 and its a0=s/(12*pi) scale is matched exactly',
              conditional_freezing_step='checked: exact no-relation/error/assigned-child output decomposition and finite energy triangle combine s/3, s/12, s/3 within s; for each 0<s<=1 the numerical rho,v,N0 precede N,J,Q,profiles,assignments and actual points, and the displayed compressed-block count plus supplied approximating children and their finite estimates imply the parent FiniteMinorEstimate; structural production and termination are not asserted',
              widened_original_blocks='checked: all original sources, including boundaries, have their complete block labels in a finite vertical input of size 3*N^2; exact zero extension preserves the same input energy and recovers the actual original block; arbitrary pointwise compressed original blocks inherit widened energy bounds; an exact two-term counterexample refutes direct domination of a truncated phase sum by its complete sum',
              phase_based_large_block='checked: complete pair and lag formulas retain the exact four-factor circle phase and N^(-4) normalization; zero lag costs at most N, and a complete-lag envelope gives the widened energy coefficient (N+sum_nonzero M)/N^4; its comparison with actual compressed original blocks uses exact operator compression',
              many_large_block_lags='checked: for every v>0, c=v^2/8 and a positive N0 are fixed before N,full-integer profile,original profile,mask and horizontal points; failure of the actual compressed original v/N block bound yields at least c*N nonzero lags with |k|<N and complete original-normalized phase sums >=c*N, each at its own actual original source root; no root synchronization or structural polynomial property of an arbitrary extension is asserted',
              cubic_interval_weyl='checked from the existing proved cubic Weyl theorem: actual shorter integer intervals and exact lag overlaps retain the original N denominator; one positive common multiplier precedes N, interval endpoints and every cubic coefficient tuple; no external Weyl input is used for this cubic case',
              affine_profile_phases='checked: full integer affine profiles agree with the original box and all real affine evaluations; the actual complete lag phase has four explicit cubic coefficients, with root-independent top coefficient -2*h*k*(a+3*b); the reverse direction has +2*h*k*(3*a+b), and an exact quarter-slope obstruction forbids cancellation of the factor 8',
              affine_power_returns='checked: uniform affine returns improve C/N^m to E/N^(m+1) for every m>=1, with constants before m,N and data; the bounded-positive-multiplier version retains an actual dense denominator fiber; F32 separately proves the general monomial-in-h return theorem',
              affine_actual_block_relations='checked: for every v>0, constants precede N,unrestricted affine profiles,arbitrary contractive pointwise masks and original horizontal points; failure of an actual compressed v/N block bound gives a bounded positive n with ||n*h*a(x)||<=E/N^4; both true block directions and the full factor 8*n1*n2 are retained without requiring common roots or common successful lag sets',
              affine_top_relation='checked: at least rho*N actual large compressed affine blocks force a bounded positive multiple of the current slope within E/N^5; constants precede all original data; the exact horizontal-point-to-lag image preserves cardinality, and the contrapositive supplies a true no-relation block count',
              affine_no_relation_operator='checked: positive Q,E,N0 precede N,slopes,intercepts and masks; contractive masks vanishing on N^(-5) slope-relation rows have original response energy <=s^2 times the same input energy, without any structural count premise; F29 combines this with actual children and degree-zero freezing conditional on the explicit external two-coefficient Weyl input',
              affine_constant_children='checked: the explicit all-root major-arc grid has circle error epsilon/(2*N^3); a slope relation at N^(-5) makes each original vertical increment a major-arc point; the positive child count precedes N and every coefficient, the finite offsets precede slope and intercept fields, and an actual point assignment independent of the intercept gives global constant-in-y children b(x)+offset with the same original point error; these are not global constant-frequency candidates',
              affine_freezing_reduction='checked: F27 proves complete affine freezing from UniformConstantFreezing using actual children, assignments and the no-relation operator; F29 discharges the degree-zero core premise from CubicTwoCoefficientWeylInput, leaving only that explicit external analytic premise in the final affine theorem; no new axiom or proved external theorem is asserted',
              cube_extraction='PARTIAL overall: original responses yield prepared distinct high-weight real seven-cubes conditional on the external concatenation input; original transport, actual Gram estimates, dense monomial returns including the critical m=D case, actual ordinary children and full ordinary degree induction are checked; ordinary freezing now has only its two explicit external Weyl premises; structural output types and existence, realization, general structural counts, rational descents and uniform structural termination remain open; external deep proofs and source adapters are not asserted proved',
              degree_zero_fourier_passage='checked: exact positive translation multiplier and Fourier diagonalization, counting-energy Parseval with cancellation of the group size, injective cyclic input zero extension and all original endpoint/response recovery; every cyclic character is represented by one circle frequency for all natural powers; a uniform-in-xi horizontal estimate implies the original FiniteMinorEstimate with the same Q,N0; F29 now supplies that horizontal estimate from the explicit unproved CubicTwoCoefficientWeylInput',
              horizontal_cubic_gram='checked: exact horizontal kernel action, collision-to-I_h bijection, full double and single label sums, diagonal 1/N, each entry norm <=1/N, and all four coefficients of the true cubic-plus-quadratic phase; two coefficient relations with one q give the original current-row return with multiplier 3*q and error 4*C/N^2; an exact nonzero-frequency obstruction prevents inference from the cubic difference alone',
              constant_affine_freezing_from_external_weyl='checked conditionally: CubicTwoCoefficientWeylInput gives actual large-entry returns, dense current-row returns at N^(-3), true major-arc membership, the scalar count and Schur bound uniform in xi, the original degree-zero estimate and complete affine freezing; all constants precede N and unrestricted original coefficients, all roots and original responses are retained; the external analytic input is a function premise, not a new axiom or proved theorem, and its conversion from a library theorem is not yet formalized',
              ordinary_polynomial_phase='checked for every degree bound: genuine full-integer real polynomial profiles recover the same original responses and complete circle double phase; affine substitution preserves bounded degree and multiplies its indexed top coefficient by the slope power, including zero and lower actual degrees; for D>=2 the actual degree-(D+2) coefficient is -3*k*(2*h)^D*a_D(x+h), independent of the successful root, and the phase degree is <=D+2; an exact D=1 obstruction prevents applying that formula to the affine exception; the uniform ordinary target and its D=0,1 bases match the existing conditional freezing results',
              ordinary_single_block_relation='checked conditionally for every D>=2: PolynomialLeadingWeylInput on actual lag intervals, the proved many-lag extraction and bounded-multiplier affine returns in k give a positive bounded n with ||n*h^D*a_D(current row)||<=E/N^(D+3) from each actual compressed large block; constants precede N, unrestricted original polynomial coefficients, masks and horizontal points; reversal uses only the true compressed block adjoint, retains the factor 3*2^D, and does not synchronize successful roots; the analytic input remains explicit and unproved, while F32 now proves the subsequent nonlinear returns internally',
              ordinary_lower_children='checked without an external or monomial-return premise: from an actual N^(-(2*D+3)) top relation, every original y^D increment lies in a cubic major arc; all-root grid offsets and their positive count precede N and coefficient fields; actual point assignments depend only on the top field, and real polynomial children erase the indexed top coefficient and add a real constant, retaining every nonconstant lower coefficient and having degree <=D-1; the supported circle error is epsilon/(2*N^3), including zero and lower actual degrees; an exact half-frequency obstruction forbids discarding root branches',
              monomial_return_obligation='DISCHARGED at F32: monomial_dense_returns proves MonomialDenseReturns with no unproved core or external premise, including every m>=D>=1; actual bounded clusters, center-independent rational interpolation with integer denominators cleared first, a finite uniform node-pattern bound, exact same-sign retention and actual rounding fibers give positive bounded q and N^(-(m+D)) error; all constants precede N, the original circle coefficient and retained set',
              ordinary_conditional_degree_induction='checked: the F31 modular degree induction retains its explicit return premise, and F32 substitutes the proved monomial_dense_returns witness; uniform_ordinary_freezing_of_weyl now assumes only CubicTwoCoefficientWeylInput and PolynomialLeadingWeylInput, both explicit external analytic premises; all actual block counts, same-input no-relation bounds, lower-degree children, circle branches, point assignments and degree termination are supplied by proved core arguments; this does not prove general structural freezing, WeightedCapture or P0',
              monomial_seed='checked for every D: a uniform integer bucket count extracts D+1 distinct actual retained integers, represented by an injective bounded relative pattern at an arbitrary center; rational Lagrange interpolation and prior denominator clearing give an integer functional at every center; finitely many relative patterns give uniform positive multiplier and absolute-coefficient bounds before N and all original frequency/error data',
              monomial_amplification='checked for every m>=D>=1: an actual sign retains at least half the original returns, with exact reflection provenance and power parity; the nearest real lift of the bounded seed has bounded N^D range; one actual rounding fiber has macroscopic diameter and the nonnegative power-gap inequality gives the full N^(-D) improvement, including m=D, without a derivative estimate or discarding circle roots',
              proof_scope='Phase algebra, exact original input geometry and weighted finite adjoints, response comparison, full-label metric and scaling, complete circle roots and grids, original-response cube preparation from explicit external concatenation, full internally proved dense monomial returns, ordinary polynomial freezing in every fixed degree from only two explicit external Weyl inputs; actual observation algebra, topology and lattice results under literal structural presentations, unique full-quotient invariant probability, exact original base marginal and global zero cutoff means for specified measurable sections with constants; conditional reductions to capture and P0, which remain unproved')
(OUT / 'result.json').write_text(json.dumps(result, indent=2) + '\n', encoding='utf-8')
print(f'Build passed; {len(audit)} theorem declarations audited; only standard foundations occur.')
print('P0 and WeightedCapture remain unproved propositions.')
