"""Build actual proofs, then audit every project theorem's transitive axioms."""
from pathlib import Path
import json
import re
import shutil
import subprocess
import sys

sys.stdout.reconfigure(encoding='utf-8')

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'verification'
OUT.mkdir(exist_ok=True)
lake = shutil.which('lake')
if not lake:
    raise SystemExit('Lake is unavailable')

def run(args, filename):
    result = subprocess.run([lake, *args], cwd=ROOT, capture_output=True,
                            encoding='utf-8', errors='replace')
    output = result.stdout + result.stderr
    (OUT / filename).write_text(output, encoding='utf-8')
    if result.returncode:
        print(output)
        raise SystemExit(result.returncode)
    return output

run(['build', 'GMZP0', 'GMZP0.Audit'], 'build.log')
output = run(['env', 'lean', 'GMZP0/Audit.lean'], 'axioms.log')

def without_comments(source):
    """Remove line and nested block comments before the complementary lexical guard."""
    out, i, depth = [], 0, 0
    while i < len(source):
        if source.startswith('/-', i):
            depth += 1
            out.append(' ')
            i += 2
        elif depth and source.startswith('-/', i):
            depth -= 1
            out.append(' ')
            i += 2
        elif depth:
            out.append('\n' if source[i] == '\n' else ' ')
            i += 1
        elif source.startswith('--', i):
            end = source.find('\n', i)
            i = len(source) if end < 0 else end
        else:
            out.append(source[i])
            i += 1
    if depth:
        raise SystemExit('Unclosed Lean block comment')
    return ''.join(out)

theorems = set()
for path in (ROOT / 'GMZP0').glob('*.lean'):
    source = without_comments(path.read_text(encoding='utf-8'))
    for name in re.findall(r'\btheorem\s+(\w+)', source):
        theorems.add('GMZP0.' + name)
    # This lexical guard complements, and does not replace, the kernel axiom report.
    if re.search(r'\b(?:sorry|admit|axiom)\b', source):
        raise SystemExit(f'Unproved placeholder or axiom declaration in {path.name}')
reports = re.findall(r"'(GMZP0\.\w+)' depends on axioms: \[([^\]]*)\]", output)
allowed = {'propext', 'Classical.choice', 'Quot.sound'}
audit = {}
for name, values in reports:
    axioms = {v.strip() for v in values.split(',') if v.strip()}
    if not axioms <= allowed:
        raise SystemExit(f'Unexpected axiom dependency: {name}: {axioms - allowed}')
    audit[name] = sorted(axioms)
if set(audit) != theorems:
    raise SystemExit(f'Incomplete audit: missing={theorems - set(audit)}; extra={set(audit) - theorems}')
result = dict(build='passed', checked_theorems=len(audit), transitive_axioms=audit,
              main_P0='NOT_proved', weighted_capture='NOT_proved',
              observation_integer_lattice='checked at F37: a supplied actual finite real basis represented by rational coordinate polynomials, with the actual subgroup coordinate image equal to the full integer grid, implies DiscreteTopology of the original integer-valued subgroup and real span equal to V; this does not construct the rational presentation, prove a cocompact quotient theorem, or install a normed IsZLattice instance',
              observation_integer_basis='checked at F37: separating actual subgroup evaluations admit a determining family of at most dim(V) points; exact integer evaluation embeds the original integer-valued subgroup into a finite free integer module, and a basis of its actual range gives a finite integer basis; no basis height bound or adaptation to W is proved',
              observation_finite_dimension='checked at F36: actual uniformly bounded-degree coordinate polynomial representatives put V in a finite-dimensional polynomial-value image; finrank(V) is bounded by the fixed restricted polynomial space, and the actual pointwise topology is the finite-dimensional module topology; W is closed',
              observation_topological_group='checked at F36: finite-dimensional continuous functions have jointly continuous evaluation; actual left translations, right-semidirect multiplication and inverse are jointly continuous; continuous coordinates and the same uniform representative degree bound supply these hypotheses; Lie structure and lattice cocompactness are not inferred',
              observation_rational_difference='checked at F36: every vector polynomial has equal real spans of all real values and actual coefficients; a surjective coordinate map and a literal rational polynomial matrix for actual basis translation differences give a finite rational-coordinate generating list for W, of size at most basis-card times combined-support-card; constructing that rational presentation from full Malcev data remains open',
              polynomial_parameter_obstruction='checked exact example: the nonzero polynomial X vanishes on the restricted coordinate image {0}, so the coefficient-span proof cannot simply discard its parameter-coverage hypothesis; this does not refute a proved determining-grid theorem or P0',
              observation_group_algebra='checked at F33: actual left-translation function module, constructed difference space, right semidirect group laws and inverse, integer-valued subgroup and all right lattice correction terms; F35 additionally proves commutators and nilpotence under explicit flag/triangular hypotheses; F36 proves topological group structure and rational W from explicit coordinate/matrix presentations; F37 proves fiber lattice discreteness and full real span from an actual rational polynomial basis and integer-grid presentation; constructing the full rational Malcev presentation and the group lattice cocompactness remains open',
              observation_commutator='checked at F35: the actual subgroup commutator of H equals the pairs with base in [G,G] and fiber in the real difference span W; arbitrary real multiples are themselves generated by actual base-fiber commutators, with no closure enlargement or abelian-base assumption',
              observation_nilpotence='checked: a nilpotent base of class c and actual lowering flag of height K give lowerCentralSeries(H,c+K)=bottom; triangular coordinates with correction degree D and observation degree R give class(H)<=c+R*(D+1)^m+1, uniformly in coefficients; full rational Malcev presentation and Lie/topological structure remain open',
              observation_actual_characters='checked: every actual real-valued group character decomposes into base and additive fiber restrictions, and the fiber annihilates all of W; in the product topology with the pointwise observation subspace topology, continuity proves real linearity, source-term cancellation and a nontrivial component pair; actual lattice integrality restricts to both components; bounded integer bases and their quantitative bounds remain open',
              observation_commutator_obstruction='checked exact affine-function example over the additive real base: the base-fiber commutator is the nonzero constant-one fiber, so an abelian base does not make H abelian; not a counterexample to P0',
              observation_quotient='checked: fixed unit-modulus observation on the actual coset quotient by a possibly nonnormal subgroup; right lattice multiplication adds an actual integer to the real phase, so its circle value is invariant',
              observation_original_phase='checked: the curve (g, source*1 - A*(F composed with L_g)) gives the exact complete double phase and lag sum, with the same original label set and each original root; the observation-profile response uses the same input and all original labels; existence of a model for arbitrary original theta is not supplied',
              observation_character='checked: linear fiber functionals annihilating the constructed W combine with base characters to give actual group characters; 1 in W removes the source term; F34 constructs the common lowering flag from actual triangular coordinate corrections and bounded-degree polynomial representatives; F35 derives the linear form for actual continuous characters; the full rational Malcev presentation and bounded integer-character bases remain open',
              weighted_polynomial_lowering='checked at F34 for actual multivariate polynomial supports: coordinate corrections of weight strictly below their coordinate weight imply substitution preserves every weighted bound and lowers the actual polynomial difference by one; constants, zero terms and top cancellation are included',
              coordinate_observation_flag='checked: exact evaluation intertwines actual left translation with the proved polynomial substitution; intersecting the image of weighted support spaces with V constructs increasing flag levels with zero bottom and a supplied uniform top; no observation function is replaced by an unrelated polynomial witness',
              triangular_observation_structure='checked: for m triangular coordinates with all correction degrees <=D and actual observation representatives of degree <=R, weights (D+1)^i and flag height R*(D+1)^m+1 are chosen before coefficients and translations; the constructed flag proves 1 in W and W proper for a nonconstant module; matching the complete rational Malcev presentation remains open',
              observation_integer_saturation='checked: the actual additive subgroup W intersect V_Z is saturated inside V_Z, using nonzero-scalar cancellation only in the real vector space; full lattice, rationality, quotient integer bases and circle-root conclusions are not asserted',
              weighted_degree_obstruction='checked exact polynomial identity: X_1 -> X_1+X_0 gives a difference of unchanged ordinary total degree one, while the explicit triangular weights make the difference strictly lower; this refutes the unweighted shortcut, not P0',
              observation_obstruction='checked exact affine-coordinate example: omitting the left pullback changes the circle phase by 1/2; this refutes an algebraic shortcut, not P0 or structural freezing',
              conditional_P0_reduction='checked: WeightedCapture -> P0',
              conditional_terminal_capture='checked: explicit model approximation and finite minor-arc operator estimates imply original-weight finite capture',
              original_first_adjoint='checked: exact finite adjoint, endpoint Gram expansion, I/N same-horizontal block, original-weight energy lower bound and first grouped TT* inequality',
              second_adjoint_statistic='checked with explicit horizontal window X; normalized second diagonal <= mu(D)/N; complete original-label reindexing proves equality to the finite lag-indexed signed statistic at total scale N^(-6)',
              safe_window='checked: M=ceil(64/kappa), c=kappa/(4M), exact interval partition, original mass and supported original targets',
              positive_safe_statistic='checked: constants and scale threshold precede all original data; exact finite and lag statistics are equal and >= 2*zeta > 0, with original responses retained',
              lag_reindexing='checked: single block, full double-label sum, (r1,r2) to (k,r) and t=r+k-h finite-sum bijections; k=0 contribution explicit, nonnegative and <= mu(D)/N; original targets and weights preserved',
              rerooted_average='checked: exact g(k)e(P(k)) factorization, B normalized by N, S_lag+D_lag equals N^(-5) outer weighted sum, |g| and |B| <= 1, uniform positive finite modulus average',
              cyclic_average='checked: original supported field values and B survive cyclic embedding; complete horizontal reindexing has 2N shifts; exact finite modulus average = (2q/N^2) * cyclic modulus average; constants precede N, q and all original data; cyclic mean >= zeta/128, with weights in [0,1] on a 2qN^3-point sample space',
              prime_modulus='checked from Mathlib Bertrand: for every N>0 there is a prime 64N^2<q<128N^2',
              smoothing='checked: interval translation error for all signed shifts and empty intervals; four independent shifts on exactly (2*ell+1)^4 points; N-normalized error <= 8*ell/N <= a/8; the smoothed original weighted mean is >=7*a/8 with all constants preceding N, q and original data',
              cubic_faces='checked: explicit four unit circle-phase factors, each independent of its own coordinate; exact factorization of the actual cyclic smoothed sequence',
              box_cauchy_schwarz='checked for every dimension: coordinate doubling preserves unit face factors and independence; nonnegative recursively defined box moments and exact root-power identity; actual four-shift sequence is bounded by its box norm',
              positive_box_average='checked: weights removed only from a nonnegative box norm; full lag extension costs (2N+1)/N<=3; finite moment Jensen gives average box moment >=(a/4)^16 on 2qN^3(2N+1) outer samples; constants precede N, q and original data, original mass and complete response retained',
              cube_expansion='checked in every dimension: exact complex equality of recursive moment and full Boolean-vertex product with multiplicities and parity conjugation; four-dimensional shift pairs have (2*ell+1)^8 points',
              cube_rerooting='checked: full cyclic average reindexed by Y=y+2hk with explicit inverse; sixteen weights and alternating alignments factored; t-cubic coefficient is minus the signed original frequency sum and independent of k',
              weighted_time_average='checked: full t average separated by an exact finite bijection; all sixteen weights remain in an average >=(a/4)^16 with constants before N, q and original data; each nonzero-weight cube vertex is an actual retained original base point with the original complete response',
              linear_weyl='checked: inverse chord and geometric sums give ||a|| <= 1/(2*rho*N) for every affine phase and every integer interval with original N normalization',
              weyl_differencing='checked: exact whole pair-sum identity, explicit zero shift <=1, at least N*rho^2/4 nonzero signed shifts above rho^2/8 when N*rho^2>=2; exact N=1 obstruction to dropping this threshold',
              polynomial_differences='checked: exact circle-valued quadratic/cubic derivatives on actual overlap intervals; quadratic large shifts satisfy ||2*h*a2|| <= 4/(rho^2*N), without changing N normalization',
              affine_recurrence_seed='checked: explicit pigeonhole cardinality condition gives two nearby actual returns and a nonzero bounded multiple',
              affine_recurrence='checked: bounded actual rounding fibers amplify epsilon to E*epsilon/N when epsilon*N<=C; positive denominator bound, error factor and threshold precede N, a, b, epsilon and the retained set',
              quadratic_weyl='checked at every N>0: uniform bounded positive denominator and N^(-2) leading-coefficient error; actual shorter intervals retain their original N normalization',
              cubic_weyl='checked at every N>0: exact differencing, actual quadratic denominator fiber and affine recurrence give uniform bounded positive denominator and N^(-3) leading-coefficient error',
              common_denominator='checked: factorial of the uniform denominator bound yields one positive denominator fixed before N and all polynomial/original data',
              weighted_cube_capture='checked: actual original cubic time sum has the checked leading coefficient; successful N^(-3) cube coefficients retain original weighted mean >=(a/4)^16/2, all constants before N,q and original data, with original safe mass and complete responses preserved',
              lag_and_sign_reduction='checked: unused k average removed exactly; simultaneous h/shift reflection fixes every actual vertex and preserves all weights; positive-h mean equals the original signed mean',
              cube_collisions='checked: short shift interval embeds, 2h is nonzero for positive labels at the chosen scale, coordinate resampling gives pair probability <=1/(2*ell+1), all 120 unordered pairs give total <=120/(2*ell+1); zero modular step obstruction proved',
              distinct_original_cube_capture='checked: one scale threshold fixed before q and all original data ensures weighted distinct-vertex cube mass >=(a/4)^16/4 for prime q in the original range, while original safe mass and complete responses remain',
              real_lift_rounding='checked: one [0,1) representative, actual nearest integer, eight positive and eight negative signs, S=l*M+r with |l|<=8 and |r|<=9, and one allowed local correction makes the real cube sum exactly zero',
              global_assignment='checked: restriction of the full point-choice product to any injective vertex family is uniform; local success has probability >=57^(-16); finite weighted expectation produces one choice shared by all cubes without independence between cubes',
              simultaneous_real_lift='checked: M_lift=floor(N^3/E)>=9, all point values lie in M_lift^(-1)Z, |F|<=3, zero original weight gives F=0, supported circle error to d*theta is <=19*E/N^3, and original weighted real-zero cube mass is >=(a/4)^16/(4*57^16); all constants precede N,q and original data, original complete responses retained',
              exact_frequency_mesh='checked: all dimensions d<=7, grid differences k/M with |k|<=384M<1024M, complete j/1024 character orthogonality detects exact real zero; integer-frequency and missing-size-bound obstructions are proved',
              local_four_average='checked: generic finite multiset local moments are nonnegative, local norms have the exact 2^s power and are <=1 for bounded fields; the actual weighted mesh average equals the original real-zero four-cube mass with every multiplicity retained',
              original_local_fibres='checked: uniform original-data theorem gives local fourth-norm sixteenth moment >=beta=(a/4)^16/(4*57^16) and proportion >=beta/2 of actual (x,j) fibres with mean_h local norm >=beta/2; one fixed F, prior constants, original safe mass and full responses preserved',
              finite_fourier='checked: probability-normalized coefficients, unnormalized character synthesis, finite inversion and Parseval; difference correlation has coefficients |nu_hat|^2 with sum exactly E nu^2',
              parameter_difference_density='checked: actual parameter multiplicities give density |G|*count/|A| relative to uniform measure; exact weighted pushforward, independent pair differences, full product law, and density L2 <= |G|*K/|A| from representation multiplicity K',
              local_fourier_expansion='checked: local paired-shift moment equals the global additive cube mean weighted by the actual difference density; explicit nonnegative Fourier expansion retains all multiplicities and yields a bound conditional on every character-twisted global cube average',
              local_global_comparison='checked for every s>=2: all character-twisted global cube averages are bounded by the untwisted moment; actual multiset local moment <= C^s times global moment whenever the original uniform density energy <=C; no unproved twist or mixed-CS premise remains; exact norm and positive lower-moment consequences checked; family concatenation remains unproved',
              global_frequency_average='checked for every 1<=s<=7: the complete finite mesh mean of the global s-moment equals the weighted real-zero cube mass of the same F; actual cyclic seventh-moment identity preserves all original weights, without asserting an unproved positive lower bound',
              twisted_cube='checked: exact derivative recurrence, two-dimensional Fourier energy base, translation square-sum estimate and induction; exact one-dimensional nontrivial-character obstruction also checked',
              pair_geometry='checked: actual integer and cyclic multiplicity <=1+2*A^2; exceptional positive-label pairs have proportion <=3/A<=u/4 for A=ceil(12/u); finite reciprocal-square telescoping, short radius and no-wrap retain all multiplicities; uniform density energy <=2^24*(1+2*A^2)/(u^2*a^2)',
              conditional_original_real_seven='checked: CyclicConcatenationInput implies a uniform positive original weighted real-zero seventh-cube mass; constants precede N,q and original f,theta,lam,mu; the same real lift, original safe-window mass and all complete original responses remain; the external input is not proved',
              external_deep_theorem_scope='user instruction 2026-09-12: prioritize core proofs; external deep theorems are explicit hypotheses, not new axioms, and are not counted as proved',
              seven_cube_preparation='checked: threshold deletion costs <=tau; all 8128 unordered seven-vertex pairs cost <=8128/q; exact unweighted count denominator q^8; a uniform collision threshold and chi/512 level yield at least chi*N/4 good horizontal fibres with at least chi*q^8/4 distinct real-zero seven-cubes each, conditional on the existing concatenation input',
              original_fibre_transport='checked: supplied high-weight cyclic subsets are in the actual original box and D; exact preimage counts give original mass >=|H|*cModel*q*tau/N^3, hence >=64*rho*cModel*tau at the original prime scale; supplied matching values retain the circle error to d*theta and the full original response; no structural model existence is asserted',
              bounded_box_faces='checked in every dimension: the face-factor Cauchy-Schwarz estimate allows norm <=1, with independence and all finite means retained; this is not being asserted as a full mixed Gowers inequality',
              density_normalization_obstruction='checked: on ZMod 2 a constant function disproves use of raw probability masses in place of density relative to the uniform mean',
              finite_block_schur='checked: exact adjoint and Gram energy transfer, finite row-column Schur and symmetric block Schur; all original horizontal blocks have norm <=1/N; arbitrary pointwise contractive masks preserve this bound; at most rho*N actual large compressed blocks per retained horizontal row gives squared energy <=(rho+v+1/N)*input energy, hence the square-root operator bound',
              conditional_minor_block_criterion='checked: the actual pointwise minor-arc mask and original full response yield FiniteMinorEstimate from the displayed compressed-block count; positive rho,v and N0 are chosen before N,Q,p for each target s>0; the count remains open for general structural profiles, while the affine no-relation count is now proved separately',
              square_root_obstruction='checked: exact one-dimensional kernel K=1/2 has Gram row sum R=1/4 but its operator norm is greater than R; this refutes omission of the square root, not P0',
              original_operator_stability='checked: every original finite response operator is a contraction; a phase error <=epsilon on all original labels at nonzero masked points gives squared difference energy <=epsilon^2 times the same input energy; supported circle error epsilon/(2*pi*N^3) suffices',
              child_assignment='checked: arbitrary pointwise single-valued assignment splits output energy exactly; individual minor-arc estimates with different child cutoffs give J*t^2 times input energy; t=s/(3*sqrt(J)) gives (s/3)^2; an exact disjoint-output counterexample shows the J energy loss cannot simply be removed',
              major_arc_transfer='checked: Q>=2*Qchild and circle error <=N^(-3) transfer a child major-arc witness to the parent; contrapositively parent minor implies selected child minor; an exact quarter-frequency counterexample shows closeness is necessary; the paper restricts 0<s<=1 and its a0=s/(12*pi) scale is matched exactly',
              conditional_freezing_step='checked: exact no-relation/error/assigned-child output decomposition and finite energy triangle combine s/3, s/12, s/3 within s; for each 0<s<=1 the numerical rho,v,N0 precede N,J,Q,profiles,assignments and actual points, and the displayed compressed-block count plus supplied approximating children and their finite estimates imply the parent FiniteMinorEstimate; structural production and termination are not asserted',
              widened_original_blocks='checked: all original sources, including boundaries, have their complete block labels in a finite vertical input of size 3*N^2; exact zero extension preserves the same input energy and recovers the actual original block; arbitrary pointwise compressed original blocks inherit widened energy bounds; an exact two-term counterexample refutes direct domination of a truncated phase sum by its complete sum',
              phase_based_large_block='checked: complete pair and lag formulas retain the exact four-factor circle phase and N^(-4) normalization; zero lag costs at most N, and a complete-lag envelope gives the widened energy coefficient (N+sum_nonzero M)/N^4; its comparison with actual compressed original blocks uses exact operator compression',
              many_large_block_lags='checked: for every v>0, c=v^2/8 and a positive N0 are fixed before N,full-integer profile,original profile,mask and horizontal points; failure of the actual compressed original v/N block bound yields at least c*N nonzero lags with |k|<N and complete original-normalized phase sums >=c*N, each at its own actual original source root; no root synchronization or structural polynomial property of an arbitrary extension is asserted',
              cubic_interval_weyl='checked from the existing proved cubic Weyl theorem: actual shorter integer intervals and exact lag overlaps retain the original N denominator; one positive common multiplier precedes N, interval endpoints and every cubic coefficient tuple; no external Weyl input is used for this cubic case',
              affine_profile_phases='checked: full integer affine profiles agree with the original box and all real affine evaluations; the actual complete lag phase has four explicit cubic coefficients, with root-independent top coefficient -2*h*k*(a+3*b); the reverse direction has +2*h*k*(3*a+b), and an exact quarter-slope obstruction forbids cancellation of the factor 8',
              affine_power_returns='checked: uniform affine returns improve C/N^m to E/N^(m+1) for every m>=1, with constants before m,N and data; the bounded-positive-multiplier version retains an actual dense denominator fiber; F32 separately proves the general monomial-in-h return theorem',
              affine_actual_block_relations='checked: for every v>0, constants precede N,unrestricted affine profiles,arbitrary contractive pointwise masks and original horizontal points; failure of an actual compressed v/N block bound gives a bounded positive n with ||n*h*a(x)||<=E/N^4; both true block directions and the full factor 8*n1*n2 are retained without requiring common roots or common successful lag sets',
              affine_top_relation='checked: at least rho*N actual large compressed affine blocks force a bounded positive multiple of the current slope within E/N^5; constants precede all original data; the exact horizontal-point-to-lag image preserves cardinality, and the contrapositive supplies a true no-relation block count',
              affine_no_relation_operator='checked: positive Q,E,N0 precede N,slopes,intercepts and masks; contractive masks vanishing on N^(-5) slope-relation rows have original response energy <=s^2 times the same input energy, without any structural count premise; F29 combines this with actual children and degree-zero freezing conditional on the explicit external two-coefficient Weyl input',
              affine_constant_children='checked: the explicit all-root major-arc grid has circle error epsilon/(2*N^3); a slope relation at N^(-5) makes each original vertical increment a major-arc point; the positive child count precedes N and every coefficient, the finite offsets precede slope and intercept fields, and an actual point assignment independent of the intercept gives global constant-in-y children b(x)+offset with the same original point error; these are not global constant-frequency candidates',
              affine_freezing_reduction='checked: F27 proves complete affine freezing from UniformConstantFreezing using actual children, assignments and the no-relation operator; F29 discharges the degree-zero core premise from CubicTwoCoefficientWeylInput, leaving only that explicit external analytic premise in the final affine theorem; no new axiom or proved external theorem is asserted',
              cube_extraction='PARTIAL overall: original responses yield prepared distinct high-weight real seven-cubes conditional on the external concatenation input; original transport, actual Gram estimates, dense monomial returns including the critical m=D case, actual ordinary children and full ordinary degree induction are checked; ordinary freezing now has only its two explicit external Weyl premises; structural output types and existence, realization, general structural counts, rational descents and uniform structural termination remain open; external deep proofs and source adapters are not asserted proved',
              degree_zero_fourier_passage='checked: exact positive translation multiplier and Fourier diagonalization, counting-energy Parseval with cancellation of the group size, injective cyclic input zero extension and all original endpoint/response recovery; every cyclic character is represented by one circle frequency for all natural powers; a uniform-in-xi horizontal estimate implies the original FiniteMinorEstimate with the same Q,N0; F29 now supplies that horizontal estimate from the explicit unproved CubicTwoCoefficientWeylInput',
              horizontal_cubic_gram='checked: exact horizontal kernel action, collision-to-I_h bijection, full double and single label sums, diagonal 1/N, each entry norm <=1/N, and all four coefficients of the true cubic-plus-quadratic phase; two coefficient relations with one q give the original current-row return with multiplier 3*q and error 4*C/N^2; an exact nonzero-frequency obstruction prevents inference from the cubic difference alone',
              constant_affine_freezing_from_external_weyl='checked conditionally: CubicTwoCoefficientWeylInput gives actual large-entry returns, dense current-row returns at N^(-3), true major-arc membership, the scalar count and Schur bound uniform in xi, the original degree-zero estimate and complete affine freezing; all constants precede N and unrestricted original coefficients, all roots and original responses are retained; the external analytic input is a function premise, not a new axiom or proved theorem, and its conversion from a library theorem is not yet formalized',
              ordinary_polynomial_phase='checked for every degree bound: genuine full-integer real polynomial profiles recover the same original responses and complete circle double phase; affine substitution preserves bounded degree and multiplies its indexed top coefficient by the slope power, including zero and lower actual degrees; for D>=2 the actual degree-(D+2) coefficient is -3*k*(2*h)^D*a_D(x+h), independent of the successful root, and the phase degree is <=D+2; an exact D=1 obstruction prevents applying that formula to the affine exception; the uniform ordinary target and its D=0,1 bases match the existing conditional freezing results',
              ordinary_single_block_relation='checked conditionally for every D>=2: PolynomialLeadingWeylInput on actual lag intervals, the proved many-lag extraction and bounded-multiplier affine returns in k give a positive bounded n with ||n*h^D*a_D(current row)||<=E/N^(D+3) from each actual compressed large block; constants precede N, unrestricted original polynomial coefficients, masks and horizontal points; reversal uses only the true compressed block adjoint, retains the factor 3*2^D, and does not synchronize successful roots; the analytic input remains explicit and unproved, while F32 now proves the subsequent nonlinear returns internally',
              ordinary_lower_children='checked without an external or monomial-return premise: from an actual N^(-(2*D+3)) top relation, every original y^D increment lies in a cubic major arc; all-root grid offsets and their positive count precede N and coefficient fields; actual point assignments depend only on the top field, and real polynomial children erase the indexed top coefficient and add a real constant, retaining every nonconstant lower coefficient and having degree <=D-1; the supported circle error is epsilon/(2*N^3), including zero and lower actual degrees; an exact half-frequency obstruction forbids discarding root branches',
              monomial_return_obligation='DISCHARGED at F32: monomial_dense_returns proves MonomialDenseReturns with no unproved core or external premise, including every m>=D>=1; actual bounded clusters, center-independent rational interpolation with integer denominators cleared first, a finite uniform node-pattern bound, exact same-sign retention and actual rounding fibers give positive bounded q and N^(-(m+D)) error; all constants precede N, the original circle coefficient and retained set',
              ordinary_conditional_degree_induction='checked: the F31 modular degree induction retains its explicit return premise, and F32 substitutes the proved monomial_dense_returns witness; uniform_ordinary_freezing_of_weyl now assumes only CubicTwoCoefficientWeylInput and PolynomialLeadingWeylInput, both explicit external analytic premises; all actual block counts, same-input no-relation bounds, lower-degree children, circle branches, point assignments and degree termination are supplied by proved core arguments; this does not prove general structural freezing, WeightedCapture or P0',
              monomial_seed='checked for every D: a uniform integer bucket count extracts D+1 distinct actual retained integers, represented by an injective bounded relative pattern at an arbitrary center; rational Lagrange interpolation and prior denominator clearing give an integer functional at every center; finitely many relative patterns give uniform positive multiplier and absolute-coefficient bounds before N and all original frequency/error data',
              monomial_amplification='checked for every m>=D>=1: an actual sign retains at least half the original returns, with exact reflection provenance and power parity; the nearest real lift of the bounded seed has bounded N^D range; one actual rounding fiber has macroscopic diameter and the nonnegative power-gap inequality gives the full N^(-D) improvement, including m=D, without a derivative estimate or discarding circle roots',
              proof_scope='Phase algebra, exact original input geometry and weighted finite adjoints, response comparison, full-label metric and scaling, complete circle roots and grids, original-response cube preparation from explicit external concatenation, full internally proved dense monomial returns, ordinary polynomial freezing in every fixed degree from only two explicit external Weyl inputs, and conditional reductions to capture and P0')
(OUT / 'result.json').write_text(json.dumps(result, indent=2) + '\n', encoding='utf-8')
print(f'Build passed; {len(audit)} theorem declarations audited; only standard foundations occur.')
print('P0 and WeightedCapture remain unproved propositions.')
